/**
 * Copyright (C) 2026 Sean Chatman.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * Generated by ggen from ontology/jotp-api.ttl — do not edit by hand.
 * Re-generate: cd jotp && ggen sync
 */
package io.github.seanchatmangpt.dtr.jotp;

import org.junit.Test;
import io.github.seanchatmangpt.dtr.DtrTest;

/**
 * DTR documentation for jotp
 * Proc, ProcLink, ProcMonitor, ProcRef, ProcTimer
 * primitives — generated from {@code jotp-api.ttl}.
 *
 * <p>Each {@code @Test} method documents one primitive:
 * <ul>
 *   <li>{@code Proc<S,M>} — Lightweight supervised process with a virtual-thread mailbox</li>
 *   <li>{@code ProcLink<S,M>} — Bidirectional crash link — if either process dies the other is notified</li>
 *   <li>{@code ProcMonitor<S,M>} — One-way watcher that receives a DOWN signal when a process terminates</li>
 *   <li>{@code ProcRef<S,M>} — Opaque handle to a running Proc; used for messaging and monitoring</li>
 *   <li>{@code ProcTimer<M>} — Delivers a message to a process mailbox after a fixed delay</li>
 * </ul>
 */
public class CoreProcessDocTest extends DtrTest {

    // ─────────────────────────────────────────────────────────────────────────
    // Proc<S,M>
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testProcOverview() {
        sayNextSection("Proc<S,M> — Lightweight supervised process with a virtual-thread mailbox");
        say("<code>Proc<S,M></code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.Proc</code>.");

        String[][] methods = new String[3 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>send</code>",
            "<code>void send(ProcRef<S,M> ref, M message)</code>",
            "Delivers a message to the process mailbox asynchronously"
        };
        methods[2] = new String[]{
            "<code>start</code>",
            "<code>ProcRef<S,M> start(S initialState, BiFunction<S,M,S> handler)</code>",
            "Starts the process, returns a ProcRef for subsequent communication"
        };
        methods[3] = new String[]{
            "<code>stop</code>",
            "<code>void stop(ProcRef<S,M> ref)</code>",
            "Gracefully terminates the process and releases the virtual thread"
        };
        sayTable(methods);

        // TODO: add sayAndAssertThat assertions once jotp is a Maven dependency.
        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // ProcLink<S,M>
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testProcLinkOverview() {
        sayNextSection("ProcLink<S,M> — Bidirectional crash link — if either process dies the other is notified");
        say("<code>ProcLink<S,M></code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.ProcLink</code>.");

        String[][] methods = new String[2 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>link</code>",
            "<code>void link(ProcRef<?,?> a, ProcRef<?,?> b)</code>",
            "Creates a bidirectional link between two processes"
        };
        methods[2] = new String[]{
            "<code>unlink</code>",
            "<code>void unlink(ProcRef<?,?> a, ProcRef<?,?> b)</code>",
            "Removes an existing link without killing either process"
        };
        sayTable(methods);

        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // ProcMonitor<S,M>
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testProcMonitorOverview() {
        sayNextSection("ProcMonitor<S,M> — One-way watcher that receives a DOWN signal when a process terminates");
        say("<code>ProcMonitor<S,M></code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.ProcMonitor</code>.");

        String[][] methods = new String[2 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>demonitor</code>",
            "<code>void demonitor(MonitorRef ref)</code>",
            "Cancels the monitor before the target has exited"
        };
        methods[2] = new String[]{
            "<code>monitor</code>",
            "<code>MonitorRef monitor(ProcRef<S,M> target)</code>",
            "Starts monitoring; sends DOWN message to caller on target exit"
        };
        sayTable(methods);

        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // ProcRef<S,M>
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testProcRefOverview() {
        sayNextSection("ProcRef<S,M> — Opaque handle to a running Proc; used for messaging and monitoring");
        say("<code>ProcRef<S,M></code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.ProcRef</code>.");

        String[][] methods = new String[2 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>isAlive</code>",
            "<code>boolean isAlive()</code>",
            "Returns true if the process is still running"
        };
        methods[2] = new String[]{
            "<code>pid</code>",
            "<code>long pid()</code>",
            "Returns the unique process identifier"
        };
        sayTable(methods);

        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // ProcTimer<M>
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testProcTimerOverview() {
        sayNextSection("ProcTimer<M> — Delivers a message to a process mailbox after a fixed delay");
        say("<code>ProcTimer<M></code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.ProcTimer</code>.");

        String[][] methods = new String[2 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>cancel</code>",
            "<code>boolean cancel(TimerRef ref)</code>",
            "Cancels a pending timer; returns true if cancelled before firing"
        };
        methods[2] = new String[]{
            "<code>sendAfter</code>",
            "<code>TimerRef sendAfter(Duration delay, ProcRef<?,M> target, M message)</code>",
            "Schedules a message delivery after the specified delay"
        };
        sayTable(methods);

        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }
}
