/**
 * Copyright (C) 2026 Sean Chatman.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * Generated by ggen from ontology/jotp-api.ttl — do not edit by hand.
 * Re-generate: cd jotp && ggen sync
 */
package io.github.seanchatmangpt.dtr.jotp;

import org.junit.Test;
import io.github.seanchatmangpt.dtr.DtrTest;

/**
 * DTR overview of all jotp OTP primitives — generated from {@code jotp-api.ttl}.
 *
 * <p>jotp brings Erlang/OTP fault-tolerance patterns to Java 26 virtual threads.
 * This test documents every primitive at a glance and serves as the table of
 * contents for the per-category deep-dive tests.
 */
public class JotpOverviewDocTest extends DtrTest {

    @Test
    public void testJotpPrimitivesOverview() {
        sayNextSection("jotp — Java OTP Primitives Overview");
        say("jotp implements Erlang/OTP's battle-tested fault-tolerance patterns on top of "
                + "Java 26 virtual threads (JEP 444). The library provides "
                + "<strong>13 primitives</strong> grouped into "
                + "five categories: core processes, supervision, state management, "
                + "error handling, and runtime services.");

        say("The table below lists every primitive, its Java generic signature, "
                + "and a one-line description. Each category has a dedicated DocTest "
                + "with full method-level coverage.");

        String[][] overview = new String[13 + 1][4];
        overview[0] = new String[]{"Primitive", "Category", "Java Class", "Description"};
        overview[1] = new String[]{
            "Parallel",
            "error",
            "<code>jotp.Parallel</code>",
            "Structured concurrency with fail-fast semantics across multiple tasks"
        };
        overview[2] = new String[]{
            "Result",
            "error",
            "<code>jotp.Result</code>",
            "Railway-oriented error handling: Success<T> or Failure<E>"
        };
        overview[3] = new String[]{
            "Proc",
            "core",
            "<code>jotp.Proc</code>",
            "Lightweight supervised process with a virtual-thread mailbox"
        };
        overview[4] = new String[]{
            "ProcLink",
            "core",
            "<code>jotp.ProcLink</code>",
            "Bidirectional crash link — if either process dies the other is notified"
        };
        overview[5] = new String[]{
            "ProcMonitor",
            "core",
            "<code>jotp.ProcMonitor</code>",
            "One-way watcher that receives a DOWN signal when a process terminates"
        };
        overview[6] = new String[]{
            "ProcRef",
            "core",
            "<code>jotp.ProcRef</code>",
            "Opaque handle to a running Proc; used for messaging and monitoring"
        };
        overview[7] = new String[]{
            "ProcTimer",
            "core",
            "<code>jotp.ProcTimer</code>",
            "Delivers a message to a process mailbox after a fixed delay"
        };
        overview[8] = new String[]{
            "ProcLib",
            "runtime",
            "<code>jotp.ProcLib</code>",
            "Application startup coordination: ensures processes are ready before serving"
        };
        overview[9] = new String[]{
            "ProcRegistry",
            "runtime",
            "<code>jotp.ProcRegistry</code>",
            "Named-process registry: register, lookup, and unregister ProcRefs by name"
        };
        overview[10] = new String[]{
            "ProcSys",
            "runtime",
            "<code>jotp.ProcSys</code>",
            "System introspection: list all live processes, counts, and stats"
        };
        overview[11] = new String[]{
            "EventManager",
            "state",
            "<code>jotp.EventManager</code>",
            "Typed event broadcasting to all registered handler processes"
        };
        overview[12] = new String[]{
            "StateMachine",
            "state",
            "<code>jotp.StateMachine</code>",
            "Complex workflow engine with sealed-type state and event transitions"
        };
        overview[13] = new String[]{
            "Supervisor",
            "supervision",
            "<code>jotp.Supervisor</code>",
            "Fault-recovery tree that automatically restarts crashed child processes"
        };
        sayTable(overview);

        sayNote("Each primitive is documented in detail in its category DocTest: "
                + "CoreProcessDocTest, SupervisorDocTest, StateManagementDocTest, "
                + "ErrorHandlingDocTest, RuntimeServicesDocTest.");
    }

    @Test
    public void testJotpCategorySummary() {
        sayNextSection("Category Summary");
        say("jotp primitives are grouped by responsibility:");

        String[][] categories = new String[][]{
            {"Category", "Primitives", "Purpose"},
            {"core",       "Proc, ProcRef, ProcMonitor, ProcLink, ProcTimer",
                           "Process lifecycle, references, links, and timed messages"},
            {"supervision","Supervisor",
                           "Fault-recovery trees with ONE_FOR_ONE / ONE_FOR_ALL / REST_FOR_ONE"},
            {"state",      "StateMachine, EventManager",
                           "Sealed-type state transitions and typed event broadcasting"},
            {"error",      "Result, Parallel",
                           "Railway-oriented error handling and structured concurrency"},
            {"runtime",    "ProcRegistry, ProcSys, ProcLib",
                           "Named lookup, system introspection, and application startup"}
        };
        sayTable(categories);

        sayNote("Proc: Virtual threads (JEP 444) enable 10M+ concurrent Proc instances");
        sayNote("Supervisor: Restart latency ~200µs measured on Java 26.ea.13 with virtual threads");
    }
}
