/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.seanchatmangpt.dtr.test;

import io.github.seanchatmangpt.dtr.DtrTest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import java.util.Arrays;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.Function;

/**
 * Documentation test for the {@code sayDataFlow} innovation in DTR.
 *
 * <p>{@code sayDataFlow} documents a data transformation pipeline by running a
 * sample value through an ordered sequence of named stages, each driven by a
 * {@link Function}{@code <Object, Object>} transform. After every stage the
 * intermediate result is captured and emitted as a table row, producing a
 * traceable, auditable record of the full transformation without any manual
 * intermediate logging.</p>
 *
 * <p>This test class covers three representative pipeline shapes:</p>
 * <ol>
 *   <li><strong>String processing</strong> — trim, uppercase, split</li>
 *   <li><strong>Numeric transformation</strong> — parse, double, format</li>
 *   <li><strong>Map enrichment</strong> — validate, enrich, serialize</li>
 * </ol>
 *
 * <p>All measurements are real ({@code System.nanoTime()}) on the executing JVM.
 * No numbers are estimated or hand-written.</p>
 *
 * <p>Running this test generates {@code DataFlowDocTest.md} (and companion
 * {@code .tex}, {@code .html}, {@code .json}) under
 * {@code target/docs/test-results/}.</p>
 */
@TestMethodOrder(MethodOrderer.MethodName.class)
public class DataFlowDocTest extends DtrTest {

    @AfterAll
    static void afterAll() {
        finishDocTest();
    }

    // =========================================================================
    // Test 1: String processing pipeline
    // =========================================================================

    /**
     * Documents a three-stage string processing pipeline: Trim → Uppercase → Split.
     *
     * <p>The pipeline takes a raw, padded string and normalizes it into an array
     * of uppercase tokens. Each stage is represented as a named transform so that
     * the generated documentation shows exactly which value entered and left each
     * stage boundary.</p>
     */
    @Test
    void a1_sayDataFlow_string_processing_pipeline() {
        sayNextSection("sayDataFlow — String Processing Pipeline");

        say(
            "A string processing pipeline is the simplest and most common transformation " +
            "shape in enterprise systems: raw input arrives with uncontrolled whitespace " +
            "and casing, and must be normalized before storage, comparison, or routing. " +
            "`sayDataFlow` documents each stage so that readers understand the exact value " +
            "at every boundary — not just the final result."
        );

        sayCode("""
                String sample = " hello world ";

                List<String> stages = List.of("Trim", "Uppercase", "Split");

                List<Function<Object, Object>> transforms = List.of(
                    s -> s.toString().trim(),
                    s -> s.toString().toUpperCase(),
                    s -> s.toString().split(" ")
                );

                sayDataFlow("String Normalization Pipeline", stages, transforms, sample);
                """, "java");

        say(
            "The table below is generated by `sayDataFlow` executing the pipeline " +
            "against the sample input `\" hello world \"`. Each row captures the stage " +
            "label and the value produced by that stage's transform."
        );

        String sample = " hello world ";

        List<String> stages = List.of("Trim", "Uppercase", "Split");

        List<Function<Object, Object>> transforms = List.of(
            s -> s.toString().trim(),
            s -> s.toString().toUpperCase(),
            s -> Arrays.toString(s.toString().split(" "))
        );

        long start = System.nanoTime();
        sayDataFlow("String Normalization Pipeline", stages, transforms, sample);
        long pipelineNs = System.nanoTime() - start;

        sayKeyValue(new LinkedHashMap<>(Map.of(
            "Sample input",      "\"" + sample + "\"",
            "Stages",            String.join(" -> ", stages),
            "Pipeline overhead", pipelineNs + " ns",
            "Java version",      System.getProperty("java.version")
        )));

        sayNote(
            "The Split stage uses `Arrays.toString()` so the resulting array is " +
            "rendered as a readable string in the documentation table rather than " +
            "the raw JVM object reference."
        );

        sayWarning(
            "Each transform receives the output of the preceding stage as its " +
            "argument. Transforms must be written to accept the actual runtime type " +
            "produced by the prior stage, not the original input type. " +
            "Mismatched assumptions cause `ClassCastException` at pipeline execution time."
        );
    }

    // =========================================================================
    // Test 2: Numeric transformation pipeline
    // =========================================================================

    /**
     * Documents a three-stage numeric transformation pipeline: Parse → Double → Format.
     *
     * <p>The pipeline accepts a string representation of an integer, converts it to
     * a numeric value, doubles it, and formats the result as a labelled string.
     * This pattern is ubiquitous in event-driven systems that receive numeric payloads
     * as serialized strings from upstream producers.</p>
     */
    @Test
    void a2_sayDataFlow_number_transformation() {
        sayNextSection("sayDataFlow — Numeric Transformation Pipeline");

        say(
            "Numeric pipelines frequently cross type boundaries: a value arrives as a " +
            "string, is parsed to a number, transformed arithmetically, and re-serialized " +
            "for downstream consumption. `sayDataFlow` makes each type transition explicit " +
            "and auditable, eliminating the silent type coercions that cause production bugs."
        );

        sayCode("""
                String sample = "21";

                List<String> stages = List.of("Parse", "Double", "Format");

                List<Function<Object, Object>> transforms = List.of(
                    s  -> Integer.parseInt(s.toString()),
                    n  -> ((Integer) n) * 2,
                    n  -> "Result: " + n
                );

                sayDataFlow("Integer Doubling Pipeline", stages, transforms, sample);
                """, "java");

        say(
            "The sample value `\"21\"` is a string that a producer emitted as part of " +
            "a serialized message payload. After Parse it becomes an `Integer`, after " +
            "Double it becomes `42`, and after Format it becomes the labelled string " +
            "`\"Result: 42\"` ready for downstream rendering or logging."
        );

        String sample = "21";

        List<String> stages = List.of("Parse", "Double", "Format");

        @SuppressWarnings("unchecked")
        List<Function<Object, Object>> transforms = List.of(
            s  -> Integer.parseInt(s.toString()),
            n  -> ((Integer) n) * 2,
            n  -> "Result: " + n
        );

        long start = System.nanoTime();
        sayDataFlow("Integer Doubling Pipeline", stages, transforms, sample);
        long pipelineNs = System.nanoTime() - start;

        sayTable(new String[][] {
            {"Stage",    "Input type",    "Output type",   "Operation"},
            {"Parse",    "String",        "Integer",       "Integer.parseInt()"},
            {"Double",   "Integer",       "Integer",       "n * 2"},
            {"Format",   "Integer",       "String",        "\"Result: \" + n"},
        });

        sayKeyValue(new LinkedHashMap<>(Map.of(
            "Sample input",      sample,
            "Expected output",   "Result: 42",
            "Pipeline overhead", pipelineNs + " ns",
            "Java version",      System.getProperty("java.version")
        )));

        sayNote(
            "The explicit `((Integer) n)` cast in the Double stage is intentional. " +
            "Because the transform list is `List<Function<Object, Object>>`, the " +
            "compiler cannot infer that the Parse stage produced an `Integer`. " +
            "The cast makes the type assumption visible and compiler-verifiable at " +
            "the point of use, rather than hidden in an implicit `Number` widening."
        );
    }

    // =========================================================================
    // Test 3: Map enrichment pipeline
    // =========================================================================

    /**
     * Documents a three-stage Map enrichment pipeline: Validate → Enrich → Serialize.
     *
     * <p>The pipeline receives a raw event {@code Map<String, Object>}, validates
     * that required fields are present, enriches the map with computed metadata
     * (a processing timestamp and a derived correlation ID), and serializes the
     * final map to a compact JSON-like string for downstream dispatch.</p>
     *
     * <p>This pattern is canonical in event-driven microservices architectures
     * where incoming domain events must be augmented with routing metadata before
     * being forwarded to a message broker.</p>
     */
    @Test
    @SuppressWarnings("unchecked")
    void a3_sayDataFlow_event_enrichment() {
        sayNextSection("sayDataFlow — Event Map Enrichment Pipeline");

        say(
            "Event enrichment pipelines are the backbone of event-driven microservices: " +
            "a raw domain event arrives as a `Map<String, Object>`, is validated against " +
            "a schema, enriched with routing metadata, and serialized for broker dispatch. " +
            "`sayDataFlow` documents the map state at each stage boundary, providing an " +
            "auditable trace that is impossible to produce with conventional logging."
        );

        sayCode("""
                var sample = new HashMap<>(Map.of("id", "42", "type", "order"));

                List<String> stages = List.of("Validate", "Enrich", "Serialize");

                List<Function<Object, Object>> transforms = List.of(

                    // Validate: assert required fields are present, return map unchanged
                    raw -> {
                        var m = (Map<String, Object>) raw;
                        if (!m.containsKey("id") || !m.containsKey("type")) {
                            throw new IllegalArgumentException("Missing required field");
                        }
                        return m;
                    },

                    // Enrich: add processing timestamp and correlation ID
                    raw -> {
                        var m = new HashMap<>((Map<String, Object>) raw);
                        m.put("processedAt", System.currentTimeMillis());
                        m.put("correlationId", "corr-" + m.get("id"));
                        return m;
                    },

                    // Serialize: convert to compact key=value string for broker dispatch
                    raw -> {
                        var m = (Map<String, Object>) raw;
                        var sb = new StringBuilder("{");
                        m.forEach((k, v) -> sb.append(k).append('=').append(v).append(", "));
                        if (sb.length() > 1) sb.setLength(sb.length() - 2);
                        sb.append('}');
                        return sb.toString();
                    }
                );

                sayDataFlow("Order Event Enrichment Pipeline", stages, transforms, sample);
                """, "java");

        say(
            "The sample below begins as a minimal order event with only `id` and `type`. " +
            "After Validate the map is returned unchanged — the stage is a gate, not a " +
            "transformer. After Enrich the map carries two additional fields: " +
            "`processedAt` (epoch milliseconds) and `correlationId` (derived from the " +
            "event `id`). After Serialize the map is rendered as a flat string ready " +
            "for message broker headers or log emission."
        );

        var sample = new HashMap<>(Map.of("id", "42", "type", "order"));

        List<String> stages = List.of("Validate", "Enrich", "Serialize");

        List<Function<Object, Object>> transforms = List.of(

            // Validate: assert required fields are present, return map unchanged
            raw -> {
                var m = (Map<String, Object>) raw;
                if (!m.containsKey("id") || !m.containsKey("type")) {
                    throw new IllegalArgumentException("Missing required field: id or type");
                }
                return m;
            },

            // Enrich: add processing timestamp and correlation ID
            raw -> {
                var m = new HashMap<>((Map<String, Object>) raw);
                m.put("processedAt", System.currentTimeMillis());
                m.put("correlationId", "corr-" + m.get("id"));
                return m;
            },

            // Serialize: convert to compact key=value string for broker dispatch
            raw -> {
                var m = (Map<String, Object>) raw;
                var sb = new StringBuilder("{");
                // Sort keys for deterministic documentation output
                new java.util.TreeMap<>(m).forEach(
                    (k, v) -> sb.append(k).append('=').append(v).append(", ")
                );
                if (sb.length() > 1) sb.setLength(sb.length() - 2);
                sb.append('}');
                return sb.toString();
            }
        );

        long start = System.nanoTime();
        sayDataFlow("Order Event Enrichment Pipeline", stages, transforms, sample);
        long pipelineNs = System.nanoTime() - start;

        sayTable(new String[][] {
            {"Stage",      "Role",                   "Input shape",           "Output shape"},
            {"Validate",   "Gate — no mutation",      "Map{id, type}",         "Map{id, type} (unchanged)"},
            {"Enrich",     "Augment with metadata",   "Map{id, type}",         "Map{id, type, processedAt, correlationId}"},
            {"Serialize",  "Flatten for dispatch",    "Map{4 fields}",         "String key=value payload"},
        });

        sayKeyValue(new LinkedHashMap<>(Map.of(
            "Sample input",      sample.toString(),
            "Pipeline overhead", pipelineNs + " ns",
            "Java version",      System.getProperty("java.version")
        )));

        sayNote(
            "Keys are sorted with `TreeMap` inside the Serialize stage to produce " +
            "deterministic documentation output across JVM runs. Without explicit " +
            "ordering, `HashMap` iteration order is undefined in Java and the " +
            "serialized string would differ between runs, undermining the " +
            "reproducibility guarantee that DTR documentation provides."
        );

        sayWarning(
            "The Validate stage performs an unchecked cast from `Object` to " +
            "`Map<String, Object>`. This is unavoidable given the erased generic " +
            "signature of `Function<Object, Object>`. The `@SuppressWarnings(\"unchecked\")` " +
            "annotation on the test method documents that this cast is intentional " +
            "and the caller is responsible for providing the correct runtime type."
        );
    }
}
