/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.seanchatmangpt.dtr.test;

import io.github.seanchatmangpt.dtr.DtrTest;
import io.github.seanchatmangpt.dtr.evolution.GitHistoryReader;
import io.github.seanchatmangpt.dtr.rendermachine.RenderMachineImpl;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.LinkedHashMap;
import java.util.List;

/**
 * 80/20 Blue Ocean Innovation: Git Repository Intelligence Documentation.
 *
 * <p>Demonstrates how DTR's {@code sayEvolutionTimeline} and companion git
 * introspection capabilities turn a repository's commit history into living
 * documentation. Unlike static README sections about code history, every
 * table here is re-generated on each CI run, so the documentation cannot
 * drift from the actual history.</p>
 *
 * <p>Key methods showcased:</p>
 * <ul>
 *   <li>{@code sayEvolutionTimeline(Class, int)} — git log per source file</li>
 *   <li>{@code sayCallSite()} — provenance: who asked for this documentation</li>
 *   <li>{@code sayAsciiChart} — visualise commit frequency from real timeline data</li>
 *   <li>Raw {@link ProcessBuilder} git commands for repository-level metrics</li>
 * </ul>
 */
@TestMethodOrder(MethodOrderer.MethodName.class)
public class GitIntelligenceDocTest extends DtrTest {

    @AfterAll
    static void afterAll() {
        finishDocTest();
    }

    // =========================================================================
    // a1 — Overview
    // =========================================================================

    @Test
    void a1_overview() {
        sayNextSection("Git Repository Intelligence: Documenting Code Evolution");

        say("Every Java class carries an invisible trail: the series of commits that " +
                "shaped it. DTR surfaces this trail as first-class documentation " +
                "using `sayEvolutionTimeline`, which shells out to " +
                "`git log --follow` and renders a structured table of commits, " +
                "dates, authors, and subjects. The documentation is generated " +
                "at test-run time, so it reflects the actual history — not a " +
                "developer's memory of it.");

        say("This is the Blue Ocean insight: no other Java documentation framework " +
                "treats commit history as a documentation artefact. Static wikis go " +
                "stale within weeks. DTR-generated evolution timelines are always " +
                "current because they are produced by running the tests, not by " +
                "editing prose.");

        sayNote("`sayEvolutionTimeline` relies on `git log --follow`. It returns an " +
                "empty table gracefully when git is unavailable (e.g., in a Docker " +
                "layer with no `.git` directory) rather than failing the test.");

        say("The call site below shows exactly which test method requested this " +
                "documentation — provenance metadata for audit trails:");
        sayCallSite();

        sayTable(new String[][] {
                {"DTR Method", "Data Source", "Output"},
                {"sayEvolutionTimeline", "git log --follow", "Commit timeline table"},
                {"sayCallSite", "StackWalker API", "Caller class, method, line"},
                {"sayAsciiChart", "Derived from timeline", "Horizontal bar chart"},
                {"sayKeyValue", "ProcessBuilder git stats", "Repository metadata table"},
        });
    }

    // =========================================================================
    // a2 — Evolution timeline for DtrTest
    // =========================================================================

    @Test
    void a2_evolution_timeline() {
        sayNextSection("Evolution Timeline: DtrTest Git History");

        say("The table below is generated by running `git log --follow` against " +
                "`DtrTest.java` at test execution time. It shows the last five " +
                "commits that touched the core base class, providing a living " +
                "change-log that requires zero manual maintenance.");

        sayEvolutionTimeline(DtrTest.class, 5);

        say("Each column in the timeline table has a specific meaning:");
        sayTable(new String[][] {
                {"Column", "Description"},
                {"Commit", "Short (7-char) SHA-1 hash — click to open in GitHub/GitLab"},
                {"Date", "Author date in ISO-8601 format (YYYY-MM-DD)"},
                {"Author", "Git author name from the commit metadata"},
                {"Subject", "First line of the commit message (the 'what' of the change)"},
        });

        sayNote("Commit subjects use the imperative mood by convention: " +
                "\"Add sayEvolutionTimeline\" not \"Added sayEvolutionTimeline\". " +
                "When a class is renamed, `--follow` traces the history through " +
                "the rename so no commits are silently dropped.");
    }

    // =========================================================================
    // a3 — Repository-level profile via ProcessBuilder
    // =========================================================================

    @Test
    void a3_repository_profile() {
        sayNextSection("Repository Profile: Live Git Statistics");

        say("Beyond per-file history, DTR tests can query repository-level metrics " +
                "by spawning git sub-processes with `ProcessBuilder`. The data below " +
                "is read from the actual repository at test execution time.");

        String commitCount = runGitCommand(
                List.of("git", "log", "--oneline"),
                lines -> String.valueOf(lines.size()),
                "unavailable (git not found)");

        String contributorCount = runGitCommand(
                List.of("git", "shortlog", "-s", "--no-merges"),
                lines -> String.valueOf(lines.size()),
                "unavailable (git not found)");

        String currentBranch = runGitCommand(
                List.of("git", "rev-parse", "--abbrev-ref", "HEAD"),
                lines -> lines.isEmpty() ? "unknown" : lines.get(0).trim(),
                "unavailable (git not found)");

        String lastModified = runGitCommand(
                List.of("git", "log", "-1", "--pretty=format:%as"),
                lines -> lines.isEmpty() ? "unknown" : lines.get(0).trim(),
                "unavailable (git not found)");

        var stats = new LinkedHashMap<String, String>();
        stats.put("Total Commits", commitCount);
        stats.put("Contributors", contributorCount);
        stats.put("Branch", currentBranch);
        stats.put("Last Modified", lastModified);
        sayKeyValue(stats);

        sayCode("""
                // ProcessBuilder pattern for git commands in DTR tests
                var pb = new ProcessBuilder("git", "log", "--oneline")
                        .redirectErrorStream(true);
                var proc = pb.start();
                try (var reader = new BufferedReader(
                        new InputStreamReader(proc.getInputStream()))) {
                    long commitCount = reader.lines().count();
                }
                proc.waitFor();
                """, "java");

        sayNote("All git commands are executed via `ProcessBuilder`, not `Runtime.exec()`. " +
                "`ProcessBuilder` gives explicit control over the argument list (no shell " +
                "injection), stderr redirection, and working directory.");
    }

    // =========================================================================
    // a4 — Hotspot analysis across multiple classes
    // =========================================================================

    @Test
    void a4_hotspot_analysis() {
        sayNextSection("Hotspot Analysis: Which Classes Change Most Often?");

        say("A hotspot is a class that accumulates commits faster than its neighbours. " +
                "High commit frequency signals either active feature development or " +
                "chronic instability — context determines which. The chart below " +
                "derives commit counts from the real evolution timelines of three " +
                "core DTR classes, then renders the comparison as an ASCII bar chart.");

        // DtrTest — always present in the repo
        int dtrTestCommits = GitHistoryReader.read(DtrTest.class, 100).size();

        // RenderMachineImpl — another core class with expected history
        int renderMachineImplCommits = 0;
        try {
            renderMachineImplCommits = GitHistoryReader.read(RenderMachineImpl.class, 100).size();
        } catch (Exception e) {
            // class exists but may have no history in a shallow clone
        }

        // GitHistoryReader itself — likely newer, fewer commits
        int gitHistoryReaderCommits = 0;
        try {
            gitHistoryReaderCommits = GitHistoryReader.read(GitHistoryReader.class, 100).size();
        } catch (Exception e) {
            // graceful fallback
        }

        say("Evolution timelines for the three tracked classes:");
        sayEvolutionTimeline(DtrTest.class, 5);

        say("**RenderMachineImpl** recent history:");
        sayEvolutionTimeline(RenderMachineImpl.class, 5);

        say("Commit frequency comparison (derived from real timeline data, capped at 100 entries):");

        // Use at least 1 for each so the chart renders even in shallow clones
        double[] commitCounts = {
                Math.max(dtrTestCommits, 1),
                Math.max(renderMachineImplCommits, 1),
                Math.max(gitHistoryReaderCommits, 1),
        };
        String[] classLabels = {
                "DtrTest",
                "RenderMachineImpl",
                "GitHistoryReader",
        };
        sayAsciiChart("Commit Frequency (last 100 entries)", commitCounts, classLabels);

        sayTable(new String[][] {
                {"Class", "Commits (sampled)", "Interpretation"},
                {"DtrTest", String.valueOf(dtrTestCommits),
                        dtrTestCommits > 10 ? "Actively maintained base class" : "Stable — few recent changes"},
                {"RenderMachineImpl", String.valueOf(renderMachineImplCommits),
                        renderMachineImplCommits > 10 ? "High churn — core output engine" : "Stable implementation"},
                {"GitHistoryReader", String.valueOf(gitHistoryReaderCommits),
                        gitHistoryReaderCommits > 5 ? "Evolving git integration" : "New or stable utility"},
        });

        sayNote("Counts reflect commits visible in the current clone. Shallow clones " +
                "(depth=1 or depth=50) will show lower numbers than a full clone. " +
                "The relative proportions remain meaningful for hotspot identification.");
    }

    // =========================================================================
    // a5 — Best practices
    // =========================================================================

    @Test
    void a5_best_practices() {
        sayNextSection("Best Practices for Git-Backed Documentation");

        say("These practices are derived from production experience integrating " +
                "`sayEvolutionTimeline` into CI pipelines. They prioritise " +
                "correctness and graceful degradation over completeness.");

        sayOrderedList(List.of(
                "Always pass a `maxEntries` limit to `sayEvolutionTimeline`. " +
                        "A class with 500 commits generates a 500-row table; " +
                        "5-10 entries is enough for a documentation audience.",
                "Treat empty timelines as informative, not as failures. " +
                        "A new class with zero history is worth documenting: " +
                        "it signals that no production incident has forced a change yet.",
                "Combine `sayEvolutionTimeline` with `sayCallSite` so readers " +
                        "know exactly which test method produced the timeline " +
                        "and when. Provenance is part of documentation quality.",
                "Run git-backed tests in CI with a full clone (`fetch-depth: 0` " +
                        "in GitHub Actions). Shallow clones truncate history and " +
                        "produce misleading commit counts.",
                "Pair `sayEvolutionTimeline` with `sayAsciiChart` to give " +
                        "decision-makers a single-screen hotspot view without " +
                        "requiring them to read commit tables.",
                "Use `ProcessBuilder` rather than `Runtime.exec(String)` for all " +
                        "git sub-processes. The array form prevents shell injection " +
                        "and makes argument lists auditable.",
                "Catch both `IOException` (process spawn failure) and non-zero " +
                        "exit codes separately. Exit code 128 from git usually means " +
                        "the working directory is not inside a repository."
        ));

        sayNote("`sayEvolutionTimeline` only works inside a git repository. " +
                "When the test runs outside a git context — for example, " +
                "in a Docker build stage that copies only compiled classes — " +
                "the method falls back to a NOTE block explaining that git " +
                "is unavailable, and the test still passes.");

        sayWarning("Shallow clones (`git clone --depth=N`) truncate commit history. " +
                "If your CI pipeline uses a shallow clone, `sayEvolutionTimeline` " +
                "will show fewer entries than exist in the full repository. " +
                "For accurate hotspot analysis, configure your CI checkout action " +
                "with `fetch-depth: 0` to retrieve the complete history.");

        say("Example GitHub Actions configuration for full history:");
        sayCode("""
                - uses: actions/checkout@v4
                  with:
                    fetch-depth: 0   # required for sayEvolutionTimeline
                """, "yaml");

        sayEnvProfile();
    }

    // =========================================================================
    // Private helpers
    // =========================================================================

    /**
     * Runs a git command via {@link ProcessBuilder}, applies {@code transform} to
     * the output lines, and returns the result. Returns {@code fallback} on any
     * {@link IOException} or non-zero exit code so tests never fail due to git
     * unavailability.
     *
     * @param command   the git command and arguments
     * @param transform maps the captured output lines to a String result
     * @param fallback  value returned when git is unavailable or exits non-zero
     * @return the transformed result or the fallback value
     */
    private String runGitCommand(
            List<String> command,
            java.util.function.Function<List<String>, String> transform,
            String fallback) {

        try {
            var pb = new ProcessBuilder(command).redirectErrorStream(true);
            var proc = pb.start();
            List<String> lines;
            try (var reader = new BufferedReader(
                    new InputStreamReader(proc.getInputStream()))) {
                lines = reader.lines().toList();
            }
            int exitCode = proc.waitFor();
            if (exitCode != 0) {
                return fallback;
            }
            return transform.apply(lines);
        } catch (IOException | InterruptedException e) {
            Thread.currentThread().interrupt();
            return fallback;
        }
    }
}
