/*
 * Copyright 2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.seanchatmangpt.dtr.test;

import io.github.seanchatmangpt.dtr.DtrTest;
import io.github.seanchatmangpt.dtr.javadoc.JavadocSelfLookup;
import io.github.seanchatmangpt.dtr.javadoc.JavadocSelfLookup.LookupResult;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.MethodOrderer;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Documentation test for the JavadocSelf feature.
 *
 * <p>Demonstrates how {@link JavadocSelfLookup} walks the JVM call stack to
 * identify the invoking method and optionally enriches output with Javadoc
 * text sourced from {@code docs/meta/javadoc.json}.</p>
 *
 * <p>Tests execute in alphabetical order to establish a clear narrative flow.</p>
 */
@TestMethodOrder(MethodOrderer.MethodName.class)
public class JavadocSelfDocTest extends DtrTest {

    // =========================================================================
    // Test methods
    // =========================================================================

    @Test
    public void t01_overview() {
        sayNextSection("Javadoc Self-Lookup — Overview");

        say("""
            `JavadocSelfLookup` uses `StackWalker` to inspect the JVM call stack at \
            the moment `sayJavadocSelf()` is invoked. It skips DTR's own internal frames \
            and surfaces the method that the test author actually wrote, together with its \
            class name and source-line number.
            """);

        say("""
            When `docs/meta/javadoc.json` is present (generated by the `dtr-javadoc` Rust \
            binary), the lookup also retrieves the Javadoc description text for that method. \
            If the file does not exist the feature degrades gracefully — caller info is \
            always available, Javadoc text defaults to an empty string.
            """);

        sayCode("""
            // Minimal usage inside a DtrTest subclass:
            public void myTest() {
                sayJavadocSelf();   // documents THIS method's caller info + Javadoc
            }
            """, "java");

        sayNote("""
            The frame offset is fixed: frame 0 is `lookup()`, frame 1 is \
            `RenderMachineImpl.sayJavadocSelf()`, and frame 2 is the test method itself.
            """);
    }

    @Test
    public void t02_stackWalkerDemo() {
        sayNextSection("StackWalker Demo");

        say("Calling `JavadocSelfLookup.lookup()` directly from this test method " +
            "returns caller metadata for `t02_stackWalkerDemo`.");

        var result = JavadocSelfLookup.lookup();

        var info = new LinkedHashMap<String, String>();
        info.put("Caller class",  result.callerClass());
        info.put("Caller method", result.callerMethod());
        info.put("Line number",   String.valueOf(result.lineNumber()));
        info.put("Javadoc text",  result.javadocText().isBlank() ? "(none)" : result.javadocText());
        sayKeyValue(info);

        assertNotNull(result.callerClass(),  "callerClass must not be null");
        assertFalse(result.callerClass().isBlank(),  "callerClass must not be empty");
        assertNotNull(result.callerMethod(), "callerMethod must not be null");
        assertFalse(result.callerMethod().isBlank(), "callerMethod must not be empty");

        sayAssertions(Map.of(
            "callerClass non-null and non-empty",  "✓ PASS",
            "callerMethod non-null and non-empty", "✓ PASS"
        ));
    }

    @Test
    public void t03_markdownOutput() {
        sayNextSection("Markdown Output from toMarkdown()");

        say("Calling `JavadocSelfLookup.toMarkdown(result)` returns Markdown lines " +
            "ready for direct injection into the document buffer.");

        var result = JavadocSelfLookup.lookup();
        List<String> lines = JavadocSelfLookup.toMarkdown(result);

        for (var line : lines) {
            sayRaw(line);
        }

        assertNotNull(lines, "toMarkdown result must not be null");
        assertFalse(lines.isEmpty(), "toMarkdown must return at least one line");
        assertTrue(lines.stream().anyMatch(l -> l.contains("Javadoc Self-Reference")),
            "Output must contain the section heading");

        sayAssertions(Map.of(
            "toMarkdown returns non-empty list",              "✓ PASS",
            "Output contains 'Javadoc Self-Reference' heading", "✓ PASS"
        ));
    }

    @Test
    public void t04_sayJavadocSelf() {
        sayNextSection("sayJavadocSelf() Integration");

        say("Invoking `sayJavadocSelf()` through the standard `DtrTest` API produces " +
            "the same call-site table that `lookup()` + `toMarkdown()` would produce, " +
            "but in a single, ergonomic call.");

        sayJavadocSelf();

        say("Javadoc self-lookup completed.");
    }

    @Test
    public void t05_recordStructure() {
        sayNextSection("LookupResult Record Structure");

        say("`LookupResult` is a Java 26 record with four components. " +
            "The schema is captured here via `sayRecordComponents()`.");

        sayRecordComponents(LookupResult.class);

        var components = LookupResult.class.getRecordComponents();
        assertNotNull(components, "record components array must not be null");
        assertTrue(components.length > 0, "LookupResult must have at least one record component");

        sayAssertions(Map.of(
            "LookupResult has record components", "✓ PASS"
        ));
    }

    // =========================================================================
    // Lifecycle
    // =========================================================================

    @AfterAll
    static void afterAll() {
        finishDocTest();
    }
}
