/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.seanchatmangpt.dtr.test;

import io.github.seanchatmangpt.dtr.DtrTest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * 80/20 Blue Ocean Innovation: OpenAPI REST API Documentation.
 *
 * <p>Demonstrates how DTR's {@code say*} methods produce living, executable
 * OpenAPI-style documentation for REST APIs. Each test method documents one
 * aspect of the API lifecycle — overview, endpoint schema, error catalogue,
 * authentication, and versioned evolution — entirely through real Java code
 * with no external REST libraries or mocked HTTP calls.</p>
 *
 * <p>All structural data (endpoint tables, error codes, JWT claims) is
 * defined inline so it can be read, validated, and extended by any future
 * test run. Documentation cannot drift from the schema because the schema
 * IS the documentation.</p>
 */
@TestMethodOrder(MethodOrderer.MethodName.class)
public class OpenApiDocTest extends DtrTest {

    @AfterAll
    static void afterAll() {
        finishDocTest();
    }

    // =========================================================================
    // Domain records — compile-checked schema anchors
    // =========================================================================

    /** Represents a User resource in the API. */
    record User(long id, String name, String email, String role) {}

    /** Represents a structured API error envelope. */
    record ApiError(int status, String code, String message, String path) {}

    /** Represents a JWT claim set (subset). */
    record JwtClaims(String sub, String iss, long exp, List<String> scopes) {}

    // =========================================================================
    // Tests
    // =========================================================================

    @Test
    void a1_overview() {
        sayNextSection("OpenAPI REST API Documentation with DTR");

        say(
            "DTR transforms JUnit 5 tests into living API documentation. " +
            "Each `say*` call is a typed documentation event captured by the " +
            "RenderMachine and written to Markdown, LaTeX, HTML, and JSON outputs. " +
            "REST API docs written this way can never drift from the code because " +
            "the documentation is generated by running the code."
        );

        say("The four standard HTTP methods covered in this guide:");

        sayTable(new String[][] {
            {"Method",   "Semantics",          "Safe", "Idempotent", "Typical Status Codes"},
            {"GET",      "Retrieve resource",  "Yes",  "Yes",        "200, 304, 404"},
            {"POST",     "Create resource",    "No",   "No",         "201, 400, 409, 422"},
            {"PUT",      "Replace resource",   "No",   "Yes",        "200, 204, 404, 422"},
            {"DELETE",   "Remove resource",    "No",   "Yes",        "204, 404"},
        });

        sayNote(
            "Safe methods do not modify server state. Idempotent methods produce " +
            "the same result regardless of how many times they are called with the same input."
        );

        say("Request/response lifecycle for a typical REST call:");

        sayMermaid("""
                sequenceDiagram
                    participant Client
                    participant Gateway as API Gateway
                    participant Auth   as Auth Service
                    participant API    as Resource API
                    participant DB     as Database

                    Client->>Gateway: HTTP Request + Bearer token
                    Gateway->>Auth: Validate JWT
                    Auth-->>Gateway: 200 OK (claims)
                    Gateway->>API: Forward request + claims
                    API->>DB: Query / mutation
                    DB-->>API: Result set
                    API-->>Gateway: 200 OK (JSON body)
                    Gateway-->>Client: Response + CORS headers
                """);

        sayWarning(
            "All endpoints require a valid JWT Bearer token in the " +
            "`Authorization` header. Requests without a token receive " +
            "HTTP 401 Unauthorized immediately at the gateway."
        );
    }

    @Test
    void a2_endpoint_schema() {
        sayNextSection("User API — Endpoint Schema");

        say(
            "The User resource exposes three endpoints. Each endpoint is fully " +
            "described by its HTTP method, path template, expected status code, " +
            "and a brief contract statement. The Java record `User` below is the " +
            "canonical schema — it is the single source of truth for field names " +
            "and types across request, response, and documentation."
        );

        sayRecordComponents(User.class);

        say("Endpoint catalogue:");

        sayTable(new String[][] {
            {"Method",   "Path",             "Success Status", "Description"},
            {"GET",      "/users/{id}",      "200 OK",         "Fetch a single user by numeric ID"},
            {"POST",     "/users",           "201 Created",    "Create a new user; returns Location header"},
            {"DELETE",   "/users/{id}",      "204 No Content", "Hard-delete a user; idempotent"},
        });

        say("GET /users/{id} — sample response body:");

        sayCode("""
                // Java record used as response model
                record User(long id, String name, String email, String role) {}

                // Serialised to JSON by the framework
                // GET /users/42 → 200 OK
                """, "java");

        // Build a representative User response and show it as JSON
        var exampleUser = new User(42L, "Alice Nguyen", "alice@example.com", "ADMIN");
        sayJson(exampleUser);

        say("POST /users — request body and 201 response:");

        sayCode("""
                // POST /users
                // Content-Type: application/json
                {
                  "name":  "Bob Tanaka",
                  "email": "bob@example.com",
                  "role":  "VIEWER"
                }

                // 201 Created
                // Location: /users/43
                // Content-Type: application/json
                {
                  "id":    43,
                  "name":  "Bob Tanaka",
                  "email": "bob@example.com",
                  "role":  "VIEWER"
                }
                """, "json");

        say("DELETE /users/{id} — no response body on success:");

        sayCode("""
                // DELETE /users/43
                // Authorization: Bearer <token>

                // 204 No Content
                // (empty body)

                // Second call to same ID is also 204 — idempotent contract.
                """, "http");

        sayNote(
            "The `id` field is server-assigned and must not be included in POST " +
            "request bodies. Including it returns HTTP 422 Unprocessable Entity."
        );
    }

    @Test
    void a3_error_catalogue() {
        sayNextSection("Standard HTTP Error Catalogue");

        say(
            "Every error response from the User API is wrapped in a uniform " +
            "`ApiError` envelope. Consumers can always rely on this structure " +
            "regardless of which endpoint produced the error."
        );

        sayRecordComponents(ApiError.class);

        say("Sample error response body:");

        var sampleError = new ApiError(
            404,
            "USER_NOT_FOUND",
            "No user exists with id=99",
            "/users/99"
        );
        sayJson(sampleError);

        say("Complete 4xx error taxonomy for the User API:");

        sayTable(new String[][] {
            {"HTTP Status",           "Error Code",             "Trigger Condition",                          "Retryable"},
            {"400 Bad Request",       "INVALID_REQUEST",        "Malformed JSON or missing required fields",  "No"},
            {"401 Unauthorized",      "MISSING_TOKEN",          "Authorization header absent or malformed",   "No"},
            {"403 Forbidden",         "INSUFFICIENT_SCOPE",     "Token valid but scope does not allow action","No"},
            {"404 Not Found",         "USER_NOT_FOUND",         "No user with the supplied id exists",        "No"},
            {"409 Conflict",          "EMAIL_ALREADY_EXISTS",   "POST with an email already registered",      "No"},
            {"422 Unprocessable",     "VALIDATION_FAILED",      "Field constraints violated (e.g. bad email)","No"},
            {"429 Too Many Requests", "RATE_LIMIT_EXCEEDED",    "Client exceeded 100 req/min quota",          "Yes"},
        });

        sayWarning(
            "HTTP 429 responses include a `Retry-After` header (seconds). " +
            "Clients must honour this header and back off before retrying. " +
            "Ignoring `Retry-After` will result in a temporary IP-level ban."
        );

        say("5xx server error taxonomy:");

        sayTable(new String[][] {
            {"HTTP Status",              "Error Code",          "Trigger Condition",                        "Retryable"},
            {"500 Internal Server Error","INTERNAL_ERROR",      "Unhandled exception — check server logs",  "No"},
            {"502 Bad Gateway",          "UPSTREAM_FAILURE",    "Database or downstream service unreachable","Yes"},
            {"503 Service Unavailable",  "MAINTENANCE_MODE",    "Planned maintenance window active",         "Yes"},
            {"504 Gateway Timeout",      "UPSTREAM_TIMEOUT",    "Upstream did not respond within 10 s",      "Yes"},
        });

        sayWarning(
            "5xx errors indicate a server-side fault. Clients should apply " +
            "exponential backoff with jitter starting at 1 s, doubling up to a " +
            "ceiling of 32 s, for a maximum of 5 retries before surfacing the " +
            "error to the end user."
        );

        say("Java pattern for handling the ApiError envelope:");

        sayCode("""
                // Sealed result type — maps status code to typed outcome
                sealed interface ApiResult<T> permits ApiResult.Ok, ApiResult.Err {}

                record Ok<T>(T body) implements ApiResult<T> {}
                record Err<T>(ApiError error) implements ApiResult<T> {}

                // Pattern matching on the result (Java 21+)
                switch (parseResult(responseBody)) {
                    case Ok(var user)   -> display(user);
                    case Err(var error) -> switch (error.status()) {
                        case 401 -> redirectToLogin();
                        case 429 -> scheduleRetry(retryAfterSeconds);
                        default  -> showErrorBanner(error.message());
                    };
                }
                """, "java");
    }

    @Test
    void a4_authentication() {
        sayNextSection("JWT Bearer Token Authentication");

        say(
            "The User API uses stateless JWT (JSON Web Token) authentication. " +
            "Tokens are issued by the Auth Service, signed with RS256, and " +
            "validated at the API Gateway on every request. No session state is " +
            "stored server-side — horizontal scaling is unrestricted."
        );

        say("Token acquisition and usage flow:");

        sayMermaid("""
                sequenceDiagram
                    participant User    as User / Client App
                    participant Auth    as Auth Service (POST /token)
                    participant Gateway as API Gateway
                    participant API     as Resource API

                    User->>Auth: POST /token {client_id, client_secret}
                    Auth-->>User: 200 OK {access_token, expires_in: 3600}

                    Note over User: Store token in memory only.<br/>Never persist to disk or localStorage.

                    User->>Gateway: GET /users/42<br/>Authorization: Bearer <access_token>
                    Gateway->>Gateway: Verify RS256 signature + exp claim
                    Gateway->>API: Forward + inject claims header
                    API-->>User: 200 OK {id:42, name:"Alice Nguyen", ...}

                    Note over User,Gateway: Token expires after 3600 s.<br/>Re-authenticate via POST /token.
                """);

        say("JWT claim set — the `JwtClaims` record defines the required fields:");

        sayRecordComponents(JwtClaims.class);

        say("Example decoded JWT payload:");

        var claims = new JwtClaims(
            "user:42",
            "https://auth.example.com",
            System.currentTimeMillis() / 1000L + 3600L,
            List.of("users:read", "users:write", "users:delete")
        );
        sayJson(claims);

        say("Scope-to-endpoint mapping:");

        sayTable(new String[][] {
            {"Required Scope",    "Permitted Endpoints"},
            {"users:read",        "GET /users/{id}"},
            {"users:write",       "POST /users, PUT /users/{id}"},
            {"users:delete",      "DELETE /users/{id}"},
        });

        say("Java utility for extracting scopes from the claims header injected by the gateway:");

        sayCode("""
                /**
                 * Extracts the scope list injected by the gateway as an
                 * X-Jwt-Claims header value (URL-encoded JSON).
                 */
                static List<String> scopesFrom(HttpRequest request) {
                    return request.headers()
                        .firstValue("X-Jwt-Claims")
                        .map(raw -> URLDecoder.decode(raw, UTF_8))
                        .map(json -> MAPPER.readValue(json, JwtClaims.class).scopes())
                        .orElse(List.of());
                }

                // Guard in a request handler:
                if (!scopesFrom(request).contains("users:write")) {
                    throw new ForbiddenException("INSUFFICIENT_SCOPE");
                }
                """, "java");

        sayWarning(
            "Tokens must not be logged, stored in cookies without `HttpOnly` + `Secure` " +
            "flags, or transmitted over plain HTTP. All API Gateway endpoints enforce " +
            "TLS 1.2+ and reject plain HTTP connections with HTTP 301."
        );

        sayNote(
            "Token refresh is not supported. When a token expires the client must " +
            "re-authenticate with `POST /token`. Tokens cannot be revoked individually; " +
            "compromise of a token requires rotating the signing key pair."
        );
    }

    @Test
    void a5_api_evolution() {
        sayNextSection("API Versioning and Evolution Timeline");

        say(
            "The User API follows a calendar-versioned, header-based versioning " +
            "strategy. The requested API version is supplied in the " +
            "`Accept-Version` request header. When the header is absent the " +
            "gateway routes to the latest stable version. Deprecated versions " +
            "are supported for a minimum of six months after the sunset date."
        );

        sayNote(
            "DTR itself uses calendar versioning (YYYY.MINOR.PATCH). " +
            "API versions below follow the same convention — the year prefix " +
            "communicates when the version was introduced, not a compatibility " +
            "guarantee level."
        );

        say("Version history with breaking-change annotations:");

        sayTable(new String[][] {
            {"Version",    "Release Date", "Status",     "Breaking Change",                         "Migration"},
            {"2026.1.0",   "2026-01-10",   "Current",    "None — initial stable release",            "N/A"},
            {"2026.2.0",   "2026-03-01",   "Current",    "Added `role` field to User response",      "Old clients ignore unknown fields"},
            {"2026.3.0",   "2026-06-01",   "Planned",    "DELETE returns 200 + body (was 204)",      "Update null-body handling"},
            {"2025.1.0",   "2025-07-15",   "Deprecated", "Removed `username` field (replaced email)","Replace username with email"},
            {"2024.1.0",   "2024-01-20",   "Sunset",     "No pagination on GET /users",              "Migrate to cursor pagination"},
        });

        say("Version negotiation — request and response headers:");

        sayCode("""
                // Request: pin to a specific version
                GET /users/42 HTTP/1.1
                Accept-Version: 2026.2.0
                Authorization: Bearer <token>

                // Response: echoes the resolved version
                HTTP/1.1 200 OK
                Content-Version: 2026.2.0
                Deprecation: false
                Content-Type: application/json
                """, "http");

        say("Deprecated version response — gateway injects advisory headers:");

        sayCode("""
                // Request to a deprecated version
                GET /users/42 HTTP/1.1
                Accept-Version: 2025.1.0
                Authorization: Bearer <token>

                // Response includes sunset and migration hints
                HTTP/1.1 200 OK
                Content-Version: 2025.1.0
                Deprecation: true
                Sunset: Sun, 01 Jun 2026 00:00:00 GMT
                Link: <https://api.example.com/docs/migration/2026.1.0>; rel="successor-version"
                """, "http");

        say("Migration metadata for the 2026.3.0 planned breaking change:");

        // LinkedHashMap preserves insertion order for deterministic table output
        var migrationMeta = new LinkedHashMap<String, String>();
        migrationMeta.put("Version",         "2026.3.0");
        migrationMeta.put("Breaking Change", "DELETE /users/{id} returns 200 + ApiResult body instead of 204 No Content");
        migrationMeta.put("Migration",       "Replace null-body check with JSON body parse on DELETE response");
        migrationMeta.put("Affected Clients","Any client that asserts status == 204 or reads a null body on DELETE");
        migrationMeta.put("Sunset Date",     "2026-12-01 (six months after 2026.3.0 GA)");
        migrationMeta.put("Contact",         "api-team@example.com");
        sayKeyValue(migrationMeta);

        say("Java version negotiation utility for client code:");

        sayCode("""
                /**
                 * Builds a request with the requested API version pinned.
                 * Callers should catch UnsupportedVersionException and
                 * fall back to the current stable version.
                 */
                static HttpRequest versionedRequest(URI endpoint, String version) {
                    return HttpRequest.newBuilder(endpoint)
                        .header("Accept-Version", version)
                        .header("Authorization", "Bearer " + tokenStore.get())
                        .GET()
                        .build();
                }

                // Usage: pin to specific version
                var req = versionedRequest(
                    URI.create("https://api.example.com/users/42"),
                    "2026.2.0"
                );
                var response = HttpClient.newHttpClient().send(req, ofString());

                // Check for deprecation advisory
                response.headers()
                    .firstValue("Deprecation")
                    .filter("true"::equalsIgnoreCase)
                    .ifPresent(d -> log.warn("API version deprecated — plan migration"));
                """, "java");

        sayWarning(
            "Sunset versions return HTTP 410 Gone after the sunset date. " +
            "Clients pinned to a sunset version will receive 410 on every request " +
            "with no response body. Update `Accept-Version` before the sunset date."
        );

        sayUnorderedList(List.of(
            "Subscribe to the API changelog RSS feed to receive advance notice of breaking changes",
            "Run contract tests against each new version before updating `Accept-Version` in production",
            "Never rely on a version marked `Deprecated` for new feature development",
            "Contact api-team@example.com for migration assistance or an extended deprecation window"
        ));
    }
}
