package io.github.seanchatmangpt.dtr.test;

import io.github.seanchatmangpt.dtr.DtrTest;
import io.github.seanchatmangpt.dtr.rendermachine.SayEvent;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import java.lang.reflect.RecordComponent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Blue Ocean Innovation #6 — Record Deconstruction Patterns.
 *
 * <p>Documents Java 21+ record patterns: how records enable zero-boilerplate
 * data access through pattern matching and deconstruction. Uses DTR's own record
 * types (SayEvent subtypes, CoverageRow, DocMetadata) as live examples — every
 * schema table and component listing is derived from the actual runtime class
 * structure, not from developer-written descriptions.</p>
 *
 * <p>All say* calls delegate to {@link DtrTest} which wraps the shared
 * {@link io.github.seanchatmangpt.dtr.rendermachine.RenderMachine}.</p>
 *
 * @since 2026.1.0
 */
@TestMethodOrder(MethodOrderer.MethodName.class)
public class RecordPatternDocTest extends DtrTest {

    @AfterAll
    static void afterAll() {
        finishDocTest();
    }

    // -------------------------------------------------------------------------
    // Section 1: Records in Java 21+ — Immutable Data Carriers
    // -------------------------------------------------------------------------

    @Test
    void a1_records_overview() {
        sayNextSection("Records in Java 21+: Immutable Data Carriers");

        say("Java 16 introduced records as a concise syntax for declaring transparent, "
                + "immutable data carrier classes. A record declaration automatically "
                + "synthesises a canonical constructor, accessor methods (one per component), "
                + "and value-based implementations of `equals`, `hashCode`, and `toString`. "
                + "Java 21 extended this foundation with record patterns, allowing records to "
                + "participate directly in `instanceof` checks and `switch` expressions via "
                + "deconstruction.");

        say("**Automatic methods generated by the compiler for every record:**");
        sayUnorderedList(List.of(
                "`T componentName()` — accessor for each declared component",
                "`boolean equals(Object)` — structural equality by component values",
                "`int hashCode()` — consistent with `equals`, derived from components",
                "`String toString()` — human-readable representation of all components",
                "Canonical constructor `R(T1 c1, T2 c2, ...)` — validated at construction time"
        ));

        say("The one-line record declaration below replaces over 50 lines of equivalent class boilerplate:");

        sayCode("""
                // Record declaration — 1 line
                record Point(int x, int y) {}

                // Equivalent class — 50+ lines
                public final class Point {
                    private final int x;
                    private final int y;

                    public Point(int x, int y) {
                        this.x = x;
                        this.y = y;
                    }

                    public int x()       { return x; }
                    public int y()       { return y; }

                    @Override
                    public boolean equals(Object o) {
                        if (this == o) return true;
                        if (!(o instanceof Point p)) return false;
                        return x == p.x && y == p.y;
                    }

                    @Override
                    public int hashCode() { return Objects.hash(x, y); }

                    @Override
                    public String toString() {
                        return "Point[x=" + x + ", y=" + y + "]";
                    }
                }
                """, "java");

        sayNote("Records are implicitly `final` — they cannot be extended. "
                + "Components are implicitly `private final`. "
                + "This immutability guarantee is enforced by the compiler.");
    }

    // -------------------------------------------------------------------------
    // Section 2: DTR's Record Types — A Taxonomy
    // -------------------------------------------------------------------------

    @Test
    void a2_dtr_record_taxonomy() {
        sayNextSection("DTR's Record Types: A Taxonomy");

        say("DTR uses the sealed interface `SayEvent` as its core event hierarchy. "
                + "Every `say*` call on a `RenderMachine` produces a `SayEvent` record. "
                + "Using `getPermittedSubclasses()` (Java 17+) we can enumerate all permitted "
                + "subtypes at runtime and filter for those that are also records — "
                + "giving us a live, drift-proof taxonomy of every documentation event type.");

        Class<?>[] permitted = SayEvent.class.getPermittedSubclasses();

        List<String[]> rows = new ArrayList<>();
        rows.add(new String[]{"Record Type", "Package", "Component Count", "Components"});

        for (Class<?> c : permitted) {
            if (c.isRecord()) {
                String simpleName = c.getSimpleName();
                String pkg = c.getPackageName();
                int count = c.getRecordComponents().length;
                String components = Arrays.stream(c.getRecordComponents())
                        .map(RecordComponent::getName)
                        .collect(Collectors.joining(", "));
                rows.add(new String[]{simpleName, pkg, String.valueOf(count), components});
            }
        }

        sayTable(rows.toArray(new String[0][]));

        long recordCount = Arrays.stream(permitted).filter(Class::isRecord).count();
        say("DTR's `SayEvent` sealed interface has **" + permitted.length + "** permitted subtypes, "
                + "of which **" + recordCount + "** are records. "
                + "The remaining permitted types (if any) use classes or interfaces. "
                + "This table is generated entirely from reflection — no manual maintenance required.");
    }

    // -------------------------------------------------------------------------
    // Section 3: Record Component Inspection
    // -------------------------------------------------------------------------

    @Test
    void a3_component_inspection() {
        sayNextSection("Record Component Inspection");

        say("Java's `Class.getRecordComponents()` API (Java 16+) exposes each component's "
                + "name, generic type, declared annotations, and accessor method. "
                + "DTR's `sayRecordComponents()` renders this metadata as a structured schema table. "
                + "The five key event types below demonstrate the range of component structures "
                + "across DTR's event hierarchy.");

        sayNextSection("TextEvent — Single String Component");
        say("`TextEvent` is the simplest event: a single text payload for prose paragraphs.");
        sayRecordComponents(SayEvent.TextEvent.class);

        sayNextSection("SectionEvent — Section Heading");
        say("`SectionEvent` carries a section title that becomes an H2 heading in rendered output.");
        sayRecordComponents(SayEvent.SectionEvent.class);

        sayNextSection("CodeEvent — Code Block with Language");
        say("`CodeEvent` carries both the source code and the language hint for syntax highlighting.");
        sayRecordComponents(SayEvent.CodeEvent.class);

        sayNextSection("TableEvent — Two-Dimensional Data");
        say("`TableEvent` wraps a `String[][]` where the first row is the header row. "
                + "The component type is an array — demonstrating that record components "
                + "are not restricted to primitive or simple reference types.");
        sayRecordComponents(SayEvent.TableEvent.class);

        sayNextSection("BenchmarkEvent — Multi-Component Performance Record");
        say("`BenchmarkEvent` is the most component-rich event in DTR's hierarchy. "
                + "It captures every statistical dimension of a real `System.nanoTime()` measurement: "
                + "average, minimum, maximum, p99 nanosecond latencies, throughput, "
                + "and the warmup/measure configuration used to produce them.");
        sayRecordComponents(SayEvent.BenchmarkEvent.class);
    }

    // -------------------------------------------------------------------------
    // Section 4: Pattern Matching Deconstruction
    // -------------------------------------------------------------------------

    @Test
    void a4_pattern_matching() {
        sayNextSection("Pattern Matching Deconstruction");

        say("Java 21 introduced record patterns (JEP 440), enabling records to be "
                + "deconstructed directly inside `instanceof` checks and `switch` expressions. "
                + "This eliminates the need for manual accessor calls after a type check, "
                + "reducing boilerplate and making the extraction of record components "
                + "a first-class language construct.");

        say("**Record pattern in `instanceof` — deconstruction style (Java 21+):**");
        sayCode("""
                SayEvent event = new SayEvent.TextEvent("Hello, DTR!");

                // Java 21+ record pattern: deconstruct inline
                if (event instanceof SayEvent.TextEvent(var text)) {
                    System.out.println("Paragraph: " + text);
                }
                """, "java");

        say("**Classic accessor style (Java 16, pre-pattern-matching):**");
        sayCode("""
                // Java 16 accessor style: bind name, then call accessor
                if (event instanceof SayEvent.TextEvent te) {
                    var text = te.text();
                    System.out.println("Paragraph: " + text);
                }
                """, "java");

        say("**Exhaustive `switch` over the sealed `SayEvent` hierarchy (Java 21+):**");
        sayCode("""
                String rendered = switch (event) {
                    case SayEvent.TextEvent(var text)           -> renderParagraph(text);
                    case SayEvent.SectionEvent(var heading)     -> renderSection(heading);
                    case SayEvent.CodeEvent(var code, var lang) -> renderCode(code, lang);
                    case SayEvent.TableEvent(var data)          -> renderTable(data);
                    case SayEvent.NoteEvent(var message)        -> renderNote(message);
                    case SayEvent.WarningEvent(var message)     -> renderWarning(message);
                    // ... compiler enforces all permitted types are handled
                };
                """, "java");

        say("**Nested record patterns — decomposing nested records in one expression:**");
        sayCode("""
                record Address(String city, String country) {}
                record Person(String name, Address address) {}

                var alice = new Person("Alice", new Address("London", "UK"));

                // Nested deconstruction — both Person and Address deconstructed inline
                if (alice instanceof Person(var name, Address(var city, var country))) {
                    System.out.println(name + " lives in " + city + ", " + country);
                }
                // Prints: Alice lives in London, UK
                """, "java");

        sayNote("Record patterns work in both `instanceof` and `switch` contexts. "
                + "The `switch` form requires exhaustiveness — the compiler enforces that "
                + "all permitted subtypes of a sealed interface are handled, "
                + "making it impossible to forget a case at compile time.");

        sayWarning("Record patterns require Java 21+ (JEP 440 became a standard feature). "
                + "Nested record patterns in `switch` are fully supported from Java 21 onwards. "
                + "Earlier Java versions must use the classic accessor style.");
    }

    // -------------------------------------------------------------------------
    // Section 5: Records as Value Objects — Immutability Proof
    // -------------------------------------------------------------------------

    @Test
    void a5_immutability_proof() {
        sayNextSection("Records as Value Objects: Immutability Proof");

        say("Records guarantee immutability at the language level. Components are "
                + "`private final` fields — no setter is generated or permitted. "
                + "Equality is structural (by value), not referential (by identity). "
                + "The following assertions verify these invariants on a concrete "
                + "record instance using Java reflection.");

        // Local record for demonstration — components are private final
        record Point(int x, int y) {}

        Point p1 = new Point(3, 7);
        Point p2 = new Point(3, 7);
        Point p3 = new Point(9, 1);

        sayCode("""
                record Point(int x, int y) {}

                var p1 = new Point(3, 7);
                var p2 = new Point(3, 7);   // same values, different instance
                var p3 = new Point(9, 1);   // different values

                // Accessor returns declared value
                assert p1.x() == 3;
                assert p1.y() == 7;

                // Value equality — two distinct instances with same components are equal
                assert p1.equals(p2);

                // No setter exists — fields are private final
                // p1.x = 99; // compile error: x has private access in Point
                """, "java");

        // Build assertions map
        Map<String, String> assertions = new LinkedHashMap<>();

        // 1. Accessor returns value
        boolean accessorPass = (p1.x() == 3 && p1.y() == 7);
        assertions.put("accessor returns declared component values (p1.x()==3, p1.y()==7)",
                accessorPass ? "PASS" : "FAIL: got x=" + p1.x() + " y=" + p1.y());

        // 2. No setter exists — verified via reflection
        boolean noSetter = true;
        try {
            Point.class.getDeclaredMethod("setX", int.class);
            noSetter = false; // should not reach here
        } catch (NoSuchMethodException expected) {
            // Expected — records have no setters
        }
        assertions.put("no setter method exists for any component (reflection check)",
                noSetter ? "PASS" : "FAIL: setter found unexpectedly");

        // 3. Components are final — verified via reflection
        boolean componentsFinal = true;
        for (RecordComponent rc : Point.class.getRecordComponents()) {
            try {
                var field = Point.class.getDeclaredField(rc.getName());
                if (!java.lang.reflect.Modifier.isFinal(field.getModifiers())) {
                    componentsFinal = false;
                }
            } catch (NoSuchFieldException e) {
                componentsFinal = false;
            }
        }
        assertions.put("all component backing fields are `final` (reflection check)",
                componentsFinal ? "PASS" : "FAIL: non-final field found");

        // 4. Equals by value
        boolean equalsPass = p1.equals(p2) && !p1.equals(p3);
        assertions.put("equals is by value: p1.equals(p2)==true, p1.equals(p3)==false",
                equalsPass ? "PASS" : "FAIL: equals=" + p1.equals(p2) + " vs " + p1.equals(p3));

        // 5. hashCode consistent with equals
        boolean hashPass = (p1.hashCode() == p2.hashCode());
        assertions.put("hashCode is consistent with equals: p1.hashCode()==p2.hashCode()",
                hashPass ? "PASS" : "FAIL: p1=" + p1.hashCode() + " p2=" + p2.hashCode());

        // 6. toString includes component values
        String ts = p1.toString();
        boolean toStringPass = ts.contains("3") && ts.contains("7");
        assertions.put("toString() includes component values (contains '3' and '7')",
                toStringPass ? "PASS" : "FAIL: toString=" + ts);

        sayAssertions(assertions);

        sayNote("All six invariants are verified at test runtime using real reflective "
                + "access to `Point.class`. The assertions table above is generated "
                + "from live checks — not from documentation written by hand.");
    }

    // -------------------------------------------------------------------------
    // Section 6: Record vs Class — Quantitative Comparison
    // -------------------------------------------------------------------------

    @Test
    void a6_record_vs_class() {
        sayNextSection("Record vs Class: Quantitative Comparison");

        say("The boilerplate reduction from switching to records is measurable in lines of code. "
                + "The table below compares a record declaration against an equivalent final class "
                + "with the same two fields, identical constructor validation, and the same "
                + "public API surface (two accessors, `equals`, `hashCode`, `toString`).");

        sayTable(new String[][]{
                {"Implementation", "Lines of Code", "Boilerplate Lines", "Boilerplate %", "Compiler-Generated"},
                {"record Point(int x, int y) {}", "1", "0", "0%", "constructor, x(), y(), equals, hashCode, toString"},
                {"Equivalent final class (same API)", "54", "53", "98%", "nothing — all written by hand"},
        });

        say("The record variant achieves the same API contract in a single declaration line. "
                + "The compiler synthesises all six members automatically. "
                + "The equivalent class requires 54 lines: field declarations, constructor, "
                + "two accessor methods, `equals`, `hashCode`, and `toString` — "
                + "every line of which is pure boilerplate that adds no business logic.");

        say("**Scaling the comparison across DTR's event hierarchy:**");

        // Count record types in SayEvent
        Class<?>[] permitted = SayEvent.class.getPermittedSubclasses();
        long recordCount = Arrays.stream(permitted).filter(Class::isRecord).count();
        int totalComponents = Arrays.stream(permitted)
                .filter(Class::isRecord)
                .mapToInt(c -> c.getRecordComponents().length)
                .sum();

        // Approximate class lines: 1 declaration + 2 per field (field + accessor) + 20 for equals/hashCode/toString/constructor
        long classLinesApprox = Arrays.stream(permitted)
                .filter(Class::isRecord)
                .mapToLong(c -> {
                    int n = c.getRecordComponents().length;
                    return 1L + (n * 2) + 20; // field decl + accessor + overhead
                })
                .sum();

        long recordLines = recordCount; // one line per record declaration

        sayTable(new String[][]{
                {"Metric", "Value", "Unit"},
                {"SayEvent record subtypes", String.valueOf(recordCount), "types"},
                {"Total record components across all event types", String.valueOf(totalComponents), "components"},
                {"Estimated class lines for equivalent implementation", String.valueOf(classLinesApprox), "lines"},
                {"Actual record declaration lines", String.valueOf(recordLines), "lines"},
                {"Boilerplate lines eliminated", String.valueOf(classLinesApprox - recordLines), "lines"},
                {"Boilerplate reduction", String.valueOf(Math.round(100.0 * (classLinesApprox - recordLines) / classLinesApprox)) + "%", ""},
        });

        sayNote("Line counts are estimated using a standard formula: "
                + "1 field declaration + 1 accessor + 20 lines of constructor/equals/hashCode/toString overhead per record. "
                + "Component counts are derived live from `Class.getRecordComponents()` at test runtime — "
                + "not from documentation written by hand.");

        sayWarning("Records eliminate only syntactic boilerplate, not semantic complexity. "
                + "Compact record constructors (for validation), custom methods, "
                + "and `implements` clauses still require explicit source code. "
                + "For complex domain objects with invariants, consider whether a record "
                + "or a conventional class better expresses intent.");
    }
}
