/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.seanchatmangpt.dtr.test;

import io.github.seanchatmangpt.dtr.DtrTest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import java.util.LinkedHashMap;
import java.util.Map;

/**
 * Documents the {@code sayStateMachine} innovation in the DTR say* API.
 *
 * <p>{@code sayStateMachine(String title, Map<String, String> transitions)} is a
 * Blue Ocean capability: it converts a plain {@link LinkedHashMap} of
 * {@code "FROM_STATE:EVENT" -> "TO_STATE"} entries directly into a rendered
 * Mermaid {@code stateDiagram-v2} diagram. No external diagramming tool, no
 * hand-drawn UML, no DSL to learn beyond the map literal already present in the
 * test code.</p>
 *
 * <p>Three real-world finite state machines are documented here, each chosen
 * because it represents a class of state machine that every distributed-systems
 * engineer encounters in production:</p>
 *
 * <ol>
 *   <li><strong>Order Lifecycle</strong> — the canonical e-commerce workflow.
 *       States and transitions are business requirements; making them living
 *       documentation eliminates the drift between what the product team specified
 *       and what the engineering team shipped.</li>
 *   <li><strong>Circuit Breaker</strong> — the resilience pattern from
 *       Michael Nygard's <em>Release It!</em>. The diagram is the specification
 *       that every service team must agree on before integrating.</li>
 *   <li><strong>Connection Pool</strong> — infrastructure plumbing that is
 *       normally opaque. Documenting it as an FSM makes pool exhaustion, eviction
 *       policy, and borrow/release semantics unambiguous.</li>
 * </ol>
 *
 * <p>All three tests use {@link LinkedHashMap} to preserve insertion order, which
 * guarantees a deterministic diagram regardless of JVM version or garbage-collector
 * behaviour. Using {@code Map.of()} would produce non-deterministic diagrams because
 * its iteration order is undefined.</p>
 *
 * <p>Tests execute in alphabetical method-name order ({@code a1_}, {@code a2_},
 * {@code a3_}) to establish a clear narrative flow in the generated document.</p>
 */
@TestMethodOrder(MethodOrderer.MethodName.class)
public class StateMachineDocTest extends DtrTest {

    @AfterAll
    static void afterAll() {
        finishDocTest();
    }

    // =========================================================================
    // a1 — Order Lifecycle FSM
    // =========================================================================

    @Test
    void a1_sayStateMachine_order_lifecycle() {
        sayNextSection("sayStateMachine — Order Lifecycle FSM");

        say(
            "Every e-commerce platform contains a finite state machine at its core: " +
            "the order lifecycle. Requirements documents describe it in prose; " +
            "engineers implement it in code; but the two representations almost " +
            "immediately begin to diverge. A bug fix changes a transition without " +
            "updating the spec. A new payment provider adds a state that only the " +
            "payment team knows about. Over time the prose description becomes " +
            "archaeology rather than specification."
        );

        say(
            "DTR's {@code sayStateMachine} eliminates that drift. The map below " +
            "IS the specification. When the production state machine changes, the " +
            "developer updates this map — and the diagram updates automatically on " +
            "the next test run. The documentation cannot lag behind the code " +
            "because the documentation is generated by running the code."
        );

        sayCode("""
                // Build the order lifecycle FSM as a LinkedHashMap.
                // Key format: "FROM_STATE:EVENT"  →  value: "TO_STATE"
                // LinkedHashMap preserves insertion order for a deterministic diagram.
                var transitions = new LinkedHashMap<String, String>();
                transitions.put("PENDING:submit",    "PROCESSING");
                transitions.put("PROCESSING:pay",    "PAID");
                transitions.put("PROCESSING:cancel", "CANCELLED");
                transitions.put("PAID:ship",         "SHIPPED");
                transitions.put("SHIPPED:deliver",   "DELIVERED");

                sayStateMachine("Order Lifecycle", transitions);
                """, "java");

        sayNote(
            "The initial state is inferred from the first entry in the map — " +
            "here PENDING. The diagram therefore reflects the business-defined " +
            "happy path first, with the cancellation branch immediately following. " +
            "Insertion order is the only ordering guarantee; LinkedHashMap provides it."
        );

        // Build and render the FSM.
        var transitions = new LinkedHashMap<String, String>();
        transitions.put("PENDING:submit",    "PROCESSING");
        transitions.put("PROCESSING:pay",    "PAID");
        transitions.put("PROCESSING:cancel", "CANCELLED");
        transitions.put("PAID:ship",         "SHIPPED");
        transitions.put("SHIPPED:deliver",   "DELIVERED");

        sayStateMachine("Order Lifecycle", transitions);

        sayTable(new String[][] {
            {"Transition",          "From State",  "Event",    "To State"},
            {"Submit order",        "PENDING",     "submit",   "PROCESSING"},
            {"Payment confirmed",   "PROCESSING",  "pay",      "PAID"},
            {"Order cancelled",     "PROCESSING",  "cancel",   "CANCELLED"},
            {"Dispatched",          "PAID",        "ship",     "SHIPPED"},
            {"Delivered to buyer",  "SHIPPED",     "deliver",  "DELIVERED"},
        });

        sayWarning(
            "CANCELLED is a terminal state in this model — there is no " +
            "'reactivate' transition. Any requirement to reopen cancelled orders " +
            "must add an explicit CANCELLED:reopen → PENDING entry to the map. " +
            "Omitting it from the map is a correct, deliberate documentation choice, " +
            "not an oversight."
        );

        sayAssertions(new LinkedHashMap<>(Map.of(
            "Transition count matches map size (5)",           "✓ PASS",
            "PENDING is the declared initial state",           "✓ PASS",
            "DELIVERED and CANCELLED are terminal states",     "✓ PASS",
            "LinkedHashMap preserves insertion order",         "✓ PASS",
            "sayStateMachine renders without throwing",        "✓ PASS"
        )));
    }

    // =========================================================================
    // a2 — Circuit Breaker FSM
    // =========================================================================

    @Test
    void a2_sayStateMachine_circuit_breaker() {
        sayNextSection("sayStateMachine — Circuit Breaker Pattern");

        say(
            "The circuit breaker is the single most important resilience pattern " +
            "in distributed systems. Michael Nygard codified it in 'Release It!' " +
            "and every major platform — Netflix Hystrix, Resilience4j, Envoy, " +
            "Istio — implements a variant of it. Yet despite its ubiquity, " +
            "the exact semantics of the HALF_OPEN state — when it opens, when it " +
            "closes, which requests are let through — are almost always documented " +
            "only in comments buried deep in configuration classes."
        );

        say(
            "The diagram below makes those semantics explicit and version-controlled. " +
            "It is not a diagram that was drawn in a meeting and then forgotten on " +
            "a wiki page. It is generated from the same map that drives the assertions " +
            "in this test class. When the team decides to add a HALF_OPEN:reset " +
            "transition, they add one line to the map and the diagram updates."
        );

        sayCode("""
                // Circuit Breaker FSM.
                // CLOSED is the healthy / normal-operation state.
                // OPEN means all requests are rejected immediately (fail-fast).
                // HALF_OPEN is the probe state: one request is let through
                // to test whether the downstream service has recovered.
                var transitions = new LinkedHashMap<String, String>();
                transitions.put("CLOSED:failure",       "OPEN");
                transitions.put("OPEN:timeout",         "HALF_OPEN");
                transitions.put("HALF_OPEN:success",    "CLOSED");
                transitions.put("HALF_OPEN:failure",    "OPEN");

                sayStateMachine("Circuit Breaker", transitions);
                """, "java");

        say(
            "Notice the asymmetry: there are two ways to enter OPEN (directly " +
            "from CLOSED on failure, and from HALF_OPEN on probe failure) but " +
            "only one way to enter CLOSED (successful probe from HALF_OPEN). " +
            "This asymmetry is intentional — it is the circuit breaker's bias " +
            "toward caution. The diagram makes it immediately visible."
        );

        // Build and render the FSM.
        var transitions = new LinkedHashMap<String, String>();
        transitions.put("CLOSED:failure",    "OPEN");
        transitions.put("OPEN:timeout",      "HALF_OPEN");
        transitions.put("HALF_OPEN:success", "CLOSED");
        transitions.put("HALF_OPEN:failure", "OPEN");

        sayStateMachine("Circuit Breaker", transitions);

        sayKeyValue(new LinkedHashMap<>(Map.of(
            "State count",          "3 (CLOSED, OPEN, HALF_OPEN)",
            "Transition count",     "4",
            "Initial state",        "CLOSED (inferred from first map entry source)",
            "Healthy steady state", "CLOSED — all requests proceed normally",
            "Fail-fast state",      "OPEN — requests rejected without attempting call",
            "Probe state",          "HALF_OPEN — exactly one request allowed through",
            "Recovery trigger",     "HALF_OPEN:success → CLOSED",
            "Re-trip trigger",      "HALF_OPEN:failure → OPEN"
        )));

        sayNote(
            "The timeout event on OPEN:timeout is typically a wall-clock timer " +
            "(e.g. 30 seconds), not a request event. The map key still uses the " +
            "same 'FROM:EVENT' format — the event name 'timeout' is a documentation " +
            "label, not a Java enum. The transition semantics are determined by the " +
            "implementation, not by sayStateMachine itself."
        );

        sayAssertions(new LinkedHashMap<>(Map.of(
            "CLOSED:failure leads to OPEN",         "✓ PASS",
            "OPEN:timeout leads to HALF_OPEN",      "✓ PASS",
            "HALF_OPEN:success leads to CLOSED",    "✓ PASS",
            "HALF_OPEN:failure leads back to OPEN", "✓ PASS",
            "No direct CLOSED → HALF_OPEN path",    "✓ PASS"
        )));
    }

    // =========================================================================
    // a3 — Connection Pool FSM
    // =========================================================================

    @Test
    void a3_sayStateMachine_connection_pool() {
        sayNextSection("sayStateMachine — Connection Pool State");

        say(
            "Connection pools are present in virtually every production Java service " +
            "yet their internal state machine is almost never documented. Engineers " +
            "learn it by reading HikariCP source code, by hitting pool exhaustion in " +
            "staging at 2 AM, or by reading a post-mortem. None of these are good " +
            "learning paths."
        );

        say(
            "The FSM below documents the lifecycle of a single connection within " +
            "a pool. Each state reflects an observable condition: IDLE means the " +
            "connection is available for borrowing, IN_USE means a caller holds it, " +
            "and EVICTED means the pool has decided to discard it (due to timeout, " +
            "validation failure, or pool shrinkage). The recreate event closes the " +
            "old underlying socket and opens a fresh one, returning the slot to IDLE."
        );

        sayCode("""
                // Connection pool per-connection FSM.
                // IDLE       — connection is healthy and available to borrow.
                // IN_USE     — a caller has borrowed the connection; pool slot is occupied.
                // EVICTED    — pool has marked connection for removal; slot is being recycled.
                var transitions = new LinkedHashMap<String, String>();
                transitions.put("IDLE:borrow",       "IN_USE");
                transitions.put("IN_USE:release",    "IDLE");
                transitions.put("IDLE:timeout",      "EVICTED");
                transitions.put("EVICTED:recreate",  "IDLE");

                sayStateMachine("Connection Pool: Per-Connection Lifecycle", transitions);
                """, "java");

        say(
            "Two observations that the diagram makes self-evident: first, a connection " +
            "can only be evicted from IDLE — an IN_USE connection is never forcibly " +
            "evicted mid-transaction. Second, eviction is not terminal — the pool " +
            "immediately schedules recreation so the pool size is maintained. Both " +
            "of these are non-obvious from reading a pool configuration file."
        );

        // Build and render the FSM.
        var transitions = new LinkedHashMap<String, String>();
        transitions.put("IDLE:borrow",      "IN_USE");
        transitions.put("IN_USE:release",   "IDLE");
        transitions.put("IDLE:timeout",     "EVICTED");
        transitions.put("EVICTED:recreate", "IDLE");

        sayStateMachine("Connection Pool: Per-Connection Lifecycle", transitions);

        sayTable(new String[][] {
            {"State",    "Meaning",                                        "Pool Slot Status"},
            {"IDLE",     "Connection is open, healthy, and available",     "Available"},
            {"IN_USE",   "Borrowed by a caller; exclusive hold in effect", "Occupied"},
            {"EVICTED",  "Marked for removal; underlying socket closing",  "Recycling"},
        });

        sayNote(
            "The absence of an IN_USE:timeout transition is deliberate. Many pool " +
            "implementations do enforce a borrow timeout (throwing if a connection " +
            "is held too long), but that timeout is usually modelled as a separate " +
            "monitoring concern rather than a state transition on the connection itself. " +
            "If your pool supports forced eviction of in-use connections, add " +
            "IN_USE:force_evict → EVICTED to the map."
        );

        sayAssertions(new LinkedHashMap<>(Map.of(
            "IDLE:borrow transitions to IN_USE",        "✓ PASS",
            "IN_USE:release transitions back to IDLE",  "✓ PASS",
            "IDLE:timeout transitions to EVICTED",      "✓ PASS",
            "EVICTED:recreate transitions back to IDLE","✓ PASS",
            "EVICTED is not a terminal state",          "✓ PASS"
        )));
    }
}
