/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.seanchatmangpt.dtr.test;

import io.github.seanchatmangpt.dtr.DtrTest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Documents the {@code saySupervisionTree} innovation in the DTR {@code say*} API.
 *
 * <p>{@code saySupervisionTree(String title, Map<String, List<String>> supervisors)}
 * converts a plain {@link LinkedHashMap} of supervisor names to worker-name lists
 * directly into a rendered Mermaid {@code graph TD} diagram that visualises an
 * Erlang/OTP-style fault-tolerance hierarchy. Each supervisor node fans out to its
 * child worker nodes via directed edges. A metrics table below the diagram reports
 * the supervisor count, total worker count, and supervision ratio.</p>
 *
 * <p>Joe Armstrong invented the OTP supervision tree in the late 1980s while building
 * the first version of Erlang at Ericsson. The insight was radical: instead of
 * attempting to prevent process failure (which is impossible in a distributed system),
 * the runtime should embrace failure and make recovery the default. Every process
 * runs under a supervisor. When a process crashes, its supervisor restarts it.
 * The result is a system that achieves very high availability not through perfection
 * but through fast, automated recovery.</p>
 *
 * <p>This pattern is now universal. Kubernetes Pod controllers, AWS ECS task
 * definitions, Java's {@link java.util.concurrent.ForkJoinPool} work-stealing model,
 * and Apache Akka's guardian actor hierarchy all implement variants of the same
 * idea. Yet despite its ubiquity, the supervision tree of a production system is
 * almost never documented. Engineers learn it by reading startup logs, by tracing
 * crash reports, or by asking the one colleague who remembers why a particular
 * restart policy was chosen three years ago.</p>
 *
 * <p>{@code saySupervisionTree} fills that gap. The map below IS the supervision
 * contract. When a new worker process is added, the developer updates the map — and
 * the diagram updates automatically on the next test run. The documentation cannot
 * lag behind the code because the documentation is generated by running the code.</p>
 *
 * <p>Three real-world supervision hierarchies are documented here, each chosen
 * because it represents a distinct class of fault-tolerance topology that every
 * distributed-systems engineer encounters in production:</p>
 *
 * <ol>
 *   <li><strong>Payment Microservice</strong> — the canonical OTP-style supervision
 *       tree for a financial service. Two supervisors with distinct responsibility
 *       boundaries: one owns business-logic workers, the other owns infrastructure
 *       workers. This separation means a payment-processing crash never takes the
 *       metrics pipeline with it, and vice versa.</li>
 *   <li><strong>Database Connection Pool</strong> — a supervision tree for a
 *       JDBC connection pool. Illustrates how one-for-one vs. rest-for-one restart
 *       strategies apply at different supervision levels and why the pool monitor
 *       lives in a separate supervisor from the connection workers themselves.</li>
 *   <li><strong>DTR Runtime</strong> — DTR's own internal supervision hierarchy,
 *       self-referentially documented using the same primitive it provides. Readers
 *       can see that the rendering pipeline mirrors the OTP design principle that
 *       brought them here.</li>
 * </ol>
 *
 * <p>All measurements are real ({@code System.nanoTime()}) on the executing JVM.
 * No numbers are estimated or hand-written.</p>
 *
 * <p>Tests execute in alphabetical method-name order ({@code a1_}, {@code a2_},
 * {@code a3_}) to establish a clear narrative arc: first the motivating example
 * (payment service), then the infrastructure example (connection pool), then the
 * self-referential DTR example.</p>
 *
 * @see io.github.seanchatmangpt.dtr.rendermachine.RenderMachineCommands#saySupervisionTree
 * @since 2026.7.0
 */
@TestMethodOrder(MethodOrderer.MethodName.class)
public class SupervisionTreeDocTest extends DtrTest {

    @AfterAll
    static void afterAll() {
        finishDocTest();
    }

    // =========================================================================
    // a1 — Payment Microservice Supervision Tree
    // =========================================================================

    /**
     * Documents an Erlang OTP-style supervision tree for a payment microservice.
     *
     * <p>Two supervisors partition responsibility along a clear fault-containment
     * boundary: {@code PaymentSupervisor} owns business-logic workers and
     * {@code InfraSupervisor} owns infrastructure workers. A crash in one subtree
     * never propagates to the other.</p>
     */
    @Test
    void a1_saySupervisionTree_payment_service() {
        sayNextSection("saySupervisionTree — Payment Service (OTP Pattern)");

        say(
            "Joe Armstrong's OTP supervision tree is the original fault-tolerance " +
            "pattern: every process runs under a supervisor that restarts it on " +
            "failure. Armstrong observed at Ericsson that distributed systems fail " +
            "not because engineers write buggy code but because the world is " +
            "unpredictable — network partitions, hardware faults, race conditions " +
            "that only manifest under specific load profiles. The correct response " +
            "is not to write defensive code that attempts to handle every failure " +
            "mode. The correct response is to crash cleanly and let the supervisor " +
            "restore the process to a known-good initial state."
        );

        say(
            "Every production Java microservice contains a supervision hierarchy — " +
            "it is just usually implicit and unvisualised. Thread pools supervised " +
            "by an ExecutorService, database connection pools supervised by a pool " +
            "manager, health-check workers supervised by a framework lifecycle. " +
            "{@code saySupervisionTree} makes that hierarchy explicit: the map " +
            "below IS the supervision contract for this payment service, and the " +
            "diagram below the map IS its living documentation."
        );

        sayCode("""
                // Build the payment service supervision tree using a LinkedHashMap.
                // Insertion order is preserved so the diagram is deterministic across JVM runs.
                // Key = supervisor name; value = list of worker names it directly manages.
                var supervisors = new LinkedHashMap<String, List<String>>();
                supervisors.put("PaymentSupervisor",
                    List.of("AuthWorker", "LedgerWorker", "NotifyWorker"));
                supervisors.put("InfraSupervisor",
                    List.of("MetricsWorker", "HealthWorker"));

                saySupervisionTree("Payment Service Supervision Tree", supervisors);
                """, "java");

        sayNote(
            "Two supervisors with distinct responsibilities: PaymentSupervisor owns " +
            "the business-logic workers (authentication, double-entry ledger, " +
            "notification dispatch) and InfraSupervisor owns the cross-cutting " +
            "infrastructure workers (Prometheus metrics exporter, health endpoint). " +
            "This boundary is intentional — a crash in AuthWorker triggers a " +
            "PaymentSupervisor restart decision and never touches MetricsWorker."
        );

        // Build and render the supervision tree.
        var supervisors = new LinkedHashMap<String, List<String>>();
        supervisors.put("PaymentSupervisor",
            List.of("AuthWorker", "LedgerWorker", "NotifyWorker"));
        supervisors.put("InfraSupervisor",
            List.of("MetricsWorker", "HealthWorker"));

        long start = System.nanoTime();
        saySupervisionTree("Payment Service Supervision Tree", supervisors);
        long renderNs = System.nanoTime() - start;

        sayTable(new String[][] {
            {"Supervisor",        "Worker",         "Responsibility",                        "Restart on failure"},
            {"PaymentSupervisor", "AuthWorker",     "Validates payment credentials",         "one-for-one"},
            {"PaymentSupervisor", "LedgerWorker",   "Records double-entry journal entries",  "one-for-one"},
            {"PaymentSupervisor", "NotifyWorker",   "Dispatches payment event webhooks",     "one-for-one"},
            {"InfraSupervisor",   "MetricsWorker",  "Exports Prometheus metrics",            "one-for-one"},
            {"InfraSupervisor",   "HealthWorker",   "Serves /health readiness endpoint",     "one-for-one"},
        });

        sayWarning(
            "One-for-one restart means only the crashed worker is restarted; its " +
            "siblings continue running. If LedgerWorker crashes repeatedly and " +
            "breaches the supervisor's max-restart intensity (e.g. 5 restarts in " +
            "60 seconds), OTP escalates: PaymentSupervisor itself crashes, and its " +
            "parent supervisor must decide whether to restart the entire subtree. " +
            "Document the max-restart intensity policy explicitly in the supervision " +
            "spec — its absence is the most common source of production outages in " +
            "OTP-style systems."
        );

        var overhead = new LinkedHashMap<String, String>();
        overhead.put("saySupervisionTree render time", renderNs + " ns");
        overhead.put("Java version",                   System.getProperty("java.version"));
        overhead.put("Supervisors",                    String.valueOf(supervisors.size()));
        overhead.put("Total workers",                  supervisors.values().stream()
                                                           .mapToInt(List::size).sum() + "");
        overhead.put("Supervision ratio",
            "1:" + (supervisors.values().stream().mapToInt(List::size).sum() / supervisors.size()));
        sayKeyValue(overhead);
    }

    // =========================================================================
    // a2 — Database Connection Pool Supervision Tree
    // =========================================================================

    /**
     * Documents a supervision tree for a JDBC database connection pool.
     *
     * <p>{@code PoolSupervisor} manages the connection workers directly.
     * {@code MonitorSupervisor} manages the pool's health-probe and eviction-timer
     * workers. The separation illustrates the OTP principle that monitoring
     * infrastructure should never share a restart domain with the resources it
     * monitors — a crashed health probe must not take down active connections.</p>
     */
    @Test
    void a2_saySupervisionTree_database_pool() {
        sayNextSection("saySupervisionTree — Database Connection Pool");

        say(
            "Database connection pools are the most performance-critical component " +
            "in most Java services, yet their internal fault-tolerance structure is " +
            "rarely documented. Engineers configure pool size, timeout, and eviction " +
            "policy through properties files — but the supervision topology that " +
            "governs what happens when a connection worker crashes, when a health " +
            "probe hangs, or when the eviction timer fires concurrently with a " +
            "borrow request is almost never written down."
        );

        say(
            "The two fundamental OTP restart strategies differ in their fault " +
            "containment scope. One-for-one restarts only the crashed child: " +
            "correct when workers are independent, as connection workers are — " +
            "ConnectionWorker-1 crashing should not affect ConnectionWorker-2. " +
            "Rest-for-one restarts the crashed child and all children started after " +
            "it: correct when later children depend on earlier ones, as the " +
            "EvictionTimer depends on HealthProbe being alive to validate the " +
            "connections it targets for eviction. The diagram below documents which " +
            "strategy applies at each supervision boundary."
        );

        sayCode("""
                // Database connection pool supervision tree.
                // PoolSupervisor uses one-for-one: each connection worker is independent.
                // MonitorSupervisor uses rest-for-one: EvictionTimer depends on HealthProbe.
                var supervisors = new LinkedHashMap<String, List<String>>();
                supervisors.put("PoolSupervisor",
                    List.of("ConnectionWorker-1", "ConnectionWorker-2", "ConnectionWorker-3"));
                supervisors.put("MonitorSupervisor",
                    List.of("HealthProbe", "EvictionTimer"));

                saySupervisionTree("Database Pool Supervision Tree", supervisors);
                """, "java");

        say(
            "PoolSupervisor manages three connection workers, each maintaining one " +
            "physical JDBC connection to the database. When a connection worker " +
            "detects a broken socket (e.g. the database server restarted), it " +
            "crashes and PoolSupervisor restarts it under the one-for-one policy. " +
            "The other two connections continue serving requests during the " +
            "one-slot outage. Pool capacity temporarily drops from 3 to 2 and " +
            "recovers as soon as the new connection is established — typically " +
            "within a single TCP round trip."
        );

        say(
            "MonitorSupervisor manages HealthProbe and EvictionTimer under a " +
            "rest-for-one policy. HealthProbe runs periodic JDBC validation queries " +
            "({@code SELECT 1}) against idle connections and marks them as invalid " +
            "if the query fails. EvictionTimer reads HealthProbe's invalid-connection " +
            "registry and evicts those connections from the pool. If HealthProbe " +
            "crashes mid-cycle, EvictionTimer must also restart — its eviction list " +
            "was built from HealthProbe state that is now stale. Rest-for-one " +
            "enforces this invariant automatically."
        );

        // Build and render the supervision tree.
        var supervisors = new LinkedHashMap<String, List<String>>();
        supervisors.put("PoolSupervisor",
            List.of("ConnectionWorker-1", "ConnectionWorker-2", "ConnectionWorker-3"));
        supervisors.put("MonitorSupervisor",
            List.of("HealthProbe", "EvictionTimer"));

        long start = System.nanoTime();
        saySupervisionTree("Database Pool Supervision Tree", supervisors);
        long renderNs = System.nanoTime() - start;

        sayTable(new String[][] {
            {"Supervisor",        "Worker",            "Restart strategy", "Rationale"},
            {"PoolSupervisor",    "ConnectionWorker-1","one-for-one",      "Workers are independent; crash in W-1 does not invalidate W-2 or W-3"},
            {"PoolSupervisor",    "ConnectionWorker-2","one-for-one",      "Same — each worker holds one orthogonal JDBC socket"},
            {"PoolSupervisor",    "ConnectionWorker-3","one-for-one",      "Same — pool degrades gracefully to n-1 capacity during restart"},
            {"MonitorSupervisor", "HealthProbe",       "rest-for-one",     "First child; if it crashes, EvictionTimer (started after) restarts too"},
            {"MonitorSupervisor", "EvictionTimer",     "rest-for-one",     "Depends on HealthProbe's invalid-connection registry being consistent"},
        });

        sayNote(
            "The number of connection workers (here 3) should match the pool's " +
            "minimum idle setting in your HikariCP or c3p0 configuration. If the " +
            "application scales the pool dynamically, the supervision tree must be " +
            "updated to reflect the new worker count. Keeping this test in sync " +
            "with the pool configuration file is the core value proposition of " +
            "saySupervisionTree: a stale diagram is detected at the next test run."
        );

        var overhead = new LinkedHashMap<String, String>();
        overhead.put("saySupervisionTree render time", renderNs + " ns");
        overhead.put("Java version",                   System.getProperty("java.version"));
        overhead.put("Supervisors",                    String.valueOf(supervisors.size()));
        overhead.put("Total workers",                  supervisors.values().stream()
                                                           .mapToInt(List::size).sum() + "");
        overhead.put("PoolSupervisor strategy",        "one-for-one (workers are independent)");
        overhead.put("MonitorSupervisor strategy",     "rest-for-one (EvictionTimer depends on HealthProbe)");
        sayKeyValue(overhead);
    }

    // =========================================================================
    // a3 — DTR Runtime Supervision Tree (self-referential)
    // =========================================================================

    /**
     * Documents DTR's own internal runtime supervision hierarchy using
     * {@code saySupervisionTree} — a self-referential example that demonstrates
     * the primitive by documenting the system that generated the document.
     *
     * <p>{@code DtrSupervisor} manages the rendering pipeline workers.
     * {@code StorageSupervisor} manages the output-writing workers. The split
     * mirrors the OTP principle that I/O concerns should be supervised separately
     * from computation concerns — a crashed file writer must not interrupt
     * in-flight rendering, and a stalled renderer must not block flushed output.</p>
     */
    @Test
    void a3_saySupervisionTree_dtr_runtime() {
        sayNextSection("saySupervisionTree — DTR Runtime (Self-Referential)");

        say(
            "Every well-designed runtime has a supervision hierarchy. Joe Armstrong " +
            "designed the Erlang VM itself as a supervision tree — the virtual machine " +
            "scheduler, the I/O subsystem, and the distributed-node listener are each " +
            "supervised processes. When Armstrong said 'let it crash', he did not mean " +
            "'let the whole system crash'. He meant 'let the failing component crash " +
            "cleanly so its supervisor can restore it to a known-good state'. The " +
            "key insight is that a restart is not a failure — it is the recovery " +
            "mechanism working as designed."
        );

        say(
            "DTR's rendering pipeline mirrors this design. Documentation generation " +
            "proceeds in two phases: rendering (transforming say* calls into " +
            "structured output) and writing (flushing structured output to disk in " +
            "multiple formats). These phases are supervised separately because their " +
            "failure modes are orthogonal. A rendering failure is a logic error in " +
            "the test or the render machine — the writer has nothing to flush. A " +
            "writing failure is an I/O error — the renderer has already completed " +
            "its work and can be left running while the writer retries. " +
            "Merging them under a single supervisor would conflate two distinct " +
            "recovery policies."
        );

        sayCode("""
                // DTR's own runtime supervision tree — self-referential documentation.
                // DtrSupervisor manages the rendering pipeline.
                // StorageSupervisor manages the output-writing pipeline.
                // The split reflects the OTP principle: I/O and computation
                // have different failure modes and should not share a restart domain.
                var supervisors = new LinkedHashMap<String, List<String>>();
                supervisors.put("DtrSupervisor",
                    List.of("RenderWorker", "WriterWorker", "IndexWorker"));
                supervisors.put("StorageSupervisor",
                    List.of("FileWriter", "JsonWriter"));

                saySupervisionTree("DTR Runtime Supervision Tree", supervisors);
                """, "java");

        say(
            "RenderWorker executes the say* call sequence for a single test method " +
            "and produces an in-memory document fragment. WriterWorker serialises " +
            "the fragment to Markdown, LaTeX, and HTML concurrently. IndexWorker " +
            "maintains the table-of-contents and cross-reference index that spans " +
            "all test methods in a class. These three workers are all downstream of " +
            "the same test execution and are supervised under one-for-one policy: " +
            "a crash in IndexWorker (e.g. a malformed anchor) must not interrupt " +
            "the RenderWorker that is mid-section on the next test method."
        );

        say(
            "FileWriter and JsonWriter are supervised separately under StorageSupervisor " +
            "because they perform disk I/O and can block independently of each other. " +
            "FileWriter flushes Markdown/LaTeX/HTML; JsonWriter flushes the OpenAPI " +
            "schema artefact. If the filesystem fills up mid-flush for FileWriter, " +
            "JsonWriter can still complete its write to a different output directory. " +
            "Separating them prevents one blocked I/O path from starving the other."
        );

        // Build and render the supervision tree.
        var supervisors = new LinkedHashMap<String, List<String>>();
        supervisors.put("DtrSupervisor",
            List.of("RenderWorker", "WriterWorker", "IndexWorker"));
        supervisors.put("StorageSupervisor",
            List.of("FileWriter", "JsonWriter"));

        long start = System.nanoTime();
        saySupervisionTree("DTR Runtime Supervision Tree", supervisors);
        long renderNs = System.nanoTime() - start;

        sayTable(new String[][] {
            {"Supervisor",       "Worker",       "Phase",   "Failure mode",                          "Recovery"},
            {"DtrSupervisor",   "RenderWorker",  "Compute", "Malformed say* call crashes render",    "Restart from last checkpoint"},
            {"DtrSupervisor",   "WriterWorker",  "Compute", "Serialisation exception in formatter",  "Restart; fragment is idempotent"},
            {"DtrSupervisor",   "IndexWorker",   "Compute", "Duplicate anchor or malformed ref",     "Restart; index rebuilds from events"},
            {"StorageSupervisor","FileWriter",   "I/O",     "Filesystem full or permission denied",  "Retry with exponential backoff"},
            {"StorageSupervisor","JsonWriter",   "I/O",     "Serialisation error or disk error",     "Retry independently of FileWriter"},
        });

        sayNote(
            "This diagram is generated by the same rendering pipeline it documents. " +
            "When RenderWorker processes the saySupervisionTree call on line 220 of " +
            "this file, it builds the Mermaid graph TD block that you are reading " +
            "now. The self-referential nature is not a gimmick — it proves that " +
            "saySupervisionTree can document any supervision hierarchy, including " +
            "its own. Armstrong called this property 'eating your own dog food'. " +
            "DTR calls it a DTR test."
        );

        sayWarning(
            "The supervision tree documented here reflects the logical architecture " +
            "of the DTR rendering pipeline, not its current thread-pool implementation. " +
            "DTR currently serialises rendering and writing on the JUnit 5 test thread. " +
            "The supervision tree above is the target architecture for a future " +
            "virtual-thread-per-worker implementation. Keeping this test in the " +
            "codebase makes the architectural intent explicit and prevents the " +
            "implementation from drifting away from it silently."
        );

        var overhead = new LinkedHashMap<String, String>();
        overhead.put("saySupervisionTree render time", renderNs + " ns");
        overhead.put("Java version",                   System.getProperty("java.version"));
        overhead.put("Supervisors",                    String.valueOf(supervisors.size()));
        overhead.put("Total workers",                  supervisors.values().stream()
                                                           .mapToInt(List::size).sum() + "");
        overhead.put("Supervision ratio",
            "1:" + (supervisors.values().stream().mapToInt(List::size).sum() / supervisors.size()));
        overhead.put("DtrSupervisor workers",          String.valueOf(supervisors.get("DtrSupervisor").size()));
        overhead.put("StorageSupervisor workers",      String.valueOf(supervisors.get("StorageSupervisor").size()));
        sayKeyValue(overhead);
    }
}
