/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.seanchatmangpt.dtr.assembly;

import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.List;
import java.util.Map;

/**
 * Assembles multiple DocTest .tex files into a unified document manifest.
 *
 * This class provides static factory methods for analyzing and combining
 * LaTeX source files generated by DocTester tests into a consolidated
 * assembly manifest with aggregated metadata.
 */
public final class DocumentAssembler {

    private DocumentAssembler() {
        // Utility class
    }

    /**
     * Assembles multiple .tex files into a manifest with aggregated metadata.
     *
     * @param texFiles list of paths to LaTeX source files
     * @return AssemblyManifest containing aggregated metadata
     * @throws IllegalArgumentException if texFiles is null or empty
     */
    public static AssemblyManifest assemble(List<Path> texFiles) {
        if (texFiles == null || texFiles.isEmpty()) {
            throw new IllegalArgumentException("texFiles cannot be null or empty");
        }

        var totalPages = 0;
        var totalWords = 0;
        var totalCodeListings = 0;
        var totalTables = 0;
        var totalCitations = 0;
        var totalCrossReferences = 0;

        // Process each .tex file
        for (Path texFile : texFiles) {
            if (!Files.exists(texFile)) {
                continue;
            }

            try {
                String content = Files.readString(texFile);

                // Count pages: simple approach counting \newpage directives
                totalPages += countNewPages(content);

                // Count words using WordCounter
                totalWords += WordCounter.count(content);

                // Count code listings
                totalCodeListings += countCodeListings(content);

                // Count tables/figures
                totalTables += countTables(content);

                // Count citations
                totalCitations += countCitations(content);

                // Count cross-references
                totalCrossReferences += countCrossReferences(content);
            } catch (Exception e) {
                // Log and continue processing other files
                System.err.println("Error processing " + texFile + ": " + e.getMessage());
            }
        }

        return new AssemblyManifest(
            texFiles,
            totalPages,
            totalWords,
            totalCodeListings,
            totalTables,
            totalCitations,
            totalCrossReferences,
            null,  // assemblyReceipt - would be generated by a separate signing service
            Map.of(),  // componentReceipts - would be filled by component-level receipts
            Instant.now(),
            ""  // sha3HashOfManifest - would be computed by a hash service
        );
    }

    /**
     * Counts \newpage directives in LaTeX content.
     */
    private static int countNewPages(String content) {
        if (content == null || content.isEmpty()) {
            return 0;
        }
        var count = 0;
        var index = 0;
        while ((index = content.indexOf("\\newpage", index)) != -1) {
            count++;
            index += 8;  // length of "\\newpage"
        }
        return count;
    }

    /**
     * Counts code listings (lstlisting environments).
     */
    private static int countCodeListings(String content) {
        if (content == null || content.isEmpty()) {
            return 0;
        }
        var count = 0;
        var index = 0;
        while ((index = content.indexOf("\\begin{lstlisting}", index)) != -1) {
            count++;
            index += 18;  // length of "\\begin{lstlisting}"
        }
        return count;
    }

    /**
     * Counts table and figure environments.
     */
    private static int countTables(String content) {
        if (content == null || content.isEmpty()) {
            return 0;
        }
        var count = 0;

        // Count tables
        var index = 0;
        while ((index = content.indexOf("\\begin{table}", index)) != -1) {
            count++;
            index += 13;  // length of "\\begin{table}"
        }

        // Count figures
        index = 0;
        while ((index = content.indexOf("\\begin{figure}", index)) != -1) {
            count++;
            index += 14;  // length of "\\begin{figure}"
        }

        return count;
    }

    /**
     * Counts citation commands (\cite{...}).
     */
    private static int countCitations(String content) {
        if (content == null || content.isEmpty()) {
            return 0;
        }
        var count = 0;
        var index = 0;
        while ((index = content.indexOf("\\cite{", index)) != -1) {
            count++;
            index += 6;  // length of "\\cite{"
        }
        return count;
    }

    /**
     * Counts cross-references (\ref{...} and \label{...}).
     */
    private static int countCrossReferences(String content) {
        if (content == null || content.isEmpty()) {
            return 0;
        }
        var count = 0;

        // Count \ref commands
        var index = 0;
        while ((index = content.indexOf("\\ref{", index)) != -1) {
            count++;
            index += 5;  // length of "\\ref{"
        }

        // Count \label commands
        index = 0;
        while ((index = content.indexOf("\\label{", index)) != -1) {
            count++;
            index += 7;  // length of "\\label{"
        }

        return count;
    }
}
