/**
 * Copyright (C) 2026 Sean Chatman.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * Generated by ggen from ontology/jotp-api.ttl — do not edit by hand.
 * Re-generate: cd jotp && ggen sync
 */
package io.github.seanchatmangpt.dtr.jotp;

import org.junit.Test;
import io.github.seanchatmangpt.dtr.DtrTest;

/**
 * DTR documentation for jotp
 * Parallel, Result
 * primitives — generated from {@code jotp-api.ttl}.
 *
 * <p>Each {@code @Test} method documents one primitive:
 * <ul>
 *   <li>{@code Parallel<T>} — Structured concurrency with fail-fast semantics across multiple tasks</li>
 *   <li>{@code Result<T,E>} — Railway-oriented error handling: Success&lt;T&gt; or Failure&lt;E&gt;</li>
 * </ul>
 */
public class ErrorHandlingDocTest extends DtrTest {

    // ─────────────────────────────────────────────────────────────────────────
    // Parallel<T>
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testParallelOverview() {
        sayNextSection("Parallel<T> — Structured concurrency with fail-fast semantics across multiple tasks");
        say("<code>Parallel<T></code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.Parallel</code>.");

        String[][] methods = new String[2 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>all</code>",
            "<code>List<T> all(List<Callable<T>> tasks)</code>",
            "Runs all tasks in parallel; fails fast if any task throws"
        };
        methods[2] = new String[]{
            "<code>race</code>",
            "<code>T race(List<Callable<T>> tasks)</code>",
            "Returns the first task to complete; cancels all remaining tasks"
        };
        sayTable(methods);

        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Result<T,E>
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testResultOverview() {
        sayNextSection("Result<T,E> — Railway-oriented error handling: Success<T> or Failure<E>");
        say("<code>Result<T,E></code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.Result</code>.");

        String[][] methods = new String[4 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>failure</code>",
            "<code>static <T,E> Result<T,E> failure(E error)</code>",
            "Wraps an error in a Failure record"
        };
        methods[2] = new String[]{
            "<code>fold</code>",
            "<code><R> R fold(Function<T,R> onSuccess, Function<E,R> onFailure)</code>",
            "Exhaustive pattern: applies one of two functions to extract R"
        };
        methods[3] = new String[]{
            "<code>map</code>",
            "<code><U> Result<U,E> map(Function<T,U> f)</code>",
            "Transforms the success value; leaves Failure unchanged"
        };
        methods[4] = new String[]{
            "<code>success</code>",
            "<code>static <T,E> Result<T,E> success(T value)</code>",
            "Wraps a successful value in a Success record"
        };
        sayTable(methods);

        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }
}
