/**
 * Copyright (C) 2026 Sean Chatman.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * Generated by ggen from ontology/jotp-api.ttl — do not edit by hand.
 * Re-generate: cd jotp && ggen sync
 */
package io.github.seanchatmangpt.dtr.jotp;

import org.junit.Test;
import io.github.seanchatmangpt.dtr.DtrTest;

/**
 * DTR documentation for jotp
 * ProcLib, ProcRegistry, ProcSys
 * primitives — generated from {@code jotp-api.ttl}.
 *
 * <p>Each {@code @Test} method documents one primitive:
 * <ul>
 *   <li>{@code ProcLib} — Application startup coordination: ensures processes are ready before serving</li>
 *   <li>{@code ProcRegistry} — Named-process registry: register, lookup, and unregister ProcRefs by name</li>
 *   <li>{@code ProcSys} — System introspection: list all live processes, counts, and stats</li>
 * </ul>
 */
public class RuntimeServicesDocTest extends DtrTest {

    // ─────────────────────────────────────────────────────────────────────────
    // ProcLib
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testProcLibOverview() {
        sayNextSection("ProcLib — Application startup coordination: ensures processes are ready before serving");
        say("<code>ProcLib</code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.ProcLib</code>.");

        String[][] methods = new String[2 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>awaitReady</code>",
            "<code>void awaitReady(AppRef ref, Duration timeout)</code>",
            "Blocks until all supervised children report ready or timeout expires"
        };
        methods[2] = new String[]{
            "<code>start</code>",
            "<code>AppRef start(AppSpec spec)</code>",
            "Starts the OTP application from a declarative spec"
        };
        sayTable(methods);

        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // ProcRegistry
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testProcRegistryOverview() {
        sayNextSection("ProcRegistry — Named-process registry: register, lookup, and unregister ProcRefs by name");
        say("<code>ProcRegistry</code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.ProcRegistry</code>.");

        String[][] methods = new String[2 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>register</code>",
            "<code>void register(String name, ProcRef<?,?> ref)</code>",
            "Associates a name with a ProcRef for global lookup"
        };
        methods[2] = new String[]{
            "<code>whereis</code>",
            "<code>Optional<ProcRef<?,?>> whereis(String name)</code>",
            "Returns the ProcRef registered under name, or empty if absent"
        };
        sayTable(methods);

        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // ProcSys
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testProcSysOverview() {
        sayNextSection("ProcSys — System introspection: list all live processes, counts, and stats");
        say("<code>ProcSys</code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.ProcSys</code>.");

        String[][] methods = new String[2 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>count</code>",
            "<code>long count()</code>",
            "Returns the current number of live processes in the runtime"
        };
        methods[2] = new String[]{
            "<code>list</code>",
            "<code>List<ProcRef<?,?>> list()</code>",
            "Returns a snapshot of all currently live process references"
        };
        sayTable(methods);

        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }
}
