/**
 * Copyright (C) 2026 Sean Chatman.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * Generated by ggen from ontology/jotp-api.ttl — do not edit by hand.
 * Re-generate: cd jotp && ggen sync
 */
package io.github.seanchatmangpt.dtr.jotp;

import org.junit.Test;
import io.github.seanchatmangpt.dtr.DtrTest;

/**
 * DTR documentation for jotp
 * EventManager, StateMachine
 * primitives — generated from {@code jotp-api.ttl}.
 *
 * <p>Each {@code @Test} method documents one primitive:
 * <ul>
 *   <li>{@code EventManager<E>} — Typed event broadcasting to all registered handler processes</li>
 *   <li>{@code StateMachine<S,E,D>} — Complex workflow engine with sealed-type state and event transitions</li>
 * </ul>
 */
public class StateManagementDocTest extends DtrTest {

    // ─────────────────────────────────────────────────────────────────────────
    // EventManager<E>
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testEventManagerOverview() {
        sayNextSection("EventManager<E> — Typed event broadcasting to all registered handler processes");
        say("<code>EventManager<E></code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.EventManager</code>.");

        String[][] methods = new String[2 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>notify</code>",
            "<code>void notify(E event)</code>",
            "Broadcasts the event to all subscribed handlers"
        };
        methods[2] = new String[]{
            "<code>subscribe</code>",
            "<code>void subscribe(ProcRef<?,E> handler)</code>",
            "Registers a process to receive all future events"
        };
        sayTable(methods);

        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // StateMachine<S,E,D>
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testStateMachineOverview() {
        sayNextSection("StateMachine<S,E,D> — Complex workflow engine with sealed-type state and event transitions");
        say("<code>StateMachine<S,E,D></code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.StateMachine</code>.");

        String[][] methods = new String[2 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>currentState</code>",
            "<code>S currentState()</code>",
            "Returns the current state of the machine without advancing it"
        };
        methods[2] = new String[]{
            "<code>transition</code>",
            "<code>S transition(S current, E event, D data)</code>",
            "Applies an event to the current state and returns the next state"
        };
        sayTable(methods);

        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }
}
