/**
 * Copyright (C) 2026 Sean Chatman.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 *
 * Generated by ggen from ontology/jotp-api.ttl — do not edit by hand.
 * Re-generate: cd jotp && ggen sync
 */
package io.github.seanchatmangpt.dtr.jotp;

import org.junit.Test;
import io.github.seanchatmangpt.dtr.DtrTest;

/**
 * DTR documentation for jotp
 * Supervisor
 * primitives — generated from {@code jotp-api.ttl}.
 *
 * <p>Each {@code @Test} method documents one primitive:
 * <ul>
 *   <li>{@code Supervisor} — Fault-recovery tree that automatically restarts crashed child processes</li>
 * </ul>
 */
public class SupervisorDocTest extends DtrTest {

    // ─────────────────────────────────────────────────────────────────────────
    // Supervisor
    // ─────────────────────────────────────────────────────────────────────────

    @Test
    public void testSupervisorOverview() {
        sayNextSection("Supervisor — Fault-recovery tree that automatically restarts crashed child processes");
        say("<code>Supervisor</code> is "
                + "a jotp primitive implemented in "
                + "<code>io.github.seanchatmangpt.jotp.Supervisor</code>.");

        String[][] methods = new String[3 + 1][3];
        methods[0] = new String[]{"Method", "Signature", "Description"};
        methods[1] = new String[]{
            "<code>startChild</code>",
            "<code>ChildRef startChild(ChildSpec spec)</code>",
            "Registers and starts a child process under this supervisor"
        };
        methods[2] = new String[]{
            "<code>stopChild</code>",
            "<code>void stopChild(ChildRef ref)</code>",
            "Stops and deregisters a child from the supervision tree"
        };
        methods[3] = new String[]{
            "<code>strategy</code>",
            "<code>RestartStrategy strategy()</code>",
            "Returns ONE_FOR_ONE, ONE_FOR_ALL, or REST_FOR_ONE"
        };
        sayTable(methods);

        sayNote("Restart latency ~200µs measured on Java 26.ea.13 with virtual threads");
        sayNote("Add <code>sayAndAssertThat</code> assertions after importing jotp as a dependency.");
    }
}
