"""Chicago-style TDD tests for `dtr schema` commands.

Tests real behavior with real collaborators — no mocks, no fakes.
Uses typer CliRunner to invoke the real CLI app end-to-end,
and pytest tmp_path for real file I/O.
"""

import json
from pathlib import Path

import pytest
from typer.testing import CliRunner

from dtr_cli.main import app
from dtr_cli.commands.schema import (
    _detect_format,
    _validate_html,
    _validate_json,
    _validate_markdown,
    _analyse_html_structure,
    _analyse_json_structure,
    _analyse_markdown_structure,
)

runner = CliRunner()

# ---------------------------------------------------------------------------
# Sample content fixtures
# ---------------------------------------------------------------------------

GOOD_HTML = """\
<!DOCTYPE html>
<html>
<head><title>DTR Report</title></head>
<body>
  <h1>Introduction</h1>
  <p>This is a test report generated by DTR.</p>
  <h2>Details</h2>
  <p>More content here.</p>
  <code>System.out.println("hello");</code>
</body>
</html>
"""

HTML_NO_TITLE = """\
<!DOCTYPE html>
<html>
<head></head>
<body>
  <h1>Section</h1>
  <p>Body content.</p>
</body>
</html>
"""

HTML_NO_BODY = """\
<!DOCTYPE html>
<html>
<head><title>Report</title></head>
</html>
"""

HTML_NO_HEADINGS = """\
<!DOCTYPE html>
<html>
<head><title>Report</title></head>
<body>
  <p>Just a paragraph, no headings.</p>
</body>
</html>
"""

HTML_EMPTY_TITLE = """\
<!DOCTYPE html>
<html>
<head><title>   </title></head>
<body>
  <h1>Section</h1>
</body>
</html>
"""

HTML_NO_H1 = """\
<!DOCTYPE html>
<html>
<head><title>Report</title></head>
<body>
  <h2>Subsection</h2>
  <p>Content.</p>
</body>
</html>
"""

GOOD_JSON = json.dumps({
    "sections": [
        {"type": "paragraph", "content": "Hello world"},
        {"type": "code", "lang": "java", "content": "System.out.println();"},
    ],
    "metadata": {
        "title": "API Reference",
        "generated_at": "2026-03-12T10:00:00Z",
    },
}, indent=2)

JSON_MISSING_SECTIONS = json.dumps({"metadata": {"title": "Report", "generated_at": "2026-01-01"}})

JSON_MISSING_METADATA = json.dumps({"sections": [{"type": "paragraph", "content": "Hi"}]})

JSON_EMPTY_SECTIONS = json.dumps({"sections": [], "metadata": {"title": "T", "generated_at": "2026-01-01"}})

JSON_MISSING_META_KEYS = json.dumps({
    "sections": [{"type": "paragraph", "content": "Hi"}],
    "metadata": {},
})

JSON_INVALID = "{ this is not valid JSON }"

JSON_NOT_OBJECT = json.dumps([1, 2, 3])

GOOD_MD = """\
# Introduction

This document covers the DTR API.

## Getting Started

Follow these steps to begin.

### Installation

Run the installer.

## Advanced Usage

More details here.
"""

MD_NO_HEADINGS = """\
Just some paragraph text.

More paragraphs.

No headings at all.
"""

MD_STARTS_WITH_H2 = """\
## Not an H1

Some content.

### Subsection
"""

MD_SKIPS_LEVEL = """\
# Top Level

### Skipped H2 (goes from H1 to H3)

Content here.
"""


# ===========================================================================
# Unit tests: _detect_format
# ===========================================================================


class TestDetectFormat:
    """Test format detection from file extension."""

    def test_detects_html(self, tmp_path: Path):
        assert _detect_format(tmp_path / "report.html") == "html"

    def test_detects_htm(self, tmp_path: Path):
        assert _detect_format(tmp_path / "report.htm") == "html"

    def test_detects_json(self, tmp_path: Path):
        assert _detect_format(tmp_path / "data.json") == "json"

    def test_detects_md(self, tmp_path: Path):
        assert _detect_format(tmp_path / "guide.md") == "md"

    def test_detects_markdown(self, tmp_path: Path):
        assert _detect_format(tmp_path / "guide.markdown") == "md"

    def test_returns_none_for_unknown(self, tmp_path: Path):
        assert _detect_format(tmp_path / "archive.zip") is None

    def test_case_insensitive(self, tmp_path: Path):
        assert _detect_format(tmp_path / "REPORT.HTML") == "html"


# ===========================================================================
# Unit tests: _validate_html
# ===========================================================================


class TestValidateHtml:
    """Test HTML validation logic."""

    def test_good_html_has_no_errors_or_warnings(self):
        errors, warnings = _validate_html(GOOD_HTML, strict=False)
        assert errors == []
        assert warnings == []

    def test_missing_title_is_an_error(self):
        errors, warnings = _validate_html(HTML_NO_TITLE, strict=False)
        assert any("title" in e.lower() for e in errors)

    def test_missing_body_is_an_error(self):
        errors, warnings = _validate_html(HTML_NO_BODY, strict=False)
        assert any("body" in e.lower() for e in errors)

    def test_no_headings_is_an_error(self):
        errors, warnings = _validate_html(HTML_NO_HEADINGS, strict=False)
        assert any("heading" in e.lower() for e in errors)

    def test_empty_title_produces_warning(self):
        errors, warnings = _validate_html(HTML_EMPTY_TITLE, strict=False)
        assert errors == []
        assert any("empty" in w.lower() or "title" in w.lower() for w in warnings)

    def test_no_h1_produces_warning_not_error(self):
        errors, warnings = _validate_html(HTML_NO_H1, strict=False)
        assert errors == []
        assert any("h1" in w.lower() for w in warnings)

    def test_empty_title_in_strict_mode_is_treated_as_error(self):
        errors, warnings = _validate_html(HTML_EMPTY_TITLE, strict=True)
        # In strict mode we pass warnings up to the caller; validator itself still
        # puts it in warnings — the CLI layer promotes them. Here we confirm the
        # warning is detected.
        assert any("empty" in w.lower() or "title" in w.lower() for w in warnings)


# ===========================================================================
# Unit tests: _validate_json
# ===========================================================================


class TestValidateJson:
    """Test JSON validation logic."""

    def test_good_json_has_no_errors_or_warnings(self):
        errors, warnings = _validate_json(GOOD_JSON, strict=False)
        assert errors == []
        assert warnings == []

    def test_missing_sections_key_is_error(self):
        errors, warnings = _validate_json(JSON_MISSING_SECTIONS, strict=False)
        assert any("sections" in e for e in errors)

    def test_missing_metadata_key_is_error(self):
        errors, warnings = _validate_json(JSON_MISSING_METADATA, strict=False)
        assert any("metadata" in e for e in errors)

    def test_empty_sections_is_warning(self):
        errors, warnings = _validate_json(JSON_EMPTY_SECTIONS, strict=False)
        assert errors == []
        assert any("sections" in w for w in warnings)

    def test_missing_metadata_sub_keys_are_warnings(self):
        errors, warnings = _validate_json(JSON_MISSING_META_KEYS, strict=False)
        assert errors == []
        assert len(warnings) >= 2  # title and generated_at both missing

    def test_invalid_json_is_error(self):
        errors, warnings = _validate_json(JSON_INVALID, strict=False)
        assert any("invalid json" in e.lower() or "json" in e.lower() for e in errors)

    def test_non_object_top_level_is_error(self):
        errors, warnings = _validate_json(JSON_NOT_OBJECT, strict=False)
        assert any("object" in e.lower() for e in errors)


# ===========================================================================
# Unit tests: _validate_markdown
# ===========================================================================


class TestValidateMarkdown:
    """Test Markdown heading hierarchy validation."""

    def test_good_markdown_has_no_errors_or_warnings(self):
        errors, warnings = _validate_markdown(GOOD_MD, strict=False)
        assert errors == []
        assert warnings == []

    def test_no_headings_is_error(self):
        errors, warnings = _validate_markdown(MD_NO_HEADINGS, strict=False)
        assert any("heading" in e.lower() for e in errors)

    def test_not_starting_with_h1_is_warning(self):
        errors, warnings = _validate_markdown(MD_STARTS_WITH_H2, strict=False)
        assert errors == []
        assert any("h1" in w.lower() or "start" in w.lower() for w in warnings)

    def test_skipped_heading_level_is_warning(self):
        errors, warnings = _validate_markdown(MD_SKIPS_LEVEL, strict=False)
        assert errors == []
        assert any("skip" in w.lower() or "h3" in w.lower() for w in warnings)

    def test_single_h1_no_warnings(self):
        errors, warnings = _validate_markdown("# Title\n\nContent.", strict=False)
        assert errors == []
        assert warnings == []


# ===========================================================================
# Unit tests: analysis helpers
# ===========================================================================


class TestAnalyseHtmlStructure:
    """Test HTML structure extraction."""

    def test_extracts_title(self, tmp_path: Path):
        f = tmp_path / "r.html"
        f.write_text(GOOD_HTML, encoding="utf-8")
        result = _analyse_html_structure(f)
        assert result["title"] == "DTR Report"

    def test_extracts_headings(self, tmp_path: Path):
        f = tmp_path / "r.html"
        f.write_text(GOOD_HTML, encoding="utf-8")
        result = _analyse_html_structure(f)
        levels = [h["level"] for h in result["headings"]]
        assert 1 in levels
        assert 2 in levels

    def test_counts_code_blocks(self, tmp_path: Path):
        f = tmp_path / "r.html"
        f.write_text(GOOD_HTML, encoding="utf-8")
        result = _analyse_html_structure(f)
        assert result["code_block_count"] >= 1

    def test_empty_html_returns_empty_title(self, tmp_path: Path):
        f = tmp_path / "r.html"
        f.write_text("<html><head></head><body></body></html>", encoding="utf-8")
        result = _analyse_html_structure(f)
        assert result["title"] == ""


class TestAnalyseJsonStructure:
    """Test JSON structure extraction."""

    def test_extracts_top_level_keys(self, tmp_path: Path):
        f = tmp_path / "data.json"
        f.write_text(GOOD_JSON, encoding="utf-8")
        result = _analyse_json_structure(f)
        assert "sections" in result["top_level_keys"]
        assert "metadata" in result["top_level_keys"]

    def test_counts_sections(self, tmp_path: Path):
        f = tmp_path / "data.json"
        f.write_text(GOOD_JSON, encoding="utf-8")
        result = _analyse_json_structure(f)
        assert result["section_count"] == 2

    def test_extracts_section_types(self, tmp_path: Path):
        f = tmp_path / "data.json"
        f.write_text(GOOD_JSON, encoding="utf-8")
        result = _analyse_json_structure(f)
        assert "paragraph" in result["section_types"]
        assert "code" in result["section_types"]

    def test_extracts_metadata_keys(self, tmp_path: Path):
        f = tmp_path / "data.json"
        f.write_text(GOOD_JSON, encoding="utf-8")
        result = _analyse_json_structure(f)
        assert "title" in result["metadata_keys"]
        assert "generated_at" in result["metadata_keys"]

    def test_invalid_json_returns_error_flag(self, tmp_path: Path):
        f = tmp_path / "bad.json"
        f.write_text("not json", encoding="utf-8")
        result = _analyse_json_structure(f)
        assert result.get("parse_error") is True


class TestAnalyseMarkdownStructure:
    """Test Markdown structure extraction."""

    def test_counts_headings(self, tmp_path: Path):
        f = tmp_path / "doc.md"
        f.write_text(GOOD_MD, encoding="utf-8")
        result = _analyse_markdown_structure(f)
        assert result["heading_count"] >= 4

    def test_extracts_heading_levels_and_text(self, tmp_path: Path):
        f = tmp_path / "doc.md"
        f.write_text(GOOD_MD, encoding="utf-8")
        result = _analyse_markdown_structure(f)
        levels = [h["level"] for h in result["headings"]]
        assert 1 in levels
        assert 2 in levels

    def test_counts_code_blocks(self, tmp_path: Path):
        md_with_code = "# Title\n\n```java\nSystem.out.println();\n```\n"
        f = tmp_path / "doc.md"
        f.write_text(md_with_code, encoding="utf-8")
        result = _analyse_markdown_structure(f)
        assert result["code_block_count"] == 1

    def test_no_headings_returns_zero(self, tmp_path: Path):
        f = tmp_path / "doc.md"
        f.write_text(MD_NO_HEADINGS, encoding="utf-8")
        result = _analyse_markdown_structure(f)
        assert result["heading_count"] == 0


# ===========================================================================
# Integration tests: `dtr schema validate`
# ===========================================================================


class TestSchemaValidateCommand:
    """Test `dtr schema validate` via CLI end-to-end."""

    def test_passes_good_html_file(self, tmp_path: Path):
        f = tmp_path / "report.html"
        f.write_text(GOOD_HTML, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f)])

        assert result.exit_code == 0, result.stdout
        assert "PASS" in result.stdout

    def test_fails_html_missing_title(self, tmp_path: Path):
        f = tmp_path / "report.html"
        f.write_text(HTML_NO_TITLE, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f)])

        assert result.exit_code != 0
        assert "FAIL" in result.stdout

    def test_fails_html_missing_body(self, tmp_path: Path):
        f = tmp_path / "report.html"
        f.write_text(HTML_NO_BODY, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f)])

        assert result.exit_code != 0
        assert "FAIL" in result.stdout

    def test_warns_html_no_h1(self, tmp_path: Path):
        f = tmp_path / "report.html"
        f.write_text(HTML_NO_H1, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f)])

        # Should pass (only a warning, not an error)
        assert result.exit_code == 0, result.stdout
        assert "WARN" in result.stdout

    def test_strict_mode_fails_on_warning(self, tmp_path: Path):
        f = tmp_path / "report.html"
        f.write_text(HTML_NO_H1, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f), "--strict"])

        assert result.exit_code != 0
        assert "FAIL" in result.stdout

    def test_passes_good_json_file(self, tmp_path: Path):
        f = tmp_path / "data.json"
        f.write_text(GOOD_JSON, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f)])

        assert result.exit_code == 0, result.stdout
        assert "PASS" in result.stdout

    def test_fails_json_missing_sections(self, tmp_path: Path):
        f = tmp_path / "data.json"
        f.write_text(JSON_MISSING_SECTIONS, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f)])

        assert result.exit_code != 0
        assert "FAIL" in result.stdout

    def test_warns_json_empty_sections(self, tmp_path: Path):
        f = tmp_path / "data.json"
        f.write_text(JSON_EMPTY_SECTIONS, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f)])

        assert result.exit_code == 0, result.stdout
        assert "WARN" in result.stdout

    def test_strict_fails_on_json_empty_sections(self, tmp_path: Path):
        f = tmp_path / "data.json"
        f.write_text(JSON_EMPTY_SECTIONS, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f), "--strict"])

        assert result.exit_code != 0

    def test_passes_good_markdown_file(self, tmp_path: Path):
        f = tmp_path / "guide.md"
        f.write_text(GOOD_MD, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f)])

        assert result.exit_code == 0, result.stdout
        assert "PASS" in result.stdout

    def test_fails_markdown_no_headings(self, tmp_path: Path):
        f = tmp_path / "guide.md"
        f.write_text(MD_NO_HEADINGS, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f)])

        assert result.exit_code != 0
        assert "FAIL" in result.stdout

    def test_warns_markdown_skipped_level(self, tmp_path: Path):
        f = tmp_path / "guide.md"
        f.write_text(MD_SKIPS_LEVEL, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f)])

        assert result.exit_code == 0, result.stdout
        assert "WARN" in result.stdout

    def test_auto_detects_format_from_extension(self, tmp_path: Path):
        html_file = tmp_path / "page.html"
        html_file.write_text(GOOD_HTML, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(html_file)])

        assert result.exit_code == 0, result.stdout
        assert "html" in result.stdout

    def test_explicit_format_overrides_extension(self, tmp_path: Path):
        # Name as .txt but content is Markdown; force format=md
        f = tmp_path / "doc.txt"
        f.write_text(GOOD_MD, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f), "--format", "md"])

        assert result.exit_code == 0, result.stdout
        assert "PASS" in result.stdout

    def test_validate_directory_checks_multiple_files(self, tmp_path: Path):
        (tmp_path / "a.html").write_text(GOOD_HTML, encoding="utf-8")
        (tmp_path / "b.json").write_text(GOOD_JSON, encoding="utf-8")
        (tmp_path / "c.md").write_text(GOOD_MD, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(tmp_path)])

        assert result.exit_code == 0, result.stdout
        assert "a.html" in result.stdout
        assert "b.json" in result.stdout
        assert "c.md" in result.stdout

    def test_validate_directory_fails_if_any_file_fails(self, tmp_path: Path):
        (tmp_path / "good.html").write_text(GOOD_HTML, encoding="utf-8")
        (tmp_path / "bad.json").write_text(JSON_MISSING_SECTIONS, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(tmp_path)])

        assert result.exit_code != 0
        assert "PASS" in result.stdout
        assert "FAIL" in result.stdout

    def test_skips_files_with_unknown_extension(self, tmp_path: Path):
        f = tmp_path / "archive.zip"
        f.write_bytes(b"PK")

        result = runner.invoke(app, ["schema", "validate", str(f)])

        assert result.exit_code == 0, result.stdout
        assert "SKIP" in result.stdout

    def test_fails_on_nonexistent_path(self, tmp_path: Path):
        missing = tmp_path / "nonexistent.html"

        result = runner.invoke(app, ["schema", "validate", str(missing)])

        assert result.exit_code != 0

    def test_invalid_format_option_exits_nonzero(self, tmp_path: Path):
        f = tmp_path / "file.html"
        f.write_text(GOOD_HTML, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(f), "--format", "xml"])

        assert result.exit_code != 0

    def test_summary_line_shows_file_count(self, tmp_path: Path):
        (tmp_path / "a.html").write_text(GOOD_HTML, encoding="utf-8")
        (tmp_path / "b.md").write_text(GOOD_MD, encoding="utf-8")

        result = runner.invoke(app, ["schema", "validate", str(tmp_path)])

        assert "2 file(s)" in result.stdout


# ===========================================================================
# Integration tests: `dtr schema generate`
# ===========================================================================


class TestSchemaGenerateCommand:
    """Test `dtr schema generate` via CLI end-to-end."""

    def _populate_export_dir(self, base: Path) -> Path:
        """Create a minimal DTR export directory with all three file types."""
        (base / "report.html").write_text(GOOD_HTML, encoding="utf-8")
        (base / "data.json").write_text(GOOD_JSON, encoding="utf-8")
        (base / "guide.md").write_text(GOOD_MD, encoding="utf-8")
        return base

    def test_creates_schema_file_by_default(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)

        result = runner.invoke(app, ["schema", "generate", str(tmp_path)])

        assert result.exit_code == 0, result.stdout
        schema_file = tmp_path / ".dtr-schema.json"
        assert schema_file.exists(), ".dtr-schema.json was not created"

    def test_schema_is_valid_json(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)
        runner.invoke(app, ["schema", "generate", str(tmp_path)])
        schema_file = tmp_path / ".dtr-schema.json"
        data = json.loads(schema_file.read_text(encoding="utf-8"))
        assert isinstance(data, dict)

    def test_schema_contains_expected_top_level_keys(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)
        runner.invoke(app, ["schema", "generate", str(tmp_path)])
        data = json.loads((tmp_path / ".dtr-schema.json").read_text())
        assert "$schema" in data
        assert "file_counts" in data
        assert "html_structure" in data
        assert "json_structure" in data
        assert "markdown_structure" in data

    def test_schema_file_counts_are_correct(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)
        runner.invoke(app, ["schema", "generate", str(tmp_path)])
        data = json.loads((tmp_path / ".dtr-schema.json").read_text())
        assert data["file_counts"]["html"] == 1
        assert data["file_counts"]["json"] == 1
        assert data["file_counts"]["markdown"] == 1

    def test_schema_html_structure_has_file_entry(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)
        runner.invoke(app, ["schema", "generate", str(tmp_path)])
        data = json.loads((tmp_path / ".dtr-schema.json").read_text())
        html_entries = data["html_structure"]
        assert len(html_entries) == 1
        assert html_entries[0]["file"] == "report.html"
        assert html_entries[0]["title"] == "DTR Report"

    def test_schema_json_structure_has_section_types(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)
        runner.invoke(app, ["schema", "generate", str(tmp_path)])
        data = json.loads((tmp_path / ".dtr-schema.json").read_text())
        json_entries = data["json_structure"]
        assert len(json_entries) == 1
        assert "paragraph" in json_entries[0]["section_types"]

    def test_schema_includes_observed_section_types(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)
        runner.invoke(app, ["schema", "generate", str(tmp_path)])
        data = json.loads((tmp_path / ".dtr-schema.json").read_text())
        assert "observed_section_types" in data
        assert "paragraph" in data["observed_section_types"]

    def test_schema_markdown_structure_has_heading_count(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)
        runner.invoke(app, ["schema", "generate", str(tmp_path)])
        data = json.loads((tmp_path / ".dtr-schema.json").read_text())
        md_entries = data["markdown_structure"]
        assert len(md_entries) == 1
        assert md_entries[0]["heading_count"] >= 4

    def test_custom_output_path(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)
        out = tmp_path / "custom-schema.json"

        result = runner.invoke(
            app, ["schema", "generate", str(tmp_path), "--output", str(out)]
        )

        assert result.exit_code == 0, result.stdout
        assert out.exists(), "Custom output file was not created"

    def test_pretty_flag_produces_indented_json(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)
        runner.invoke(app, ["schema", "generate", str(tmp_path), "--pretty"])
        raw = (tmp_path / ".dtr-schema.json").read_text(encoding="utf-8")
        # Indented JSON has newlines
        assert "\n" in raw

    def test_no_pretty_flag_produces_compact_json(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)
        out = tmp_path / "compact.json"
        runner.invoke(
            app,
            ["schema", "generate", str(tmp_path), "--no-pretty", "--output", str(out)],
        )
        raw = out.read_text(encoding="utf-8")
        # Compact JSON has no indentation (no leading spaces)
        assert "  " not in raw

    def test_generate_succeeds_on_empty_directory(self, tmp_path: Path):
        result = runner.invoke(app, ["schema", "generate", str(tmp_path)])

        assert result.exit_code == 0, result.stdout
        schema_file = tmp_path / ".dtr-schema.json"
        assert schema_file.exists()
        data = json.loads(schema_file.read_text())
        assert data["file_counts"]["html"] == 0
        assert data["file_counts"]["json"] == 0
        assert data["file_counts"]["markdown"] == 0

    def test_generate_excludes_existing_schema_file_from_json_analysis(self, tmp_path: Path):
        # Pre-populate a .dtr-schema.json so it would be found as a .json file
        (tmp_path / ".dtr-schema.json").write_text(
            json.dumps({"$schema": "previous"}), encoding="utf-8"
        )
        (tmp_path / "data.json").write_text(GOOD_JSON, encoding="utf-8")

        result = runner.invoke(app, ["schema", "generate", str(tmp_path)])

        assert result.exit_code == 0, result.stdout
        data = json.loads((tmp_path / ".dtr-schema.json").read_text())
        # Only data.json should be counted, not .dtr-schema.json
        assert data["file_counts"]["json"] == 1

    def test_fails_on_nonexistent_directory(self, tmp_path: Path):
        missing = tmp_path / "no_such_dir"

        result = runner.invoke(app, ["schema", "generate", str(missing)])

        assert result.exit_code != 0

    def test_fails_when_path_is_a_file(self, tmp_path: Path):
        f = tmp_path / "file.html"
        f.write_text(GOOD_HTML, encoding="utf-8")

        result = runner.invoke(app, ["schema", "generate", str(f)])

        assert result.exit_code != 0

    def test_output_reports_file_type_counts(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)

        result = runner.invoke(app, ["schema", "generate", str(tmp_path)])

        assert result.exit_code == 0, result.stdout
        assert "HTML: 1" in result.stdout
        assert "JSON: 1" in result.stdout
        assert "Markdown: 1" in result.stdout

    def test_schema_generated_from_field_matches_export_dir(self, tmp_path: Path):
        self._populate_export_dir(tmp_path)
        runner.invoke(app, ["schema", "generate", str(tmp_path)])
        data = json.loads((tmp_path / ".dtr-schema.json").read_text())
        assert str(tmp_path) in data["generated_from"]
