"""Initialize a new DTR documentation test.

Provides `dtr init` to scaffold new DTR test files with boilerplate.

Usage:
    dtr init MyFeatureDocTest                    # Create test in current module
    dtr init MyFeatureDocTest --module dtr-core  # Specify module
    dtr init MyFeatureDocTest --package com.example.docs  # Custom package
"""

from pathlib import Path
from typing import Optional

import typer
from rich.console import Console

console = Console()
app = typer.Typer(
    help="Initialize new DTR documentation tests",
    invoke_without_command=True,
    no_args_is_help=False,
)

JAVA_TEST_TEMPLATE = '''package {package};

import io.github.seanchatmangpt.dtr.junit5.DocTesterContext;
import io.github.seanchatmangpt.dtr.junit5.DocTesterExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.List;
import java.util.Map;

/**
 * {description}
 *
 * <p>Generated by: dtr init {class_name}</p>
 */
@ExtendWith(DocTesterExtension.class)
class {class_name} {{

    @Test
    void testDocumentation(DocTesterContext ctx) {{
        ctx.sayNextSection("{title}");
        ctx.say("This documentation was generated using DTR (Document Testing Runtime).");

        ctx.sayNextSection("Overview");
        ctx.say("Add your documentation content here.");
        ctx.sayUnorderedList(List.of(
            "Feature 1: Describe your first feature",
            "Feature 2: Describe your second feature",
            "Feature 3: Describe your third feature"
        ));

        ctx.sayNextSection("Example Code");
        ctx.sayCode("""
            // Add your example code here
            var result = myService.doSomething();
            System.out.println(result);
            """, "java");

        ctx.sayNextSection("Configuration");
        ctx.sayKeyValue(Map.of(
            "Setting", "Value",
            "timeout", "30s",
            "retries", "3"
        ));

        ctx.sayNote("Remember to replace this boilerplate with your actual documentation.");
    }}
}}
'''


@app.callback(invoke_without_command=True)
def init_command(
    class_name: str = typer.Argument(
        ...,
        help="Name of the test class to create (e.g., MyFeatureDocTest)",
    ),
    module: str = typer.Option(
        "dtr-integration-test",
        "--module",
        "-m",
        help="Maven module to create the test in",
    ),
    package: str = typer.Option(
        "controllers",
        "--package",
        "-p",
        help="Java package name",
    ),
    description: str = typer.Option(
        "DTR documentation test",
        "--description",
        "-d",
        help="Description for the test class",
    ),
    project_dir: Path = typer.Option(
        Path.cwd(),
        "--project-dir",
        "-C",
        help="Maven project root directory",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing file",
    ),
) -> None:
    """Scaffold a new DTR documentation test.

    Creates a Java test class with DTR boilerplate code including
    sayNextSection, say, sayCode, sayTable, and other say* methods.

    Examples:

        Create a new test:
        $ dtr init MyFeatureDocTest

        In a specific module and package:
        $ dtr init ApiDocTest --module dtr-integration-test --package controllers

        With a description:
        $ dtr init SecurityDocTest -d "Security feature documentation"
    """
    # Validate class name
    if not class_name[0].isupper():
        console.print("[yellow]Warning: Class name should start with uppercase[/yellow]")

    if not class_name.endswith("DocTest") and not class_name.endswith("Test"):
        console.print("[yellow]Warning: Class name should end with 'DocTest' or 'Test'[/yellow]")

    # Build output path
    package_path = package.replace(".", "/")
    test_dir = project_dir / module / "src" / "test" / "java" / package_path
    test_file = test_dir / f"{class_name}.java"

    if test_file.exists() and not force:
        console.print(f"[red]File already exists: {test_file}[/red]")
        console.print("Use --force to overwrite.")
        raise typer.Exit(1)

    # Generate title from class name
    title = _class_name_to_title(class_name)

    # Render template
    content = JAVA_TEST_TEMPLATE.format(
        package=package,
        class_name=class_name,
        description=description,
        title=title,
    )

    # Create directory and write file
    test_dir.mkdir(parents=True, exist_ok=True)
    test_file.write_text(content, encoding="utf-8")

    console.print(f"[green]Created:[/green] {test_file}")
    console.print(f"[cyan]Package:[/cyan] {package}")
    console.print(f"[cyan]Module:[/cyan] {module}")
    console.print(f"\n[bold]Next steps:[/bold]")
    console.print(f"  1. Edit {test_file.name} with your documentation")
    console.print(f"  2. Run: dtr build --modules {module}")
    console.print(f"  3. Check output: target/docs/test-results/{class_name}.md")


def _class_name_to_title(class_name: str) -> str:
    """Convert CamelCase class name to a human-readable title.

    Examples:
        MyFeatureDocTest -> My Feature
        ApiControllerDocTest -> Api Controller
        SecurityTest -> Security
    """
    # Remove common suffixes
    name = class_name
    for suffix in ["DocTest", "Test"]:
        if name.endswith(suffix):
            name = name[: -len(suffix)]
            break

    # Split CamelCase
    import re

    words = re.findall(r"[A-Z][a-z]*|[a-z]+", name)
    return " ".join(words) if words else name
