"""Template command group for DTR CLI.

Provides `dtr template list`, `dtr template show`, and `dtr template apply`
to browse and apply pre-built DTR test templates.

Usage:
    dtr template list                              # Show all built-in templates
    dtr template show basic                        # Display Java source for 'basic'
    dtr template apply api --class-name ApiDocTest # Generate Java test from template
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Optional

import typer
from rich.console import Console
from rich.syntax import Syntax
from rich.table import Table

console = Console()
app = typer.Typer(
    help="Browse and apply DTR test templates",
    no_args_is_help=True,
)


# ---------------------------------------------------------------------------
# Built-in template definitions
# ---------------------------------------------------------------------------

TEMPLATE_BASIC = '''package {package};

import io.github.seanchatmangpt.dtr.junit5.DTRContext;
import io.github.seanchatmangpt.dtr.junit5.DTRExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.List;
import java.util.Map;

/**
 * {title} — generated by: dtr template apply basic
 */
@ExtendWith(DTRExtension.class)
class {class_name} {{

    @Test
    void testDocumentation(DTRContext ctx) {{
        ctx.sayNextSection("{title}");
        ctx.say("This documentation was generated using DTR (Document Testing Runtime).");

        ctx.sayNextSection("Overview");
        ctx.say("Describe the feature or component under documentation.");
        ctx.sayUnorderedList(List.of(
            "Feature 1: Describe your first feature",
            "Feature 2: Describe your second feature",
            "Feature 3: Describe your third feature"
        ));

        ctx.sayNextSection("Example Code");
        ctx.sayCode("""
            // Add your example code here
            var result = myService.doSomething();
            System.out.println(result);
            """, "java");

        ctx.sayNextSection("Configuration");
        ctx.sayKeyValue(Map.of(
            "setting", "value",
            "timeout", "30s",
            "retries", "3"
        ));

        ctx.sayNote("Replace this boilerplate with your actual documentation.");
    }}
}}
'''

TEMPLATE_API = '''package {package};

import io.github.seanchatmangpt.dtr.junit5.DTRContext;
import io.github.seanchatmangpt.dtr.junit5.DTRExtension;
import io.github.seanchatmangpt.dtr.Request;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.Map;

import static org.hamcrest.Matchers.is;

/**
 * {title} — REST API documentation test.
 *
 * <p>Generated by: dtr template apply api</p>
 */
@ExtendWith(DTRExtension.class)
class {class_name} {{

    private static final String BASE_URL = "http://localhost:8080";

    @Test
    void documentApi(DTRContext ctx) {{
        ctx.sayNextSection("{title}");
        ctx.say("REST API documentation generated with live HTTP calls.");

        ctx.sayNextSection("Authentication");
        ctx.say("All endpoints require a valid Bearer token in the Authorization header.");
        ctx.sayCode("""
            Authorization: Bearer <your-token>
            """, "http");

        ctx.sayNextSection("GET /api/resource");
        ctx.say("Retrieve a list of resources.");
        ctx.sayAndMakeRequest(Request.GET().url(BASE_URL + "/api/resource"));

        ctx.sayNextSection("POST /api/resource");
        ctx.say("Create a new resource.");
        ctx.sayCode("""
            {{
              "name": "example",
              "value": 42
            }}
            """, "json");

        ctx.sayNextSection("Response Codes");
        ctx.sayTable(new String[][]{{
            {{"Status", "Meaning"}},
            {{"200", "OK — request succeeded"}},
            {{"201", "Created — resource was created"}},
            {{"400", "Bad Request — invalid input"}},
            {{"401", "Unauthorized — missing or invalid token"}},
            {{"404", "Not Found — resource does not exist"}},
            {{"500", "Internal Server Error"}}
        }});

        ctx.sayWarning("All POST/PUT/DELETE endpoints require authentication.");
    }}
}}
'''

TEMPLATE_BENCHMARK = '''package {package};

import io.github.seanchatmangpt.dtr.junit5.DTRContext;
import io.github.seanchatmangpt.dtr.junit5.DTRExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.ArrayList;
import java.util.List;

/**
 * {title} — performance benchmark documentation.
 *
 * <p>Generated by: dtr template apply benchmark</p>
 */
@ExtendWith(DTRExtension.class)
class {class_name} {{

    private static final int WARMUP_ITERATIONS = 1_000;
    private static final int MEASURE_ITERATIONS = 10_000;

    @Test
    void documentBenchmark(DTRContext ctx) {{
        ctx.sayNextSection("{title}");
        ctx.say("Performance benchmarks measured on real hardware using System.nanoTime().");

        ctx.sayNextSection("Environment");
        ctx.sayKeyValue(java.util.Map.of(
            "Java", System.getProperty("java.version"),
            "OS", System.getProperty("os.name"),
            "Arch", System.getProperty("os.arch"),
            "CPUs", String.valueOf(Runtime.getRuntime().availableProcessors()),
            "Heap", Runtime.getRuntime().maxMemory() / (1024 * 1024) + " MB"
        ));

        ctx.sayNextSection("Benchmark Method");
        ctx.sayCode("""
            // Warm up JIT
            for (int i = 0; i < WARMUP_ITERATIONS; i++) {{
                target.operation();
            }}
            // Measure
            long start = System.nanoTime();
            for (int i = 0; i < MEASURE_ITERATIONS; i++) {{
                target.operation();
            }}
            long elapsed = System.nanoTime() - start;
            long avgNs = elapsed / MEASURE_ITERATIONS;
            """, "java");

        ctx.sayNextSection("Results");
        // TODO: Replace with real benchmark measurements
        List<String[]> rows = new ArrayList<>();
        rows.add(new String[]{{"Operation", "Avg (ns)", "Iterations", "Notes"}});
        rows.add(new String[]{{"placeholder.operation()", "0", String.valueOf(MEASURE_ITERATIONS), "Replace with real data"}});
        ctx.sayTable(rows.toArray(new String[0][]));

        ctx.sayNote("Benchmark: " + MEASURE_ITERATIONS + " iterations, " +
            WARMUP_ITERATIONS + " warmup. Java " + System.getProperty("java.version") + ".");
        ctx.sayWarning("Replace placeholder measurements with real System.nanoTime() results.");
    }}
}}
'''

TEMPLATE_TUTORIAL = '''package {package};

import io.github.seanchatmangpt.dtr.junit5.DTRContext;
import io.github.seanchatmangpt.dtr.junit5.DTRExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.List;

/**
 * {title} — step-by-step tutorial.
 *
 * <p>Generated by: dtr template apply tutorial</p>
 */
@ExtendWith(DTRExtension.class)
class {class_name} {{

    @Test
    void tutorial(DTRContext ctx) {{
        ctx.sayNextSection("{title}");
        ctx.say("This tutorial walks you through the process step by step.");

        ctx.sayNextSection("Prerequisites");
        ctx.say("Before you begin, ensure you have the following installed:");
        ctx.sayUnorderedList(List.of(
            "Java 26 or later",
            "Maven 4.0.0-rc-5 or later",
            "An IDE such as IntelliJ IDEA or VS Code"
        ));

        ctx.sayNextSection("Step 1: Set Up Your Project");
        ctx.say("Create a new Maven project and add the DTR dependency.");
        ctx.sayCode("""
            <dependency>
                <groupId>io.github.seanchatmangpt</groupId>
                <artifactId>dtr-core</artifactId>
                <version>2.5.0</version>
                <scope>test</scope>
            </dependency>
            """, "xml");

        ctx.sayNextSection("Step 2: Write Your First Test");
        ctx.say("Create a new test class extending DTRExtension.");
        ctx.sayCode("""
            @ExtendWith(DTRExtension.class)
            class GettingStartedDocTest {{
                @Test
                void helloWorld(DTRContext ctx) {{
                    ctx.sayNextSection("Hello, DTR!");
                    ctx.say("My first documentation test.");
                }}
            }}
            """, "java");

        ctx.sayNextSection("Step 3: Run and Review Output");
        ctx.say("Run the test with Maven and check the generated documentation.");
        ctx.sayCode("""
            mvn test -Dtest=GettingStartedDocTest
            cat target/docs/test-results/GettingStartedDocTest.md
            """, "bash");

        ctx.sayNextSection("Next Steps");
        ctx.sayOrderedList(List.of(
            "Explore the full say* API in the DTR documentation",
            "Add API documentation with sayAndMakeRequest()",
            "Integrate DTR output into your CI/CD pipeline"
        ));

        ctx.sayNote("Full API reference: https://github.com/seanchatmangpt/dtr");
    }}
}}
'''

TEMPLATE_CHANGELOG = '''package {package};

import io.github.seanchatmangpt.dtr.junit5.DTRContext;
import io.github.seanchatmangpt.dtr.junit5.DTRExtension;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

import java.util.List;

/**
 * {title} — release notes and changelog.
 *
 * <p>Generated by: dtr template apply changelog</p>
 */
@ExtendWith(DTRExtension.class)
class {class_name} {{

    @Test
    void documentChangelog(DTRContext ctx) {{
        ctx.sayNextSection("{title}");
        ctx.say("Release notes for all versions of this project.");

        ctx.sayNextSection("v2.0.0 — 2026-03-01");
        ctx.say("Major release with breaking changes.");
        ctx.sayUnorderedList(List.of(
            "BREAKING: Removed deprecated `sayRaw()` method — use `say()` instead",
            "NEW: Added `sayOrderedList()` for numbered lists",
            "NEW: Virtual thread support via Java 21+ structured concurrency",
            "FIX: LaTeX output no longer escapes underscores in code blocks",
            "PERF: Render pipeline is 2x faster with lazy section buffering"
        ));

        ctx.sayNextSection("v1.5.0 — 2026-01-15");
        ctx.say("Minor release with new features and bug fixes.");
        ctx.sayUnorderedList(List.of(
            "NEW: `sayJson()` now pretty-prints nested objects",
            "NEW: `--watch` mode for live documentation rebuilds",
            "FIX: HTML exporter no longer drops table headers",
            "FIX: PDF export respects custom page margins"
        ));

        ctx.sayNextSection("v1.0.0 — 2025-11-01");
        ctx.say("Initial public release.");
        ctx.sayUnorderedList(List.of(
            "Core say* API: say, sayCode, sayTable, sayJson, sayKeyValue",
            "Output formats: Markdown, HTML, LaTeX, JSON",
            "JUnit 5 integration via DTRExtension",
            "Maven plugin for CI/CD integration"
        ));

        ctx.sayNote("All versions follow semantic versioning (semver.org).");
    }}
}}
'''

# ---------------------------------------------------------------------------
# Registry: name -> (description, category, source)
# ---------------------------------------------------------------------------

TEMPLATES: dict[str, dict] = {
    "basic": {
        "description": "Simple documentation test with common say* methods",
        "category": "general",
        "source": TEMPLATE_BASIC,
    },
    "api": {
        "description": "REST API doc test with live HTTP calls and response tables",
        "category": "api",
        "source": TEMPLATE_API,
    },
    "benchmark": {
        "description": "Performance benchmark documentation with real measurements",
        "category": "performance",
        "source": TEMPLATE_BENCHMARK,
    },
    "tutorial": {
        "description": "Step-by-step tutorial with prerequisites and ordered steps",
        "category": "docs",
        "source": TEMPLATE_TUTORIAL,
    },
    "changelog": {
        "description": "Release notes template with versioned sections",
        "category": "docs",
        "source": TEMPLATE_CHANGELOG,
    },
}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _class_name_to_title(class_name: str) -> str:
    """Convert CamelCase class name to a human-readable title.

    Examples:
        MyFeatureDocTest -> My Feature
        ApiControllerDocTest -> Api Controller
        SecurityTest -> Security
    """
    name = class_name
    for suffix in ("DocTest", "Test"):
        if name.endswith(suffix):
            name = name[: -len(suffix)]
            break
    words = re.findall(r"[A-Z][a-z]*|[a-z]+", name)
    return " ".join(words) if words else name


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


@app.command("list")
def list_templates() -> None:
    """Show all available built-in DTR test templates."""
    table = Table(title="DTR Built-in Templates", show_lines=False)
    table.add_column("Name", style="bold cyan", no_wrap=True)
    table.add_column("Category", style="magenta")
    table.add_column("Description")

    for name, meta in TEMPLATES.items():
        table.add_row(name, meta["category"], meta["description"])

    console.print(table)
    console.print(
        f"\n[bold]Usage:[/bold] dtr template show [cyan]<name>[/cyan]  |  "
        f"dtr template apply [cyan]<name>[/cyan] --class-name [cyan]<ClassName>[/cyan]"
    )


@app.command("show")
def show_template(
    template_name: str = typer.Argument(
        ...,
        help="Name of the template to display (e.g. basic, api, benchmark)",
    ),
) -> None:
    """Display the full Java source code of a template with syntax highlighting."""
    if template_name not in TEMPLATES:
        console.print(f"[red]Unknown template:[/red] {template_name!r}")
        console.print(
            f"Available templates: {', '.join(TEMPLATES)}"
        )
        raise typer.Exit(1)

    meta = TEMPLATES[template_name]
    console.print(
        f"[bold cyan]{template_name}[/bold cyan]  "
        f"[magenta]{meta['category']}[/magenta]  — {meta['description']}\n"
    )
    syntax = Syntax(
        meta["source"].strip(),
        "java",
        theme="monokai",
        line_numbers=True,
    )
    console.print(syntax)


@app.command("apply")
def apply_template(
    template_name: str = typer.Argument(
        ...,
        help="Name of the template to apply (e.g. basic, api, benchmark)",
    ),
    class_name: str = typer.Option(
        ...,
        "--class-name",
        "-c",
        help="Name of the Java test class to create (e.g. MyApiDocTest)",
    ),
    module: str = typer.Option(
        "dtr-integration-test",
        "--module",
        "-m",
        help="Maven module to create the test in",
    ),
    package: str = typer.Option(
        "controllers",
        "--package",
        "-p",
        help="Java package name",
    ),
    project_dir: Path = typer.Option(
        Path.cwd(),
        "--project-dir",
        "-C",
        help="Maven project root directory",
    ),
    force: bool = typer.Option(
        False,
        "--force",
        "-f",
        help="Overwrite existing file without prompting",
    ),
) -> None:
    """Generate a Java test file from a built-in template.

    Examples:

        Apply the basic template:
        $ dtr template apply basic --class-name MyFeatureDocTest

        Apply the API template to a specific module:
        $ dtr template apply api --class-name PetsApiDocTest --module petstore-service

        Apply with custom package and force overwrite:
        $ dtr template apply tutorial --class-name GettingStartedDocTest \\
              --package com.example.docs --force
    """
    if template_name not in TEMPLATES:
        console.print(f"[red]Unknown template:[/red] {template_name!r}")
        console.print(f"Available templates: {', '.join(TEMPLATES)}")
        raise typer.Exit(1)

    if not class_name[0].isupper():
        console.print("[yellow]Warning: Class name should start with uppercase[/yellow]")

    if not class_name.endswith("DocTest") and not class_name.endswith("Test"):
        console.print("[yellow]Warning: Class name should end with 'DocTest' or 'Test'[/yellow]")

    # Build output path
    package_path = package.replace(".", "/")
    test_dir = project_dir / module / "src" / "test" / "java" / package_path
    test_file = test_dir / f"{class_name}.java"

    if test_file.exists() and not force:
        console.print(f"[red]File already exists:[/red] {test_file}")
        console.print("Use --force to overwrite.")
        raise typer.Exit(1)

    title = _class_name_to_title(class_name)
    source = TEMPLATES[template_name]["source"].format(
        package=package,
        class_name=class_name,
        title=title,
    )

    test_dir.mkdir(parents=True, exist_ok=True)
    test_file.write_text(source, encoding="utf-8")

    console.print(f"[green]Created:[/green] {test_file}")
    console.print(f"[cyan]Template:[/cyan] {template_name}")
    console.print(f"[cyan]Package:[/cyan]  {package}")
    console.print(f"[cyan]Module:[/cyan]   {module}")
    console.print(f"\n[bold]Next steps:[/bold]")
    console.print(f"  1. Edit {test_file.name} with your content")
    console.print(f"  2. Run: dtr build --modules {module}")
    console.print(f"  3. Check output: target/docs/test-results/{class_name}.md")
