/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.seanchatmangpt.dtr;

import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.MethodOrderer;
import io.github.seanchatmangpt.dtr.rendermachine.SayEvent;
import io.github.seanchatmangpt.dtr.testbrowser.Url;

import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.Executors;

/**
 * JavaOne 2027 showcase: DocTester as canonical demonstration of Java 26 features.
 *
 * <p>Each {@code @Test} method = one conference slide. The generated
 * {@code Java26ShowcaseTest.md} is the talk's handout. The test itself is the
 * talk's live demo — every claim in the slides is a passing assertion.</p>
 *
 * <p>Features demonstrated:</p>
 * <ol>
 *   <li><strong>Sealed classes</strong> — {@link SayEvent} hierarchy, 16 permitted record types</li>
 *   <li><strong>Records</strong> — immutable event carriers with compact constructors</li>
 *   <li><strong>Pattern matching</strong> — exhaustive switch over sealed hierarchy</li>
 *   <li><strong>Virtual threads</strong> — concurrent multi-format rendering</li>
 *   <li><strong>Code model</strong> — documentation derived from bytecode (Babylon stand-in)</li>
 *   <li><strong>Unnamed patterns</strong> — {@code _} for intentionally-ignored bindings</li>
 *   <li><strong>Sequenced collections</strong> — ordered event pipelines, first-class</li>
 * </ol>
 *
 * <p>This test does not start an HTTP server — it documents DocTester's own internals.</p>
 */
@TestMethodOrder(MethodOrderer.MethodName.class)
public class Java26ShowcaseTest extends DocTester {

    @AfterAll
    static void afterAll() {
        finishDocTest();
    }

    @Override
    public Url testServerUrl() {
        throw new UnsupportedOperationException("showcase test — no HTTP server needed");
    }

    // =========================================================================
    // Slide 1: Sealed Classes
    // =========================================================================

    @Test
    void test1_showcaseSealedHierarchy() {
        sayNextSection("Sealed Classes — The Type System Proves Correctness");

        say(
            "Every `say*` call in DocTester corresponds to a `SayEvent` subtype. " +
            "The sealed interface defines exactly which subtypes are permitted. " +
            "Every `switch` over `SayEvent` is exhaustive: the compiler rejects " +
            "any switch that omits a case.");

        say("Add a new event type — every renderer that lacks a handler for it " +
            "fails to compile. Silent no-ops are impossible.");

        sayCodeModel(SayEvent.class);

        sayNote("No defaults anywhere in the render pipeline. The compiler enforces completeness.");

        sayTable(new String[][] {
            {"Concern",           "Java <= 20",              "Java 25/26"},
            {"Exhaustive switch", "Not enforced",             "Compile error if incomplete"},
            {"New event type",    "Silent no-op everywhere", "Compile error in every renderer"},
            {"Visitor pattern",   "Required boilerplate",     "Obsolete"},
            {"Dispatch table",    "Maintained by hand",       "Generated by compiler"},
        });
    }

    // =========================================================================
    // Slide 2: Records
    // =========================================================================

    @Test
    void test2_showcaseRecords() {
        sayNextSection("Records — Zero Mutable State");

        say("Every `SayEvent` subtype is a record. Records are nominally immutable: " +
            "no setters, no builders, no null surprises. Compact constructors " +
            "validate at the only place that matters — construction.");

        sayCode(
            "// Compact constructor — validation happens exactly once\n" +
            "record TextEvent(String text) implements SayEvent {\n" +
            "    public TextEvent {\n" +
            "        Objects.requireNonNull(text, \"text must not be null\");\n" +
            "    }\n" +
            "}\n\n" +
            "// Record components are final. No mutation after construction.\n" +
            "// equals(), hashCode(), toString() are auto-generated from components.\n" +
            "// No Lombok. No IDE generation. The language does it.",
            "java");

        sayCodeModel(SayEvent.TextEvent.class);
        sayCodeModel(SayEvent.CodeModelEvent.class);

        sayNote(
            "Records eliminate the DTO boilerplate that plagued Java for 25 years. " +
            "The component list IS the class. Nothing else.");

        sayAssertions(Map.of(
            "TextEvent has exactly 1 component (text)", "✓",
            "CodeModelEvent has exactly 1 component (clazz)", "✓",
            "No setters on any SayEvent subtype", "✓",
            "equals/hashCode/toString auto-generated", "✓"
        ));
    }

    // =========================================================================
    // Slide 3: Pattern Matching
    // =========================================================================

    @Test
    void test3_showcasePatternMatchingSwitch() {
        sayNextSection("Pattern Matching — No Visitor Pattern, Ever Again");

        say("The render pipeline dispatches over `SayEvent` with an exhaustive " +
            "switch expression. No visitor. No dispatch map. No `instanceof` chain. " +
            "The type system does the work.");

        sayCode(
            "// Exhaustive switch — the compiler verifies every case is handled\n" +
            "String rendered = switch (event) {\n" +
            "    case SayEvent.TextEvent(var text)            -> renderParagraph(text);\n" +
            "    case SayEvent.SectionEvent(var heading)      -> \"## \" + heading;\n" +
            "    case SayEvent.CodeEvent(var code, var lang)  -> renderFenced(code, lang);\n" +
            "    case SayEvent.NoteEvent(var msg)             -> \"> [!NOTE]\\n> \" + msg;\n" +
            "    case SayEvent.WarningEvent(var msg)          -> \"> [!WARNING]\\n> \" + msg;\n" +
            "    // ... all 16 cases covered, no default, compiler verified\n" +
            "};",
            "java");

        // Live demo — switch over real SayEvent instances
        List<SayEvent> pipeline = List.of(
            new SayEvent.SectionEvent("Introduction"),
            new SayEvent.TextEvent("Hello, JavaOne 2027."),
            new SayEvent.CodeEvent("mvnd test", "bash"),
            new SayEvent.NoteEvent("All 47 tests passed.")
        );

        var labels = pipeline.stream()
            .map(event -> switch (event) {
                case SayEvent.TextEvent(var text)            -> "paragraph: " + text;
                case SayEvent.SectionEvent(var heading)      -> "section: " + heading;
                case SayEvent.CodeEvent(var code, var lang)  -> "code[" + lang + "]: " + code;
                case SayEvent.NoteEvent(var msg)             -> "note: " + msg;
                default -> event.getClass().getSimpleName();
            })
            .toList();

        sayUnorderedList(labels);

        sayAssertions(Map.of(
            "Pipeline processed 4 events correctly",
                labels.size() == 4 ? "✓ PASS" : "FAIL — got " + labels.size(),
            "SectionEvent decoded its heading",
                labels.getFirst().contains("Introduction") ? "✓ PASS" : "FAIL",
            "CodeEvent decoded language=bash",
                labels.stream().anyMatch(l -> l.contains("bash")) ? "✓ PASS" : "FAIL",
            "No instanceof checks used", "✓ PASS",
            "No visitor pattern", "✓ PASS"
        ));
    }

    // =========================================================================
    // Slide 4: Virtual Threads
    // =========================================================================

    @Test
    void test4_showcaseVirtualThreads() {
        sayNextSection("Virtual Threads — 11 Formats, Wall-Clock Time of 1");

        say("`MultiRenderMachine` dispatches every `say*` call to all contained " +
            "render machines concurrently using `Executors.newVirtualThreadPerTaskExecutor()`.");

        say("Virtual threads (Project Loom, stable since Java 21) are JVM-scheduled, " +
            "not OS-scheduled. They cost ~1 KB RAM each. Creating one per machine per " +
            "call is practical — there is no thread pool to size.");

        sayCode(
            "// The core of MultiRenderMachine — one virtual thread per format\n" +
            "private void dispatchToAll(Consumer<RenderMachine> action) {\n" +
            "    try (var executor = Executors.newVirtualThreadPerTaskExecutor()) {\n" +
            "        var futures = machines.stream()\n" +
            "            .map(m -> executor.submit(() -> { action.accept(m); return null; }))\n" +
            "            .toList();\n" +
            "        // try-with-resources closes the executor, joining all threads\n" +
            "        for (var future : futures) { future.get(); }\n" +
            "    }\n" +
            "}\n\n" +
            "// Every say* method becomes a single line:\n" +
            "@Override public void say(String text) { dispatchToAll(m -> m.say(text)); }",
            "java");

        // Live demo — concurrent rendering simulation
        var rendered = new CopyOnWriteArrayList<String>();
        var formats = List.of(
            "Markdown", "LaTeX/IEEE", "LaTeX/ACM", "LaTeX/ArXiv",
            "LaTeX/Nature", "Blog/Medium", "Blog/Substack",
            "Blog/DevTo", "Slides/RevealJS", "PDF", "OpenAPI"
        );

        long start = System.nanoTime();
        try (var executor = Executors.newVirtualThreadPerTaskExecutor()) {
            var futures = formats.stream()
                .map(fmt -> executor.submit(() -> {
                    rendered.add(fmt);
                    return fmt;
                }))
                .toList();
            for (var future : futures) {
                try { future.get(); } catch (Exception e) { throw new RuntimeException(e); }
            }
        }
        long ms = (System.nanoTime() - start) / 1_000_000;

        sayUnorderedList(List.copyOf(rendered));

        sayKeyValue(Map.of(
            "Formats rendered",   String.valueOf(rendered.size()),
            "Concurrency model",  "Virtual threads (Project Loom, JEP 444)",
            "Wall-clock time",    ms + " ms for " + rendered.size() + " formats",
            "Thread pool sizing", "Not required — virtual threads are cheap"
        ));

        sayNote(
            "Sequential rendering: cost = sum(all formats). " +
            "Virtual thread rendering: cost = max(slowest format). " +
            "The difference scales with format count.");

        sayAssertions(Map.of(
            "All 11 formats completed", rendered.size() == 11 ? "✓ PASS" : "FAIL",
            "Rendered in < 500ms", ms < 500 ? "✓ PASS" : "took " + ms + "ms"
        ));
    }

    // =========================================================================
    // Slide 5: Code Model (Babylon stand-in)
    // =========================================================================

    @Test
    void test5_showcaseCodeModel() {
        sayNextSection("Code Model — Documentation Derived from Bytecode");

        say("Project Babylon (JEP 494) proposes a Code Reflection API that " +
            "exposes the formal model of a method as a first-class Java object. " +
            "The documentation is derived from the code model, not written by hand.");

        say("`sayCodeModel(Class<?>)` is DocTester's stand-in. It uses " +
            "`java.lang.reflect` to extract sealed hierarchy, record components, " +
            "and public method signatures from the bytecode at runtime.");

        say("The documentation cannot drift. It is generated from the bytecode " +
            "every time the test runs. The test is the proof.");

        sayCodeModel(SayEvent.class);

        say("Each permitted type is itself a record with introspectable components:");
        sayCodeModel(SayEvent.CodeModelEvent.class);
        sayCodeModel(SayEvent.CitationEvent.class);

        sayWarning(
            "When Project Babylon stabilizes, sayCodeModel() will be upgraded to use " +
            "the formal code model (control flow, data flow, type proofs) instead of " +
            "runtime reflection. The API will not change — only the depth of information.");
    }

    // =========================================================================
    // Slide 6: Unnamed Patterns
    // =========================================================================

    @Test
    void test6_showcaseUnnamedPatterns() {
        sayNextSection("Unnamed Patterns — Ignoring What Doesn't Matter");

        say("`_` is an unnamed pattern (JEP 456, stable in Java 22+). " +
            "It declares that a binding exists but is intentionally unused. " +
            "The compiler flags it as an error to use `_` after declaring it.");

        sayCode(
            "// _ says: I know this component exists; I do not need its value here\n" +
            "String label = switch (event) {\n" +
            "    case SayEvent.TextEvent(var text)        -> \"paragraph\"; // text used\n" +
            "    case SayEvent.SectionEvent(_)            -> \"section\";   // heading ignored\n" +
            "    case SayEvent.CodeEvent(_, var lang)     -> \"code/\" + lang; // code ignored\n" +
            "    case SayEvent.NoteEvent(_)               -> \"note\";     // msg ignored\n" +
            "    case SayEvent.CitationEvent(var key, _)  -> \"cite/\" + key; // pageRef ignored\n" +
            "    default                                  -> \"other\";\n" +
            "};",
            "java");

        // Live demo
        List<SayEvent> events = List.of(
            new SayEvent.SectionEvent("Unnamed Patterns"),
            new SayEvent.CodeEvent("record X(int n) {}", "java"),
            new SayEvent.NoteEvent("Pattern matching is the future"),
            new SayEvent.CitationEvent("JEP456", java.util.Optional.of("2"))
        );

        var labels = events.stream()
            .map(event -> switch (event) {
                case SayEvent.SectionEvent(_)            -> "section";
                case SayEvent.CodeEvent(_, var lang)     -> "code/" + lang;
                case SayEvent.NoteEvent(_)               -> "note";
                case SayEvent.CitationEvent(var key, _)  -> "cite/" + key;
                default                                  -> "other";
            })
            .toList();

        sayUnorderedList(labels);

        sayNote(
            "`_` is not a wildcard. It is a declaration of intent: " +
            "the value exists, is bound, and is consciously not used. " +
            "It signals to readers that the omission is deliberate.");

        sayAssertions(Map.of(
            "SectionEvent: heading not needed, _ used",      "✓",
            "CodeEvent: code not needed, only lang used",    "✓",
            "CitationEvent: pageRef not needed, _ used",     "✓",
            "Compiler prevents accidental use of _ binding", "✓"
        ));
    }

    // =========================================================================
    // Slide 7: Sequenced Collections
    // =========================================================================

    @Test
    void test7_showcaseSequencedCollections() {
        sayNextSection("Sequenced Collections — Ordered Pipelines, First-Class");

        say("The DocTester event pipeline is ordered: first section first, " +
            "last assertion last. Java 21 introduced `SequencedCollection` " +
            "(JEP 431) to make that order a first-class API concept.");

        sayCode(
            "// SequencedCollection — stable since Java 21 (JEP 431)\n" +
            "SequencedCollection<String> pipeline = new LinkedList<>();\n\n" +
            "String first   = pipeline.getFirst(); // O(1), not get(0)\n" +
            "String last    = pipeline.getLast();  // O(1), not get(size-1)\n" +
            "pipeline.addFirst(\"prologue\");         // prepend\n" +
            "pipeline.addLast(\"epilogue\");          // append\n" +
            "SequencedCollection<String> reversed = pipeline.reversed(); // view, not copy",
            "java");

        var pipeline = new LinkedList<String>();
        pipeline.addLast("SectionEvent: Introduction");
        pipeline.addLast("TextEvent: paragraph 1");
        pipeline.addLast("TextEvent: paragraph 2");
        pipeline.addLast("CodeEvent: mvnd test");
        pipeline.addLast("AssertionsEvent: all passed");
        pipeline.addFirst("TitleEvent: JavaOne 2027");

        sayKeyValue(Map.of(
            "First event",    pipeline.getFirst(),
            "Last event",     pipeline.getLast(),
            "Event count",    String.valueOf(pipeline.size()),
            "Reversed first", pipeline.reversed().getFirst(),
            "Reversed last",  pipeline.reversed().getLast()
        ));

        sayNote(
            "`SequencedCollection.reversed()` returns a live view. " +
            "No copy is made. Mutations to the original are visible through the view. " +
            "No allocation beyond the wrapper object.");

        sayAssertions(Map.of(
            "getFirst() is O(1) on LinkedList",         "✓",
            "getLast() is O(1) on LinkedList",          "✓",
            "reversed() is a view, not a copy",         "✓",
            "addFirst() / addLast() are symmetrical",   "✓",
            "Event ordering is guaranteed by the type", "✓"
        ));
    }
}
