/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package com.example.docs;

import io.github.seanchatmangpt.dtr.DocDescription;
import io.github.seanchatmangpt.dtr.DocSection;
import io.github.seanchatmangpt.dtr.DtrTest;
import io.github.seanchatmangpt.dtr.junit5.DtrExtension;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.junit.jupiter.api.extension.ExtendWith;

/**
 * Generated by ggen-cli from ontology/dtr-spec.ttl.
 *
 * <p>This documentation test was scaffolded automatically. Each {@code @Test} method
 * corresponds to a {@code dtr:DocSection} in the ontology. Fill in the say* calls
 * below to document your feature, then run {@code mvnd verify} to produce
 * {@code target/docs/MyFeatureDocTest.md}.</p>
 *
 * <p>Regenerate at any time: {@code ggen sync} (idempotent — safe to re-run).</p>
 */
@ExtendWith(DtrExtension.class)
@TestMethodOrder(MethodOrderer.MethodName.class)
public class MyFeatureDocTest extends DtrTest {

    // ── Section 1: Getting Started ──────────────────────────────────

    @Test
    @DocSection("Getting Started")
    @DocDescription({"Walk through the basic usage of MyFeature with a minimal example."})
    public void test01_getting_started() {
        say("Walk through the basic usage of MyFeature with a minimal example.");

        sayCode("""
                // TODO: add a representative code example
                """, "java");
    }

    // ── Section 2: Configuration Reference ──────────────────────────────────

    @Test
    @DocSection("Configuration Reference")
    @DocDescription({"Every configuration key with its type, default value, and description."})
    public void test02_configuration_reference() {
        say("Every configuration key with its type, default value, and description.");

        sayTable(new String[][]{
            {"Property",  "Type",    "Default", "Description"},
            {"TODO_key",  "string",  "—",       "TODO: describe this setting"}
        });

        sayNote("TODO: add a helpful note about this section.");
    }

    // ── Section 3: Advanced Patterns ──────────────────────────────────

    @Test
    @DocSection("Advanced Patterns")
    @DocDescription({"Edge cases, performance considerations, and production caveats."})
    public void test03_advanced_patterns() {
        say("Edge cases, performance considerations, and production caveats.");

        sayCode("""
                // TODO: add a representative code example
                """, "java");

        sayWarning("TODO: document edge cases or production caveats here.");
    }

    @AfterAll
    static void afterAll() {
        finishDocTest();
    }
}
