/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.seanchatmangpt.dtr.receipt;

import java.time.Instant;
import java.util.Map;

import io.github.seanchatmangpt.dtr.metadata.DocMetadata;

/**
 * Immutable blockchain-style receipt capturing content hash, metadata,
 * and chain linkage for document provenance verification.
 *
 * Every generated DocTest PDF contains its receipt proving that content
 * was derived from live execution. SHA3-256 hashing ensures integrity;
 * previous hash links create chronological chain.
 */
public record LockchainReceipt(
    String testClassName,
    String testMethodName,
    String contentHash,              // SHA3-256 of document
    String previousHash,             // Chain link to prior test
    Instant timestamp,               // When doc was generated
    DocMetadata metadata,            // Build/git context
    Map<String, String> fileHashes,  // Path → SHA3-256 for all outputs
    long testDurationMs,             // Execution time
    boolean allTestsPassed           // Integrity flag
) {

    /**
     * Colophon page text for human-readable receipt.
     *
     * Rendered as final page of PDF with document provenance.
     */
    public String toColophonText() {
        return """
            \\n
            \\vspace*{\\fill}

            \\begin{center}
            \\noindent\\rule{\\textwidth}{1pt}
            \\textbf{\\Large DOCUMENT PROVENANCE}
            \\noindent\\rule{\\textwidth}{1pt}
            \\end{center}

            \\small
            \\begin{tabular}{ll}
            \\textbf{Generated:} & %s \\\\
            \\textbf{Test:} & %s \\\\
            \\textbf{Test Method:} & %s \\\\
            \\textbf{Duration:} & %d ms \\\\
            \\textbf{Java:} & %s \\\\
            \\textbf{Maven:} & %s \\\\
            \\textbf{Git Commit:} & %s \\\\
            \\textbf{Git Branch:} & %s \\\\
            \\textbf{Git Author:} & %s \\\\
            \\textbf{Content Hash (SHA3-256):} & {\\small \\texttt{%s}} \\\\
            \\textbf{Previous Hash:} & {\\small \\texttt{%s}} \\\\
            \\textbf{All Tests Passed:} & %s \\\\
            \\end{tabular}

            \\vspace{0.5cm}

            \\noindent
            This document was generated by live execution of the described
            implementation using DTR 2.1.0. Content cannot deviate from
            observed behavior without invalidating the content hash.

            \\begin{center}
            \\textit{drift(A) = 0}
            \\end{center}

            \\vspace*{\\fill}
            """.formatted(
            timestamp.toString(),
            testClassName,
            testMethodName,
            testDurationMs,
            metadata.javaVersion(),
            metadata.mavenVersion(),
            truncateHash(metadata.gitCommit()),
            metadata.gitBranch(),
            metadata.gitAuthor(),
            truncateHash(contentHash),
            truncateHash(previousHash),
            allTestsPassed ? "YES" : "NO"
        );
    }

    /**
     * JSON representation for manifest.json and embedded XMP metadata.
     */
    public String toJson() {
        return String.format(
            """
            {
              "testClassName": "%s",
              "testMethodName": "%s",
              "contentHash": "%s",
              "previousHash": "%s",
              "timestamp": "%s",
              "testDurationMs": %d,
              "allTestsPassed": %s,
              "metadata": {
                "projectName": "%s",
                "projectVersion": "%s",
                "javaVersion": "%s",
                "mavenVersion": "%s",
                "gitCommit": "%s",
                "gitBranch": "%s",
                "gitAuthor": "%s",
                "buildHost": "%s"
              }
            }
            """,
            testClassName,
            testMethodName,
            contentHash,
            previousHash,
            timestamp.toString(),
            testDurationMs,
            allTestsPassed,
            metadata.projectName(),
            metadata.projectVersion(),
            metadata.javaVersion(),
            metadata.mavenVersion(),
            metadata.gitCommit(),
            metadata.gitBranch(),
            metadata.gitAuthor(),
            metadata.buildHost()
        );
    }

    /**
     * Truncate hash to first 16 characters for readability.
     */
    private static String truncateHash(String hash) {
        if (hash == null || hash.isEmpty()) {
            return "(unknown)";
        }
        if (hash.equals("0000000000000000000000000000000000000000") || hash.equals("unknown")) {
            return "(genesis)";
        }
        return hash.substring(0, Math.min(16, hash.length()));
    }
}
