/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package io.github.seanchatmangpt.dtr.jotp;

/**
 * Simple arithmetic operations expressed as pure functions over Java records.
 *
 * <p>Sourced from <a href="https://github.com/cchacin/java-maven-template">
 * cchacin/java-maven-template</a> and adapted for DTR's JOTP doctests.
 *
 * <p>Demonstrates Java 25 features:
 * <ul>
 *   <li>Records as concise, immutable value types</li>
 *   <li>Primitive field types ({@code int}, {@code long}) inside records</li>
 *   <li>Auto-generated {@code equals()}, {@code hashCode()}, {@code toString()}</li>
 *   <li>Compact accessor methods generated by the compiler</li>
 * </ul>
 */
public class Maths {

    /**
     * An immutable pair of {@code int} operands.
     *
     * @param x the first operand
     * @param y the second operand
     */
    public record Input(int x, int y) {}

    /**
     * An immutable result holding a {@code long} value.
     *
     * @param result the computed value
     */
    public record Output(long result) {}

    /**
     * Returns the sum of the two operands in {@code input} as a {@link Output}
     * with a {@code long} result to avoid integer overflow.
     *
     * @param input the two {@code int} operands
     * @return an {@link Output} whose {@code result} is {@code input.x() + input.y()}
     */
    public Output sum(final Input input) {
        return new Output((long) input.x() + input.y());
    }
}
