/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.r10r.doctester;

import com.google.common.base.Charsets;
import com.google.common.io.Files;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.util.regex.Pattern;

import static org.hamcrest.CoreMatchers.is;

/**
 * Comprehensive doctests for the DocTester annotation API.
 *
 * <p>Tests are organised in six layers of increasing depth:
 * <ol>
 *   <li><strong>Layer 1 — Individual annotations:</strong> each annotation in isolation</li>
 *   <li><strong>Layer 2 — Markdown structure:</strong> heading levels, anchor IDs, formatting</li>
 *   <li><strong>Layer 3 — Ordering guarantees:</strong> annotations always emit in section → description → note → warning → code order</li>
 *   <li><strong>Layer 4 — Interleaving:</strong> annotations coexist correctly with explicit {@code say*()} calls</li>
 *   <li><strong>Layer 5 — Edge cases:</strong> markdown-special characters, Unicode, multiple values, empty language hint</li>
 *   <li><strong>Layer 6 — Self-documentation:</strong> this class documents itself using all five annotation types</li>
 * </ol>
 *
 * <p>Each {@code @Test} method is also a living usage example; the markdown rendered
 * for this class is itself fully annotated using the API under test.
 */
public class AnnotationDocTest extends DocTester {

    /** Path to the markdown file generated by this test class. */
    private static final String MD_PATH =
            "docs/test/" + AnnotationDocTest.class.getName() + ".md";

    // =========================================================================
    // LAYER 1 — Individual annotations in isolation
    // =========================================================================

    @Test
    @DocSection("Layer 1 — @DocSection in isolation")
    @DocDescription("@DocSection adds an H1 heading entry to the document and to the left-hand TOC navbar.")
    @DocNote("This heading was produced entirely by the `@DocSection` annotation — no `sayNextSection()` call in the method body.")
    public void layer1_docSectionAlone() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("Layer 1 — @DocSection in isolation"),
                "@DocSection value appears in document body");
    }

    @Test
    @DocSection("Layer 1 — @DocDescription (single value)")
    @DocDescription("A single-string @DocDescription injects exactly one paragraph.")
    public void layer1_docDescriptionSingleValue() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("A single-string @DocDescription injects exactly one paragraph."),
                "Single @DocDescription value appears in markdown");
    }

    @Test
    @DocSection("Layer 1 — @DocDescription (multiple values)")
    @DocDescription({
        "First paragraph emitted by a multi-value @DocDescription.",
        "Second paragraph emitted by the same annotation.",
        "Third paragraph — each element becomes an independent paragraph."
    })
    public void layer1_docDescriptionMultipleValues() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("First paragraph emitted by a multi-value @DocDescription."), "First description paragraph present");
        Assertions.assertTrue(md.contains("Second paragraph emitted by the same annotation."), "Second description paragraph present");
        Assertions.assertTrue(md.contains("Third paragraph — each element becomes an independent paragraph."), "Third description paragraph present");
    }

    @Test
    @DocSection("Layer 1 — @DocNote (single value)")
    @DocNote("A single-string @DocNote renders one GitHub-flavored NOTE admonition.")
    public void layer1_docNoteSingleValue() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("A single-string @DocNote renders one GitHub-flavored NOTE admonition."),
                "@DocNote value appears in markdown");
        Assertions.assertTrue(md.contains("[!NOTE]"),
                "@DocNote uses GitHub-flavored NOTE admonition");
    }

    @Test
    @DocSection("Layer 1 — @DocNote (multiple values)")
    @DocNote({
        "First informational note.",
        "Second informational note."
    })
    public void layer1_docNoteMultipleValues() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("First informational note."), "First @DocNote value present");
        Assertions.assertTrue(md.contains("Second informational note."), "Second @DocNote value present");
    }

    @Test
    @DocSection("Layer 1 — @DocWarning (single value)")
    @DocWarning("A single-string @DocWarning renders one GitHub-flavored WARNING admonition.")
    public void layer1_docWarningSingleValue() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("A single-string @DocWarning renders one GitHub-flavored WARNING admonition."),
                "@DocWarning value appears in markdown");
        Assertions.assertTrue(md.contains("[!WARNING]"),
                "@DocWarning uses GitHub-flavored WARNING admonition");
    }

    @Test
    @DocSection("Layer 1 — @DocWarning (multiple values)")
    @DocWarning({
        "First warning message.",
        "Second warning message."
    })
    public void layer1_docWarningMultipleValues() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("First warning message."), "First @DocWarning present");
        Assertions.assertTrue(md.contains("Second warning message."), "Second @DocWarning present");
    }

    @Test
    @DocSection("Layer 1 — @DocCode (single line, no language)")
    @DocCode("Response response = sayAndMakeRequest(Request.GET().url(testServerUrl()));")
    public void layer1_docCodeSingleLineNoLanguage() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("Response response = sayAndMakeRequest(Request.GET().url(testServerUrl()));"),
                "@DocCode value appears in markdown");
        Assertions.assertTrue(md.contains("```"),
                "@DocCode rendered inside markdown code fence");
    }

    @Test
    @DocSection("Layer 1 — @DocCode (multi-line, with language)")
    @DocCode(
        language = "java",
        value = {
            "Request req = Request.POST()",
            "    .url(testServerUrl().path(\"/api/users\"))",
            "    .contentTypeApplicationJson()",
            "    .payload(new UserDto(\"alice\", \"alice@example.com\"));",
            "Response res = sayAndMakeRequest(req);"
        }
    )
    public void layer1_docCodeMultiLineWithLanguage() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("Request req = Request.POST()"), "First @DocCode line present");
        Assertions.assertTrue(md.contains("```java"),
                "language class emitted in markdown code fence");
    }

    // =========================================================================
    // =========================================================================
    // LAYER 3 — Ordering guarantees
    // =========================================================================

    @Test
    @DocSection("Layer 3 — section heading appears before description")
    @DocDescription("This description must appear after the H1 heading in the document.")
    public void layer3_sectionBeforeDescription() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        int sectionPos = md.indexOf("Layer 3 — section heading appears before description");
        int descPos    = md.indexOf("This description must appear after the H1 heading");
        Assertions.assertTrue(sectionPos < descPos,
                "Section heading index must be less than description index");
        Assertions.assertTrue(sectionPos > 0 && descPos > 0, "Both positions must be valid (content found)");
    }

    @Test
    @DocSection("Layer 3 — description appears before note")
    @DocDescription("Description paragraph must precede the info note.")
    @DocNote("Info note must follow the description.")
    public void layer3_descriptionBeforeNote() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        int descPos = md.indexOf("Description paragraph must precede the info note.");
        int notePos = md.indexOf("Info note must follow the description.");
        Assertions.assertTrue(descPos < notePos, "Description must appear before @DocNote");
    }

    @Test
    @DocSection("Layer 3 — note appears before warning")
    @DocNote("Info note must precede the warning.")
    @DocWarning("Warning must follow the info note.")
    public void layer3_noteBeforeWarning() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        int notePos    = md.indexOf("Info note must precede the warning.");
        int warningPos = md.indexOf("Warning must follow the info note.");
        Assertions.assertTrue(notePos < warningPos, "@DocNote must appear before @DocWarning");
    }

    @Test
    @DocSection("Layer 3 — warning appears before code")
    @DocWarning("Warning must precede the code block.")
    @DocCode("// code block must follow the warning")
    public void layer3_warningBeforeCode() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        int warningPos = md.indexOf("Warning must precede the code block.");
        int codePos    = md.indexOf("// code block must follow the warning");
        Assertions.assertTrue(warningPos < codePos, "@DocWarning must appear before @DocCode");
    }

    @Test
    @DocSection("Layer 3 — full pipeline order: section → desc → note → warning → code")
    @DocDescription("Narrative description in the middle of the pipeline.")
    @DocNote("Informational note after the description.")
    @DocWarning("Warning after the note.")
    @DocCode("// Code example at the end of the pipeline")
    public void layer3_fullPipelineOrder() throws IOException {
        finishDocTest();
        String md = readMarkdown();

        int sectionPos = md.indexOf("Layer 3 — full pipeline order");
        int descPos    = md.indexOf("Narrative description in the middle");
        int notePos    = md.indexOf("Informational note after the description.");
        int warnPos    = md.indexOf("Warning after the note.");
        int codePos    = md.indexOf("// Code example at the end");

        Assertions.assertTrue(sectionPos > 0 && descPos > 0 && notePos > 0 && warnPos > 0 && codePos > 0, "All five markers must be found");
        Assertions.assertTrue(sectionPos < descPos,    "section < desc");
        Assertions.assertTrue(descPos < notePos,       "desc < note");
        Assertions.assertTrue(notePos < warnPos,       "note < warning");
        Assertions.assertTrue(warnPos < codePos,       "warning < code");
    }

    // =========================================================================
    // LAYER 4 — Interleaving with explicit say*() calls
    // =========================================================================

    @Test
    @DocSection("Layer 4 — @DocSection then explicit say()")
    public void layer4_annotationThenExplicitSay() throws IOException {
        say("This paragraph was written with an explicit say() call after the annotation-driven heading.");
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("Layer 4 — @DocSection then explicit say()"),
                "Annotation-driven heading present");
        Assertions.assertTrue(md.contains("This paragraph was written with an explicit say() call"),
                "Explicit say() paragraph present");
    }

    @Test
    @DocSection("Layer 4 — explicit sayNextSection() before @DocSection annotation")
    public void layer4_explicitSayNextSectionThenAnnotation() throws IOException {
        // Explicit call runs BEFORE the annotation is processed (annotations run in @Before)
        // so the annotation heading was already emitted; calling sayNextSection explicitly
        // here adds a *second* heading in the document
        sayNextSection("Manually-added subsection within layer 4 test");
        say("Two section headings exist: one from the annotation, one from this explicit call.");
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("Layer 4 — explicit sayNextSection()"), "Annotation heading present");
        Assertions.assertTrue(md.contains("Manually-added subsection within layer 4 test"), "Explicit extra heading present");
    }

    @Test
    @DocSection("Layer 4 — @DocDescription with additional explicit say()")
    @DocDescription("Annotation-driven description paragraph.")
    public void layer4_annotationDescThenExplicitSay() throws IOException {
        say("Additional paragraph via explicit say() call.");
        finishDocTest();
        String md = readMarkdown();
        int annotationDescPos = md.indexOf("Annotation-driven description paragraph.");
        int explicitSayPos    = md.indexOf("Additional paragraph via explicit say() call.");
        Assertions.assertTrue(annotationDescPos > 0 && explicitSayPos > 0, "Both paragraphs present");
        Assertions.assertTrue(annotationDescPos < explicitSayPos,
                "Annotation description appears before explicit say()");
    }

    @Test
    @DocSection("Layer 4 — @DocNote alongside explicit sayRaw()")
    @DocNote("Annotation-driven info note.")
    public void layer4_annotationNoteThenExplicitSayRaw() throws IOException {
        sayRaw("> [!TIP]\n> Explicit sayRaw() success alert.");
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("Annotation-driven info note."), "Annotation note present");
        Assertions.assertTrue(md.contains("Explicit sayRaw() success alert."), "Explicit sayRaw() present");
    }

    @Test
    @DocSection("Layer 4 — @DocCode alongside explicit say() narrative")
    @DocCode(language = "http", value = {
        "GET /api/articles HTTP/1.1",
        "Host: localhost:8080",
        "Accept: application/json"
    })
    public void layer4_annotationCodeWithExplicitSay() throws IOException {
        say("The `@DocCode` block above was rendered by the annotation; this paragraph is from `say()`.");
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("GET /api/articles HTTP/1.1"), "HTTP code block present");
        Assertions.assertTrue(md.contains("```http"), "language-http code fence present");
        Assertions.assertTrue(md.contains("The `@DocCode` block above was rendered by the annotation"),
                "Explicit say() paragraph present");
    }

    // =========================================================================
    // LAYER 5 — Edge cases
    // =========================================================================

    @Test
    @DocSection("Layer 5 — special characters in @DocSection title")
    @DocDescription("The title contains em dashes, angle-bracket-like characters, and an ampersand: A & B.")
    public void layer5_specialCharsInSectionTitle() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("Layer 5 — special characters in @DocSection title"),
                "Section with special chars appears in markdown");
    }

    @Test
    @DocSection("Layer 5 — Unicode in @DocDescription")
    @DocDescription("Japanese: 日本語テスト. Arabic: مرحبا. Emoji context: résumé, naïve, façade.")
    public void layer5_unicodeInDescription() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        Assertions.assertTrue(md.contains("日本語テスト"),
                "Unicode description paragraph present");
        Assertions.assertTrue(md.contains("مرحبا"), "Arabic text present");
        Assertions.assertTrue(md.contains("résumé"), "Latin extended present");
    }

    @Test
    @DocSection("Layer 5 — many @DocDescription values (10 paragraphs)")
    @DocDescription({
        "Paragraph 1 of 10.",
        "Paragraph 2 of 10.",
        "Paragraph 3 of 10.",
        "Paragraph 4 of 10.",
        "Paragraph 5 of 10.",
        "Paragraph 6 of 10.",
        "Paragraph 7 of 10.",
        "Paragraph 8 of 10.",
        "Paragraph 9 of 10.",
        "Paragraph 10 of 10."
    })
    public void layer5_manyDescriptionValues() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        for (int i = 1; i <= 10; i++) {
            Assertions.assertTrue(md.contains("Paragraph " + i + " of 10."),
                    "Paragraph " + i + " present");
        }
    }

    @Test
    @DocSection("Layer 5 — many @DocWarning values (3 warnings)")
    @DocWarning({
        "Warning 1 of 3.",
        "Warning 2 of 3.",
        "Warning 3 of 3."
    })
    public void layer5_manyWarningValues() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        for (int i = 1; i <= 3; i++) {
            Assertions.assertTrue(md.contains("Warning " + i + " of 3."), "Warning " + i + " present");
        }
    }

    @Test
    @DocSection("Layer 5 — @DocCode multi-line preserves newlines")
    @DocCode({
        "line one",
        "line two",
        "line three"
    })
    public void layer5_docCodeMultiLinePreservesNewlines() throws IOException {
        finishDocTest();
        String md = readMarkdown();
        // Lines are joined with \n inside code fence
        Assertions.assertTrue(md.contains("line one\nline two\nline three"),
                "All three lines present in order");
    }

    // =========================================================================
    // LAYER 6 — Self-documentation: this class documents itself
    // =========================================================================

    @Test
    @DocSection("Layer 6 — all five annotations together (full API showcase)")
    @DocDescription({
        "This test demonstrates every annotation simultaneously on a single method.",
        "The generated markdown for this entry showcases the complete annotation API."
    })
    @DocNote({
        "The rendering order is always fixed: section → description → note → warning → code.",
        "This order applies regardless of the order the annotations appear in source."
    })
    @DocWarning("Never annotate a method with `@DocSection` more than once; only one heading per method is supported.")
    @DocCode(
        language = "java",
        value = {
            "@Test",
            "@DocSection(\"My API Section\")",
            "@DocDescription({",
            "    \"What this endpoint does.\",",
            "    \"Additional context.\"",
            "})",
            "@DocNote(\"Tip: use JSON for the request body.\")",
            "@DocWarning(\"Rate-limited to 100 req/min.\")",
            "@DocCode(language = \"json\", value = {",
            "    \"{ \\\"id\\\": 1, \\\"name\\\": \\\"Alice\\\" }\"",
            "})",
            "public void testMyApi() {",
            "    Response r = sayAndMakeRequest(Request.GET().url(testServerUrl().path(\"/api\")));",
            "    sayAndAssertThat(\"Status OK\", 200, equalTo(r.httpStatus()));",
            "}"
        }
    )
    public void layer6_allFiveAnnotationsTogether() throws IOException {
        finishDocTest();
        String md = readMarkdown();

        // Presence of all five layers' output
        Assertions.assertTrue(md.contains("Layer 6 — all five annotations together"),
                "Section heading present");
        Assertions.assertTrue(md.contains("This test demonstrates every annotation simultaneously"),
                "First description paragraph present");
        Assertions.assertTrue(md.contains("The generated markdown for this entry showcases"),
                "Second description paragraph present");
        Assertions.assertTrue(md.contains("The rendering order is always fixed"),
                "First note present");
        Assertions.assertTrue(md.contains("This order applies regardless"),
                "Second note present");
        Assertions.assertTrue(md.contains("Never annotate a method with"),
                "Warning present");
        Assertions.assertTrue(md.contains("@DocSection("),
                "Code block first line present");

        // Ordering: all five layers in sequence
        int sPos = md.indexOf("Layer 6 — all five annotations together");
        int dPos = md.indexOf("This test demonstrates every annotation simultaneously");
        int nPos = md.indexOf("The rendering order is always fixed");
        int wPos = md.indexOf("Never annotate a method with");
        int cPos = md.indexOf("@DocSection(");

        Assertions.assertTrue(sPos < dPos, "section < description");
        Assertions.assertTrue(dPos < nPos, "description < note");
        Assertions.assertTrue(nPos < wPos, "note < warning");
        Assertions.assertTrue(wPos < cPos, "warning < code");
    }

    @Test
    @DocSection("Layer 6 — backward compatibility: no annotations")
    public void layer6_backwardCompatNoAnnotations() throws IOException {
        sayNextSection("Fallback section via explicit call");
        say("A test method carrying zero doc annotations continues to work exactly as before.");
        sayAndAssertThat("Explicit assertion still works", 2 + 2, is(4));
        finishDocTest();
        File md = new File(MD_PATH);
        Assertions.assertTrue(md.exists(), "Markdown file exists");
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    /**
     * Reads the generated markdown file for this test class.
     * Calls {@link #finishDocTest()} beforehand to ensure the file is flushed.
     */
    private static String readMarkdown() throws IOException {
        return Files.toString(new File(MD_PATH), Charsets.UTF_8);
    }

    @AfterAll
    public static void afterClass() {
        finishDocTest();
    }
}
