/**
 * Copyright (C) 2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */
package org.r10r.doctester;

import com.google.common.base.Charsets;
import com.google.common.io.Files;
import org.junit.AfterClass;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

import java.io.File;
import java.io.IOException;
import java.util.regex.Pattern;

import static org.hamcrest.CoreMatchers.is;

/**
 * Comprehensive doctests for the DocTester annotation API.
 *
 * <p>Tests are organised in six layers of increasing depth:
 * <ol>
 *   <li><strong>Layer 1 — Individual annotations:</strong> each annotation in isolation</li>
 *   <li><strong>Layer 2 — Markdown structure:</strong> heading levels, anchor IDs, formatting</li>
 *   <li><strong>Layer 3 — Ordering guarantees:</strong> annotations always emit in section → description → note → warning → code order</li>
 *   <li><strong>Layer 4 — Interleaving:</strong> annotations coexist correctly with explicit {@code say*()} calls</li>
 *   <li><strong>Layer 5 — Edge cases:</strong> markdown-special characters, Unicode, multiple values, empty language hint</li>
 *   <li><strong>Layer 6 — Self-documentation:</strong> this class documents itself using all five annotation types</li>
 * </ol>
 *
 * <p>Each {@code @Test} method is also a living usage example; the markdown rendered
 * for this class is itself fully annotated using the API under test.
 */
public class AnnotationDocTest extends DocTester {

    /** Path to the markdown file generated by this test class. */
    private static final String MD_PATH =
            "target/docs/" + AnnotationDocTest.class.getName() + ".md";

    // =========================================================================
    // LAYER 1 — Individual annotations in isolation
    // =========================================================================

    @Test
    @DocSection("Layer 1 — @DocSection in isolation")
    @DocDescription("@DocSection adds an H1 heading entry to the document and to the left-hand TOC navbar.")
    @DocNote("This heading was produced entirely by the <code>@DocSection</code> annotation — no <code>sayNextSection()</code> call in the method body.")
    public void layer1_docSectionAlone() throws IOException {
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("@DocSection value appears in document body",
                html.contains("Layer 1 — @DocSection in isolation"));
    }

    @Test
    @DocSection("Layer 1 — @DocDescription (single value)")
    @DocDescription("A single-string @DocDescription injects exactly one <p> paragraph.")
    public void layer1_docDescriptionSingleValue() throws IOException {
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("Single @DocDescription value appears in HTML",
                html.contains("A single-string @DocDescription injects exactly one <p> paragraph."));
    }

    @Test
    @DocSection("Layer 1 — @DocDescription (multiple values)")
    @DocDescription({
        "First paragraph emitted by a multi-value @DocDescription.",
        "Second paragraph emitted by the same annotation.",
        "Third paragraph — each element becomes an independent <p> tag."
    })
    public void layer1_docDescriptionMultipleValues() throws IOException {
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("First description paragraph present", html.contains("First paragraph emitted by a multi-value @DocDescription."));
        Assert.assertTrue("Second description paragraph present", html.contains("Second paragraph emitted by the same annotation."));
        Assert.assertTrue("Third description paragraph present", html.contains("Third paragraph — each element becomes an independent <p> tag."));
    }

    @Test
    @DocSection("Layer 1 — @DocNote (single value)")
    @DocNote("A single-string @DocNote renders one Bootstrap info alert.")
    public void layer1_docNoteSingleValue() throws IOException {
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("@DocNote value appears in HTML",
                html.contains("A single-string @DocNote renders one Bootstrap info alert."));
        Assert.assertTrue("@DocNote uses alert-info CSS class",
                html.contains("alert-info"));
    }

    @Test
    @DocSection("Layer 1 — @DocNote (multiple values)")
    @DocNote({
        "First informational note.",
        "Second informational note."
    })
    public void layer1_docNoteMultipleValues() throws IOException {
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("First @DocNote value present", html.contains("First informational note."));
        Assert.assertTrue("Second @DocNote value present", html.contains("Second informational note."));
    }

    @Test
    @DocSection("Layer 1 — @DocWarning (single value)")
    @DocWarning("A single-string @DocWarning renders one Bootstrap warning alert.")
    public void layer1_docWarningSingleValue() throws IOException {
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("@DocWarning value appears in HTML",
                html.contains("A single-string @DocWarning renders one Bootstrap warning alert."));
        Assert.assertTrue("@DocWarning uses alert-warning CSS class",
                html.contains("alert-warning"));
    }

    @Test
    @DocSection("Layer 1 — @DocWarning (multiple values)")
    @DocWarning({
        "First warning message.",
        "Second warning message."
    })
    public void layer1_docWarningMultipleValues() throws IOException {
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("First @DocWarning present", html.contains("First warning message."));
        Assert.assertTrue("Second @DocWarning present", html.contains("Second warning message."));
    }

    @Test
    @DocSection("Layer 1 — @DocCode (single line, no language)")
    @DocCode("Response response = sayAndMakeRequest(Request.GET().url(testServerUrl()));")
    public void layer1_docCodeSingleLineNoLanguage() throws IOException {
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("@DocCode value appears in HTML",
                html.contains("Response response = sayAndMakeRequest(Request.GET().url(testServerUrl()));"));
        Assert.assertTrue("@DocCode rendered inside <pre><code>",
                html.contains("<pre><code>"));
    }

    @Test
    @DocSection("Layer 1 — @DocCode (multi-line, with language)")
    @DocCode(
        language = "java",
        value = {
            "Request req = Request.POST()",
            "    .url(testServerUrl().path(\"/api/users\"))",
            "    .contentTypeApplicationJson()",
            "    .payload(new UserDto(\"alice\", \"alice@example.com\"));",
            "Response res = sayAndMakeRequest(req);"
        }
    )
    public void layer1_docCodeMultiLineWithLanguage() throws IOException {
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("First @DocCode line present", html.contains("Request req = Request.POST()"));
        Assert.assertTrue("language class emitted on <code> element",
                html.contains("class=\"language-java\""));
    }

    // =========================================================================
    // =========================================================================
    // LAYER 3 — Ordering guarantees
    // =========================================================================

    @Test
    @DocSection("Layer 3 — section heading appears before description")
    @DocDescription("This description must appear after the H1 heading in the document.")
    public void layer3_sectionBeforeDescription() throws IOException {
        finishDocTest();
        String html = readHtml();
        int sectionPos = html.indexOf("Layer 3 — section heading appears before description");
        int descPos    = html.indexOf("This description must appear after the H1 heading");
        Assert.assertTrue("Section heading index must be less than description index",
                sectionPos < descPos);
        Assert.assertTrue("Both positions must be valid (content found)", sectionPos > 0 && descPos > 0);
    }

    @Test
    @DocSection("Layer 3 — description appears before note")
    @DocDescription("Description paragraph must precede the info note.")
    @DocNote("Info note must follow the description.")
    public void layer3_descriptionBeforeNote() throws IOException {
        finishDocTest();
        String html = readHtml();
        int descPos = html.indexOf("Description paragraph must precede the info note.");
        int notePos = html.indexOf("Info note must follow the description.");
        Assert.assertTrue("Description must appear before @DocNote", descPos < notePos);
    }

    @Test
    @DocSection("Layer 3 — note appears before warning")
    @DocNote("Info note must precede the warning.")
    @DocWarning("Warning must follow the info note.")
    public void layer3_noteBeforeWarning() throws IOException {
        finishDocTest();
        String html = readHtml();
        int notePos    = html.indexOf("Info note must precede the warning.");
        int warningPos = html.indexOf("Warning must follow the info note.");
        Assert.assertTrue("@DocNote must appear before @DocWarning", notePos < warningPos);
    }

    @Test
    @DocSection("Layer 3 — warning appears before code")
    @DocWarning("Warning must precede the code block.")
    @DocCode("// code block must follow the warning")
    public void layer3_warningBeforeCode() throws IOException {
        finishDocTest();
        String html = readHtml();
        int warningPos = html.indexOf("Warning must precede the code block.");
        int codePos    = html.indexOf("// code block must follow the warning");
        Assert.assertTrue("@DocWarning must appear before @DocCode", warningPos < codePos);
    }

    @Test
    @DocSection("Layer 3 — full pipeline order: section → desc → note → warning → code")
    @DocDescription("Narrative description in the middle of the pipeline.")
    @DocNote("Informational note after the description.")
    @DocWarning("Warning after the note.")
    @DocCode("// Code example at the end of the pipeline")
    public void layer3_fullPipelineOrder() throws IOException {
        finishDocTest();
        String html = readHtml();

        int sectionPos = html.indexOf("Layer 3 — full pipeline order");
        int descPos    = html.indexOf("Narrative description in the middle");
        int notePos    = html.indexOf("Informational note after the description.");
        int warnPos    = html.indexOf("Warning after the note.");
        int codePos    = html.indexOf("// Code example at the end");

        Assert.assertTrue("All five markers must be found", sectionPos > 0 && descPos > 0 && notePos > 0 && warnPos > 0 && codePos > 0);
        Assert.assertTrue("section < desc",    sectionPos < descPos);
        Assert.assertTrue("desc < note",       descPos    < notePos);
        Assert.assertTrue("note < warning",    notePos    < warnPos);
        Assert.assertTrue("warning < code",    warnPos    < codePos);
    }

    // =========================================================================
    // LAYER 4 — Interleaving with explicit say*() calls
    // =========================================================================

    @Test
    @DocSection("Layer 4 — @DocSection then explicit say()")
    public void layer4_annotationThenExplicitSay() throws IOException {
        say("This paragraph was written with an explicit say() call after the annotation-driven heading.");
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("Annotation-driven heading present",
                html.contains("Layer 4 — @DocSection then explicit say()"));
        Assert.assertTrue("Explicit say() paragraph present",
                html.contains("This paragraph was written with an explicit say() call"));
    }

    @Test
    @DocSection("Layer 4 — explicit sayNextSection() before @DocSection annotation")
    public void layer4_explicitSayNextSectionThenAnnotation() throws IOException {
        // Explicit call runs BEFORE the annotation is processed (annotations run in @Before)
        // so the annotation heading was already emitted; calling sayNextSection explicitly
        // here adds a *second* heading in the document
        sayNextSection("Manually-added subsection within layer 4 test");
        say("Two section headings exist: one from the annotation, one from this explicit call.");
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("Annotation heading present", html.contains("Layer 4 — explicit sayNextSection()"));
        Assert.assertTrue("Explicit extra heading present", html.contains("Manually-added subsection within layer 4 test"));
    }

    @Test
    @DocSection("Layer 4 — @DocDescription with additional explicit say()")
    @DocDescription("Annotation-driven description paragraph.")
    public void layer4_annotationDescThenExplicitSay() throws IOException {
        say("Additional paragraph via explicit say() call.");
        finishDocTest();
        String html = readHtml();
        int annotationDescPos = html.indexOf("Annotation-driven description paragraph.");
        int explicitSayPos    = html.indexOf("Additional paragraph via explicit say() call.");
        Assert.assertTrue("Both paragraphs present", annotationDescPos > 0 && explicitSayPos > 0);
        Assert.assertTrue("Annotation description appears before explicit say()",
                annotationDescPos < explicitSayPos);
    }

    @Test
    @DocSection("Layer 4 — @DocNote alongside explicit sayRaw()")
    @DocNote("Annotation-driven info note.")
    public void layer4_annotationNoteThenExplicitSayRaw() throws IOException {
        sayRaw("<div class=\"alert alert-success\">Explicit sayRaw() success alert.</div>");
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("Annotation note present", html.contains("Annotation-driven info note."));
        Assert.assertTrue("Explicit sayRaw() present", html.contains("Explicit sayRaw() success alert."));
    }

    @Test
    @DocSection("Layer 4 — @DocCode alongside explicit say() narrative")
    @DocCode(language = "http", value = {
        "GET /api/articles HTTP/1.1",
        "Host: localhost:8080",
        "Accept: application/json"
    })
    public void layer4_annotationCodeWithExplicitSay() throws IOException {
        say("The <code>@DocCode</code> block above was rendered by the annotation; this paragraph is from <code>say()</code>.");
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("HTTP code block present", html.contains("GET /api/articles HTTP/1.1"));
        Assert.assertTrue("language-http class present", html.contains("class=\"language-http\""));
        Assert.assertTrue("Explicit say() paragraph present",
                html.contains("The <code>@DocCode</code> block above was rendered by the annotation"));
    }

    // =========================================================================
    // LAYER 5 — Edge cases
    // =========================================================================

    @Test
    @DocSection("Layer 5 — special characters in @DocSection title")
    @DocDescription("The title contains em dashes, angle-bracket-like characters, and an ampersand: A & B.")
    public void layer5_specialCharsInSectionTitle() throws IOException {
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("Section with special chars appears in HTML",
                html.contains("Layer 5 — special characters in @DocSection title"));
    }

    @Test
    @DocSection("Layer 5 — Unicode in @DocDescription")
    @DocDescription("Japanese: 日本語テスト. Arabic: مرحبا. Emoji context: résumé, naïve, façade.")
    public void layer5_unicodeInDescription() throws IOException {
        finishDocTest();
        String html = readHtml();
        Assert.assertTrue("Unicode description paragraph present",
                html.contains("日本語テスト"));
        Assert.assertTrue("Arabic text present", html.contains("مرحبا"));
        Assert.assertTrue("Latin extended present", html.contains("résumé"));
    }

    @Test
    @DocSection("Layer 5 — many @DocDescription values (10 paragraphs)")
    @DocDescription({
        "Paragraph 1 of 10.",
        "Paragraph 2 of 10.",
        "Paragraph 3 of 10.",
        "Paragraph 4 of 10.",
        "Paragraph 5 of 10.",
        "Paragraph 6 of 10.",
        "Paragraph 7 of 10.",
        "Paragraph 8 of 10.",
        "Paragraph 9 of 10.",
        "Paragraph 10 of 10."
    })
    public void layer5_manyDescriptionValues() throws IOException {
        finishDocTest();
        String html = readHtml();
        for (int i = 1; i <= 10; i++) {
            Assert.assertTrue("Paragraph " + i + " present",
                    html.contains("Paragraph " + i + " of 10."));
        }
    }

    @Test
    @DocSection("Layer 5 — many @DocWarning values (3 warnings)")
    @DocWarning({
        "Warning 1 of 3.",
        "Warning 2 of 3.",
        "Warning 3 of 3."
    })
    public void layer5_manyWarningValues() throws IOException {
        finishDocTest();
        String html = readHtml();
        for (int i = 1; i <= 3; i++) {
            Assert.assertTrue("Warning " + i + " present", html.contains("Warning " + i + " of 3."));
        }
    }

    @Test
    @DocSection("Layer 5 — @DocCode multi-line preserves newlines")
    @DocCode({
        "line one",
        "line two",
        "line three"
    })
    public void layer5_docCodeMultiLinePreservesNewlines() throws IOException {
        finishDocTest();
        String html = readHtml();
        // Lines are joined with \n inside <pre><code>
        Assert.assertTrue("All three lines present in order",
                html.contains("line one\nline two\nline three"));
    }

    // =========================================================================
    // LAYER 6 — Self-documentation: this class documents itself
    // =========================================================================

    @Test
    @DocSection("Layer 6 — all five annotations together (full API showcase)")
    @DocDescription({
        "This test demonstrates every annotation simultaneously on a single method.",
        "The generated HTML for this entry showcases the complete annotation API."
    })
    @DocNote({
        "The rendering order is always fixed: section → description → note → warning → code.",
        "This order applies regardless of the order the annotations appear in source."
    })
    @DocWarning("Never annotate a method with <code>@DocSection</code> more than once; only one heading per method is supported.")
    @DocCode(
        language = "java",
        value = {
            "@Test",
            "@DocSection(\"My API Section\")",
            "@DocDescription({",
            "    \"What this endpoint does.\",",
            "    \"Additional context.\"",
            "})",
            "@DocNote(\"Tip: use JSON for the request body.\")",
            "@DocWarning(\"Rate-limited to 100 req/min.\")",
            "@DocCode(language = \"json\", value = {",
            "    \"{ \\\"id\\\": 1, \\\"name\\\": \\\"Alice\\\" }\"",
            "})",
            "public void testMyApi() {",
            "    Response r = sayAndMakeRequest(Request.GET().url(testServerUrl().path(\"/api\")));",
            "    sayAndAssertThat(\"Status OK\", 200, equalTo(r.httpStatus()));",
            "}"
        }
    )
    public void layer6_allFiveAnnotationsTogether() throws IOException {
        finishDocTest();
        String html = readHtml();

        // Presence of all five layers' output
        Assert.assertTrue("Section heading present",
                html.contains("Layer 6 — all five annotations together"));
        Assert.assertTrue("First description paragraph present",
                html.contains("This test demonstrates every annotation simultaneously"));
        Assert.assertTrue("Second description paragraph present",
                html.contains("The generated HTML for this entry showcases"));
        Assert.assertTrue("First note present",
                html.contains("The rendering order is always fixed"));
        Assert.assertTrue("Second note present",
                html.contains("This order applies regardless"));
        Assert.assertTrue("Warning present",
                html.contains("Never annotate a method with"));
        Assert.assertTrue("Code block first line present",
                html.contains("@DocSection("));
        Assert.assertTrue("Code block contains HTML-escaped quotes",
                html.contains("&quot;"));

        // Ordering: all five layers in sequence
        int sPos = html.indexOf("Layer 6 — all five annotations together");
        int dPos = html.indexOf("This test demonstrates every annotation simultaneously");
        int nPos = html.indexOf("The rendering order is always fixed");
        int wPos = html.indexOf("Never annotate a method with");
        int cPos = html.indexOf("@DocSection(");

        Assert.assertTrue("section < description", sPos < dPos);
        Assert.assertTrue("description < note",    dPos < nPos);
        Assert.assertTrue("note < warning",        nPos < wPos);
        Assert.assertTrue("warning < code",        wPos < cPos);
    }

    @Test
    @DocSection("Layer 6 — backward compatibility: no annotations")
    public void layer6_backwardCompatNoAnnotations() throws IOException {
        sayNextSection("Fallback section via explicit call");
        say("A test method carrying zero doc annotations continues to work exactly as before.");
        sayAndAssertThat("Explicit assertion still works", 2 + 2, is(4));
        finishDocTest();
        File html = new File(MD_PATH);
        Assert.assertTrue("HTML file exists", html.exists());
    }

    // =========================================================================
    // Helpers
    // =========================================================================

    /**
     * Reads the generated HTML file for this test class.
     * Calls {@link #finishDocTest()} beforehand to ensure the file is flushed.
     */
    private static String readHtml() throws IOException {
        return Files.toString(new File(MD_PATH), Charsets.UTF_8);
    }

    @AfterClass
    public static void afterClass() {
        finishDocTest();
    }
}
